-----------------------------------
-- Spell shim: Distract III  (Trust dispatch)
-- The spell_list row id 882 has group=Trust, but the working
-- implementation lives at scripts/actions/spells/black/distract_iii.lua. The engine only looks
-- in the folder matching the DB group, so without this shim Trust
-- NPCs scripted to cast Distract III would silently no-op.
--
-- This shim re-uses the canonical implementation. Zero behavioral
-- divergence between player-cast and Trust-cast versions.
-----------------------------------
return require('scripts/actions/spells/black/distract_iii')
