-- Auto-generated by tools/gen_windower_catalog.py -- do not edit manually.
-- Source: modules/custom/lua/augment_affinity_catalog.lua
-- One row per augment category: display name + the affinity NM that unlocks it.
return {
    [ 1] = { name = 'Base stats', nm = 'Behemoth' },
    [ 2] = { name = 'Melee', nm = 'King Behemoth' },
    [ 3] = { name = 'Magic', nm = 'Ouryu' },
    [ 4] = { name = 'Defense', nm = 'Genbu' },
    [ 5] = { name = 'Delays', nm = 'Byakko' },
    [ 6] = { name = 'Duration', nm = 'Aspidochelone' },
    [ 7] = { name = 'Pets', nm = 'King Vinegarroon' },
    [ 8] = { name = 'Potency', nm = 'Phoenix' },
    [ 9] = { name = 'Skills', nm = 'Absolute Virtue' },
    [10] = { name = 'Exp/Cap Points', nm = 'Proto-Omega' },
    [11] = { name = 'Job specific niche utilities', nm = 'Kirin' },
}
