"""Generate Accessory NPC tables inside docs/progression/gear-vendors.md.

Reads `modules/custom/lua/accessory_catalog.lua` and writes one marker block
per tier (bronze/silver/gold). Each tier renders five tables, one per
accessory slot (neck/waist/ear/ring/back).

Marker IDs:
  - "accessory-bronze"
  - "accessory-silver"
  - "accessory-gold"

The catalog is normally gitignored (auto-generated by score_accessories.py),
so this generator runs against `$LEGENDARY_LIVE_ROOT`. CI without that env
var skips cleanly.
"""
from __future__ import annotations

import re
from pathlib import Path

from tools.docgen._paths import resolve_source
from tools.docgen._markers import write_between_markers
from tools.docgen._bgwiki import urls_for_item
from tools.docgen.generators._vendor_common import tier_pill, tier_legend, tier_summary


_QUOTED = r"(?:'((?:[^'\\]|\\.)*)'|\"([^\"]*)\")"
_NAME_RE = re.compile(r"\bname\s*=\s*" + _QUOTED)
_COST_RE = re.compile(r"\bcost\s*=\s*(\d+)")
_JOBS_RE = re.compile(r"\bjobs\s*=\s*" + _QUOTED)
_ID_RE   = re.compile(r"\bid\s*=\s*(\d+)")

# Matches lines like:
#   table.insert(b.neck, { id = ..., name = '...', cost = N, jobs = '...' })  -- DD score N
# Group 1: short var (b/s/g), group 2: slot (neck/waist/...), group 3: row body
_INSERT_RE = re.compile(
    r"table\.insert\(\s*(\w+)\.(\w+)\s*,\s*\{([^}]*)\}\s*\)",
    re.DOTALL,
)

# Maps the local short var to its tier:  local b = catalog.bronze
_BIND_RE = re.compile(r"local\s+(\w+)\s*=\s*catalog\.(\w+)\b")

# Pulls the trailing role/score comment (post-`})`) so the docs surface
# the same scoring context the catalog comments do.
_TRAILING_SCORE_RE = re.compile(
    r"--\s*(DD|TANK|CASTER|HEAL)\s*score\s+(\d+)(?:\s*\[(.*?)\])?\s*$"
)

_SLOT_ORDER = ("neck", "waist", "ear", "ring", "back")
_SLOT_LABEL = {
    "neck":  "Neck",
    "waist": "Waist",
    "ear":   "Earring",
    "ring":  "Ring",
    "back":  "Back",
}
_TIER_ORDER = ("bronze", "silver", "gold")

# Short per-tier descriptions for the legend under the Accessory heading.
_ACCESSORY_TIER_DESC = {
    "gold": "BiS",
}


def _quoted_value(m: re.Match) -> str:
    raw = m.group(1) if m.group(1) is not None else m.group(2)
    return raw.replace("\\'", "'").replace('\\"', '"').replace("\\\\", "\\")


def _escape_md(s: str) -> str:
    return s.replace("|", "\\|").replace("\n", " ")


def _item_link(name: str) -> str:
    page_url, image_url = urls_for_item(name, None)
    return (
        f'<a class="item-link" href="{page_url}" '
        f'data-img="{image_url}" target="_blank" rel="noopener">'
        f'{_escape_md(name)}</a>'
    )


def _extract(text: str) -> dict:
    """Returns:
      {
        'bronze': {'neck': [{id,name,cost,jobs,role,score,flags}, ...], ...},
        'silver': {...},
        'gold':   {...},
      }
    """
    var_to_tier: dict[str, str] = {}
    for m in _BIND_RE.finditer(text):
        var_to_tier[m.group(1)] = m.group(2)

    out: dict[str, dict[str, list[dict]]] = {t: {s: [] for s in _SLOT_ORDER} for t in _TIER_ORDER}

    for m in _INSERT_RE.finditer(text):
        var, slot, body = m.group(1), m.group(2), m.group(3)
        tier = var_to_tier.get(var)
        if tier not in out:
            continue
        if slot not in _SLOT_ORDER:
            continue
        id_m   = _ID_RE.search(body)
        name_m = _NAME_RE.search(body)
        cost_m = _COST_RE.search(body)
        jobs_m = _JOBS_RE.search(body)
        if not (id_m and name_m and cost_m):
            continue

        # Look for the role/score comment after the `})` close. We need
        # to scan forward from the match end to the next newline.
        line_end = text.find("\n", m.end())
        if line_end == -1:
            line_end = len(text)
        tail = text[m.end():line_end]
        score_m = _TRAILING_SCORE_RE.search(tail)

        out[tier][slot].append({
            "id":    int(id_m.group(1)),
            "name":  _quoted_value(name_m),
            "cost":  int(cost_m.group(1)),
            "jobs":  _quoted_value(jobs_m) if jobs_m else "?",
            "role":  score_m.group(1) if score_m else "",
            "score": int(score_m.group(2)) if score_m else 0,
            "flags": score_m.group(3) if score_m and score_m.group(3) else "",
        })
    return out


# Fallback if the catalog doesn't expose a seals table.
_FALLBACK_CURRENCY = {
    "bronze": "Beastmens Medal",
    "silver": "Kindreds Medal",
    "gold":   "Demons Medal",
}

_SEAL_TIER_RE = re.compile(
    r"(bronze|silver|gold)\s*=\s*\{[^}]*?name\s*=\s*['\"]([^'\"]+)['\"]",
)

def _parse_tier_currency(catalog_text: str) -> dict:
    found = {}
    for m in _SEAL_TIER_RE.finditer(catalog_text):
        found[m.group(1)] = m.group(2)
    return found


def _render_accessory_slots(by_tier: dict[str, dict[str, list[dict]]], tier_currency: dict) -> str:
    """Slot-first render: one table per accessory slot, all tiers together,
    tier shown as a pill column. Within a slot the tiers run Bronze -> Gold,
    and within each tier the top pick reads first by ceiling score.
    `by_tier` is {tier: {slot: [rows]}}."""
    per_tier = {t: sum(len(items) for items in by_tier[t].values()) for t in _TIER_ORDER}
    total = sum(per_tier.values())
    if total == 0:
        return "_No accessories parsed from the catalog._"

    lines = [
        tier_summary(per_tier, "accessories"),
        "",
        tier_legend(tier_currency, _ACCESSORY_TIER_DESC),
        "",
        "_Within each slot, tiers run Bronze → Gold; the top pick per tier is "
        "listed first by role-balanced ceiling score._",
        "",
    ]
    for slot in _SLOT_ORDER:
        # All tiers for this slot; within a tier sort by score desc.
        slot_rows: list[tuple[str, dict]] = []
        for t in _TIER_ORDER:
            for it in sorted(by_tier[t].get(slot, []), key=lambda r: -r["score"]):
                slot_rows.append((t, it))
        if not slot_rows:
            continue
        lines.append(f"### {_SLOT_LABEL[slot]}")
        lines.append("")
        lines.append("| Item | Tier | Cost | Jobs | Top role (score) | Flags |")
        lines.append("|---|---|--:|---|---|:---:|")
        for tier, it in slot_rows:
            role_cell = f"{it['role']} ({it['score']})" if it['role'] else "—"
            flag_cell = _escape_md(it["flags"]) if it["flags"] else "—"
            pill = tier_pill(tier, tier_currency.get(tier))
            lines.append(
                f"| {_item_link(it['name'])} | {pill} | {it['cost']} | "
                f"{_escape_md(it['jobs'])} | {role_cell} | {flag_cell} |"
            )
        lines.append("")
    return "\n".join(lines).rstrip()


def generate(repo_root: Path, docs_dir: Path) -> None:
    src = resolve_source(repo_root, "modules/custom/lua/accessory_catalog.lua")
    if src is None:
        print("[accessory_npc] skip: accessory_catalog.lua not found")
        return

    text = src.read_text(encoding="utf-8", errors="replace")
    parsed_currency = _parse_tier_currency(text)
    tier_currency = {
        t: parsed_currency.get(t, _FALLBACK_CURRENCY[t]) for t in _TIER_ORDER
    }
    print(f"[accessory_npc] tier currencies: {tier_currency}")

    by_tier = _extract(text)

    # Sanity guard: if the catalog clearly has insert blocks but we parsed
    # nothing, raise so the page keeps its previous content instead of
    # publishing "_No data_" as a regression.
    if "table.insert" in text and not any(
        any(slot_items) for slot_items in by_tier.values()
    ):
        raise RuntimeError(
            "accessory_catalog.lua has `table.insert` rows but the "
            "extractor returned zero entries. Field renames "
            "(id/name/cost/jobs) — update regexes in accessory_npc.py."
        )

    page = docs_dir / "progression" / "gear-vendors.md"
    if not page.exists():
        print(f"[accessory_npc] skip: page not found ({page})")
        return

    content = _render_accessory_slots(by_tier, tier_currency)
    if write_between_markers(page, "accessory-slots", content):
        n = sum(len(items) for tmap in by_tier.values() for items in tmap.values())
        print(f"[accessory_npc] accessory-slots: {n} items written (slot-first)")
    else:
        print(f"[accessory_npc] accessory-slots: marker missing in {page.name}")
