-----------------------------------
-- accessory_catalog.lua
-- Endgame accessories for the Accessory NPC.
-- Covers Neck / Waist / Earring / Ring / Back.
--
-- Tiers (medal currencies, same trio as Armor / Weapons NPCs):
--   Bronze   = Beastmens Medal   (entry)
--   Silver   = Kindreds Medal    (mid)
--   Gold     = Demons Medal      (BiS endgame)
--
-- HOW THIS FILE IS MAINTAINED:
--   * Placement config (zoneId/zonePath/vendorPos/seals/goldExtraDrop)
--     is rewritten on every regen, sourced from constants at the top
--     of tools/score_accessories.py. If you want the NPC somewhere
--     else, edit those constants.
--   * Tier contents (the table.insert blocks below) are scored from
--     the live item DB and rewritten on every regen.
--
-- AUTO-GENERATED by tools/score_accessories.py — do NOT hand-edit.
-- To regenerate after the DB or weight maps change:
--     python tools/score_accessories.py
-- (or run tools/rebalance_all.bat to re-rank every gear catalog at once)
-----------------------------------
local catalog = {}

-----------------------------------
-- ZONE / NPC PLACEMENT
--   Single source of truth for:
--     - Accessory_NPC.lua : override registration + NPC position
--     - docgen            : gear-vendors.md location table + zone prose
--   Sits next to the Armor NPC and Weapons NPC at Reisenjima Henge
--   so players don't zone-hop between gear vendors.
-----------------------------------
catalog.zoneId    = xi.zone.REISENJIMA_HENGE
catalog.zonePath  = 'xi.zones.Reisenjima_Henge'
catalog.vendorPos = { x = 9.0000, y = 5.5090, z = -12.1827, rot = 230 }

-----------------------------------
-- SEAL CURRENCY DEFINITIONS (shared with Armor / Weapons NPCs)
-----------------------------------
catalog.seals =
{
    bronze = { id = 9539, name = 'Beastmens Medal' },
    silver = { id = 9541, name = 'Kindreds Medal'  },
    gold   = { id = 9543, name = 'Demons Medal'    },
}

-- Gold-tier extra requirement: disabled. Mirrors the Armor NPC's
-- pattern — set this to { id = X, qty = N, name = '...' } if you
-- want Gold accessories to require an additional drop on top of
-- the seal cost. With nil, Gold accessories cost only the medal.
catalog.goldExtraDrop = nil

-----------------------------------
-- Helper: empty slot tables for a tier
-----------------------------------
local function emptySlots()
    return { neck = {}, waist = {}, ear = {}, ring = {}, back = {} }
end

-----------------------------------
-- BRONZE TIER  (15 medals/piece)
-----------------------------------
catalog.bronze = emptySlots()
local b = catalog.bronze

-- neck
table.insert(b.neck, { id =  11581, name = 'Ire Torque'                        , cost =  15, jobs = 'All' })  -- DPS score 6
table.insert(b.neck, { id =  15524, name = 'Fortified Chain'                   , cost =  15, jobs = 'All' })  -- TANK score 7
table.insert(b.neck, { id =  28393, name = 'Goetic Torque'                     , cost =  15, jobs = 'All' })  -- CASTER score 7 [EX]
table.insert(b.neck, { id =  13073, name = 'Holy Phial'                        , cost =  15, jobs = 'All' })  -- HEAL score 6
table.insert(b.neck, { id =  16271, name = 'Lieutenants Gorget'                , cost =  15, jobs = 'All' })  -- DPS score 6 [RARE,EX]
table.insert(b.neck, { id =  10919, name = 'Tandem Necklace +1'                , cost =  15, jobs = 'All' })  -- TANK score 6 [RARE,EX]
table.insert(b.neck, { id =  16262, name = 'Mohbwa Scarf +1'                   , cost =  15, jobs = 'All' })  -- CASTER score 6
table.insert(b.neck, { id =  11580, name = 'Fylgja Torque +1'                  , cost =  15, jobs = 'WHM/BLM/RDM/BRD/SMN/PUP/SCH/GEO' })  -- HEAL score 6

-- waist
table.insert(b.waist, { id =  11774, name = 'Oneiros Cest'                      , cost =  15, jobs = 'WAR/RDM/THF/PLD/DRK/BST/BRD/RNG/SAM/NIN/DRG/BLU/COR/DNC/RUN' })  -- DPS score 6 [RARE,EX]
table.insert(b.waist, { id =  13194, name = 'Warriors Belt'                     , cost =  15, jobs = 'WAR/MNK/RDM/THF/PLD/DRK/BST/BRD/SAM/NIN/DRG/BLU/COR/DNC/RUN' })  -- TANK score 6
table.insert(b.waist, { id =  15433, name = 'Reverend Sash'                     , cost =  15, jobs = 'MNK/WHM/BLM/RDM/PLD/BRD/RNG/SMN/BLU/PUP/SCH/GEO/RUN' })  -- CASTER score 6
table.insert(b.waist, { id =  15302, name = 'Scouters Rope'                     , cost =  15, jobs = 'MNK/WHM/RDM/THF/BST/BRD/RNG/SAM/NIN/BLU/COR/DNC/RUN' })  -- DPS score 6
table.insert(b.waist, { id =  13247, name = 'Mithran Stone'                     , cost =  15, jobs = 'All' })  -- TANK score 6
table.insert(b.waist, { id =  28424, name = 'Shinjutsu-no-obi +1'               , cost =  15, jobs = 'WHM/BLM/RDM/BRD/SMN/SCH/GEO' })  -- CASTER score 4 [RARE,EX]
table.insert(b.waist, { id =  15914, name = 'Peiste Belt +1'                    , cost =  15, jobs = 'WAR/RDM/THF/PLD/DRK/BST/BRD/RNG/SAM/NIN/DRG/BLU/COR/DNC/RUN' })  -- DPS score 5
table.insert(b.waist, { id =  10821, name = 'Olympus Sash'                      , cost =  15, jobs = 'All' })  -- TANK score 6 [RARE]

-- ear
table.insert(b.ear, { id =  25522, name = 'Karagoz Earring'                   , cost =  15, jobs = 'PUP' })  -- DPS score 2 [EX]
table.insert(b.ear, { id =  14757, name = 'Mecurial Earring'                  , cost =  15, jobs = 'All' })  -- TANK score 3
table.insert(b.ear, { id =  27534, name = 'Evans Earring'                     , cost =  15, jobs = 'All' })  -- CASTER score 2 [RARE,EX]
table.insert(b.ear, { id =  14814, name = 'Diaboloss Earring'                 , cost =  15, jobs = 'All' })  -- DPS score 2 [RARE,EX]
table.insert(b.ear, { id =  13329, name = 'Orichalcum Earring'                , cost =  15, jobs = 'All' })  -- TANK score 2
table.insert(b.ear, { id =  28506, name = 'Andoaa Earring'                    , cost =  15, jobs = 'All' })  -- CASTER score 2 [RARE,EX]
table.insert(b.ear, { id =  14729, name = 'Pilferers Earring'                 , cost =  15, jobs = 'All' })  -- DPS score 2 [RARE]
table.insert(b.ear, { id =  11714, name = 'Unkai Mimikazari'                  , cost =  15, jobs = 'SAM' })  -- DPS score 2 [RARE,EX]

-- ring
table.insert(b.ring, { id =  13553, name = 'Blitz Ring'                        , cost =  15, jobs = 'WAR/PLD/DRK/BST/DRG' })  -- DPS score 5 [RARE]
table.insert(b.ring, { id =  10791, name = 'Haomas Ring'                       , cost =  15, jobs = 'All' })  -- TANK score 5
table.insert(b.ring, { id =  10752, name = 'Prolix Ring'                       , cost =  15, jobs = 'All' })  -- CASTER score 5 [RARE]
table.insert(b.ring, { id =  11672, name = 'Mujin Band'                        , cost =  15, jobs = 'All' })  -- WS score 5 [RARE]
table.insert(b.ring, { id =  10751, name = 'Valseurs Ring'                     , cost =  15, jobs = 'All' })  -- DPS score 4 [RARE]
table.insert(b.ring, { id =  10793, name = 'Eshmuns Ring'                      , cost =  15, jobs = 'All' })  -- TANK score 5
table.insert(b.ring, { id =  13284, name = 'Eremites Ring'                     , cost =  15, jobs = 'All' })  -- CASTER score 4
table.insert(b.ring, { id =  15784, name = 'Dominion Ring'                     , cost =  15, jobs = 'WAR/MNK/THF/BST/BRD/RNG/SAM/NIN/DRG/COR/PUP/DNC' })  -- HEAL score 5

-- back
table.insert(b.back, { id =  10984, name = 'Tjukurrpa Mantle'                  , cost =  15, jobs = 'THF/RNG' })  -- DPS score 6 [RARE]
table.insert(b.back, { id =  13595, name = 'Coeurl Mantle'                     , cost =  15, jobs = 'THF/BST/RNG/DNC/RUN' })  -- TANK score 6
table.insert(b.back, { id =  13586, name = 'Red Cape'                          , cost =  15, jobs = 'WHM/BLM/RDM/BRD/SMN/BLU/PUP/SCH/GEO' })  -- CASTER score 6
table.insert(b.back, { id =  11008, name = 'Medala Cape'                       , cost =  15, jobs = 'WHM/BLM/RDM/BRD/SMN/BLU/PUP/SCH/GEO' })  -- HEAL score 6 [RARE,EX]
table.insert(b.back, { id =  11540, name = 'Accura Cape +1'                    , cost =  15, jobs = 'WAR/MNK/RDM/THF/PLD/DRK/BST/BRD/RNG/SAM/NIN/DRG/BLU/COR/DNC/RUN' })  -- DPS score 6
table.insert(b.back, { id =  13680, name = 'Variable Mantle'                   , cost =  15, jobs = 'WAR/MNK/RDM/THF/PLD/DRK/BST/BRD/RNG/SAM/NIN/DRG/BLU/COR/DNC/RUN' })  -- TANK score 6 [RARE,EX]
table.insert(b.back, { id =  13610, name = 'Black Cape +1'                     , cost =  15, jobs = 'WHM/BLM/RDM/BRD/SMN/BLU/PUP/SCH/GEO' })  -- CASTER score 6
table.insert(b.back, { id =  11554, name = 'Orison Cape'                       , cost =  15, jobs = 'WHM' })  -- HEAL score 6 [RARE,EX]


-----------------------------------
-- SILVER TIER  (32 medals/piece)
-----------------------------------
catalog.silver = emptySlots()
local s = catalog.silver

-- neck
table.insert(s.neck, { id =  13162, name = 'Brisingamen +1'                    , cost =  32, jobs = 'All' })  -- DPS score 19
table.insert(s.neck, { id =  25543, name = 'Futhark Torque'                    , cost =  32, jobs = 'RUN' })  -- TANK score 19
table.insert(s.neck, { id =  28385, name = 'Atzintli Necklace'                 , cost =  32, jobs = 'All' })  -- CASTER score 19 [RARE]
table.insert(s.neck, { id =  11594, name = 'Estoqueurs Collar'                 , cost =  32, jobs = 'RDM' })  -- HEAL score 17 [RARE,EX]
table.insert(s.neck, { id =  28359, name = 'Shifting Necklace +1'              , cost =  32, jobs = 'All' })  -- DPS score 18
table.insert(s.neck, { id =  10946, name = 'Coatl Gorget'                      , cost =  32, jobs = 'PLD/DRK' })  -- TANK score 18 [RARE]
table.insert(s.neck, { id =  10942, name = 'Aifes Medal'                       , cost =  32, jobs = 'All' })  -- CASTER score 18 [RARE]
table.insert(s.neck, { id =  11621, name = 'Chrysopoeia Torque'                , cost =  32, jobs = 'WHM/BLM/BRD/SMN/SCH/GEO' })  -- HEAL score 16 [RARE,EX]

-- waist
table.insert(s.waist, { id =  10817, name = 'Moepapa Stone'                     , cost =  32, jobs = 'BST/DRG/SMN/PUP' })  -- DPS score 15 [RARE]
table.insert(s.waist, { id =  28436, name = 'Sveltesse Gouriz +1'               , cost =  32, jobs = 'MNK/WHM/RDM/THF/BST/BRD/RNG/SAM/NIN/BLU/COR/DNC/RUN' })  -- TANK score 16
table.insert(s.waist, { id =  10840, name = 'Aswang Sash'                       , cost =  32, jobs = 'WHM/BLM/RDM/BRD/SMN/BLU/SCH/GEO' })  -- CASTER score 16 [RARE]
table.insert(s.waist, { id =  28455, name = 'Ovate Rope'                        , cost =  32, jobs = 'WHM/BLM/RDM/BRD/RNG/NIN/SMN/BLU/PUP/SCH/GEO' })  -- HEAL score 16 [RARE]
table.insert(s.waist, { id =  13198, name = 'Swordbelt'                         , cost =  32, jobs = 'WAR/RDM/THF/PLD/DRK/BST/BRD/RNG/SAM/NIN/DRG/BLU/COR/DNC/RUN' })  -- WS score 15
table.insert(s.waist, { id =  10826, name = 'Witful Belt'                       , cost =  32, jobs = 'WHM/BLM/RDM/BRD/SMN/BLU/SCH/GEO' })  -- DPS score 15 [RARE]
table.insert(s.waist, { id =  10832, name = 'Carriers Sash'                     , cost =  32, jobs = 'All' })  -- TANK score 15 [RARE]
table.insert(s.waist, { id =  15874, name = 'Sorcerers Belt'                    , cost =  32, jobs = 'BLM' })  -- CASTER score 16 [RARE,EX]

-- ear
table.insert(s.ear, { id =  15979, name = 'Fowling Earring'                   , cost =  32, jobs = 'WAR/PLD/DRK/SAM/DRG' })  -- DPS score 6 [RARE]
table.insert(s.ear, { id =  14718, name = 'Hades Earring +1'                  , cost =  32, jobs = 'All' })  -- TANK score 7
table.insert(s.ear, { id =  11015, name = 'Snow Pearl'                        , cost =  32, jobs = 'All' })  -- CASTER score 6
table.insert(s.ear, { id =  15992, name = 'Celestial Earring'                 , cost =  32, jobs = 'All' })  -- HEAL score 7
table.insert(s.ear, { id =  14764, name = 'Minuet Earring'                    , cost =  32, jobs = 'All' })  -- DPS score 6 [RARE]
table.insert(s.ear, { id =  14793, name = 'Belinkys Earring'                  , cost =  32, jobs = 'All' })  -- TANK score 7 [RARE,EX]
table.insert(s.ear, { id =  11049, name = 'Myrddin Pearl'                     , cost =  32, jobs = 'All' })  -- CASTER score 6 [RARE]
table.insert(s.ear, { id =  11019, name = 'Aqua Pearl'                        , cost =  32, jobs = 'All' })  -- HEAL score 6

-- ring
table.insert(s.ring, { id =  10761, name = 'Portus Annulet'                    , cost =  32, jobs = 'All' })  -- DPS score 10 [RARE,EX]
table.insert(s.ring, { id =  28543, name = 'Rhodium Ring +1'                   , cost =  32, jobs = 'All' })  -- TANK score 10
table.insert(s.ring, { id =  10759, name = 'Aifes Annulet'                     , cost =  32, jobs = 'All' })  -- CASTER score 10 [RARE,EX]
table.insert(s.ring, { id =  10757, name = 'Tjukurrpa Annulet'                 , cost =  32, jobs = 'All' })  -- HEAL score 10 [RARE,EX]
table.insert(s.ring, { id =  11658, name = 'Stormsoul Ring'                    , cost =  32, jobs = 'All' })  -- DPS score 10
table.insert(s.ring, { id =  10760, name = 'Portus Ring'                       , cost =  32, jobs = 'All' })  -- TANK score 10 [RARE,EX]
table.insert(s.ring, { id =  10779, name = 'Sophia Ring'                       , cost =  32, jobs = 'All' })  -- CASTER score 10 [RARE]
table.insert(s.ring, { id =  10780, name = 'Quies Ring'                        , cost =  32, jobs = 'All' })  -- HEAL score 10 [RARE]

-- back
table.insert(s.back, { id =  11555, name = 'Ferine Mantle'                     , cost =  32, jobs = 'BST' })  -- DPS score 18 [RARE,EX]
table.insert(s.back, { id =  26246, name = 'Cichols Mantle'                    , cost =  32, jobs = 'WAR' })  -- TANK score 18 [EX]
table.insert(s.back, { id =  10976, name = 'Kaikias Cape'                      , cost =  32, jobs = 'WHM/BLM/RDM/BRD/SMN/BLU/PUP/SCH/GEO' })  -- CASTER score 18 [RARE]
table.insert(s.back, { id =  11000, name = 'Swith Cape'                        , cost =  32, jobs = 'WHM/BLM/RDM/BRD/SMN/BLU/PUP/SCH/GEO' })  -- HEAL score 18
table.insert(s.back, { id =  10967, name = 'Aisance Mantle +1'                 , cost =  32, jobs = 'WAR/MNK/RDM/THF/PLD/DRK/BST/BRD/RNG/SAM/NIN/DRG/BLU/COR/DNC/RUN' })  -- DPS score 18
table.insert(s.back, { id =  13633, name = 'Empowering Mantle'                 , cost =  32, jobs = 'MNK/WHM/RDM/THF/BST/BRD/RNG/SAM/NIN/BLU/COR/DNC/RUN' })  -- TANK score 17
table.insert(s.back, { id =  16203, name = 'Goetia Mantle'                     , cost =  32, jobs = 'BLM' })  -- CASTER score 18 [RARE,EX]
table.insert(s.back, { id =  27599, name = 'Dew Silk Cape +1'                  , cost =  32, jobs = 'WHM/BLM/RDM/BRD/SMN/BLU/PUP/SCH/GEO' })  -- HEAL score 18 [RARE]


-----------------------------------
-- GOLD TIER  (60 medals/piece)
-----------------------------------
catalog.gold = emptySlots()
local g = catalog.gold

-- neck
table.insert(g.neck, { id =  25473, name = 'Bards Charm +2'                    , cost =  60, jobs = 'BRD' })  -- DPS score 69
table.insert(g.neck, { id =  26037, name = 'Moonlight Necklace'                , cost =  60, jobs = 'WAR/MNK/PLD/NIN/RUN' })  -- TANK score 72
table.insert(g.neck, { id =  25437, name = 'Sorcerers Stole +2'                , cost =  60, jobs = 'BLM' })  -- CASTER score 81
table.insert(g.neck, { id =  26033, name = 'Moonbow Whistle +1'                , cost =  60, jobs = 'BRD' })  -- HEAL score 34
table.insert(g.neck, { id =  27510, name = 'Fotia Gorget'                      , cost =  60, jobs = 'All' })  -- WS score 80 [RARE,EX]
table.insert(g.neck, { id =  26026, name = 'Shulmanu Collar'                   , cost =  60, jobs = 'BST/DRG/SMN/PUP' })  -- DPS score 68 [RARE,EX]
table.insert(g.neck, { id =  25455, name = 'Knights Bead Necklace +2'          , cost =  60, jobs = 'PLD' })  -- TANK score 70
table.insert(g.neck, { id =  26086, name = 'Nicanders Necklace'                , cost =  60, jobs = 'All' })  -- CASTER score 68 [RARE]

-- waist
table.insert(g.waist, { id =  26340, name = 'Moonbow Belt'                      , cost =  60, jobs = 'MNK/PUP' })  -- DPS score 123
table.insert(g.waist, { id =  11750, name = 'Creed Baudrier'                    , cost =  60, jobs = 'PLD' })  -- TANK score 57 [RARE,EX]
table.insert(g.waist, { id =  26356, name = 'Skrymir Cord'                      , cost =  60, jobs = 'All' })  -- CASTER score 145
table.insert(g.waist, { id =  26329, name = 'Luminary Sash'                     , cost =  60, jobs = 'MNK/WHM/BLM/RDM/PLD/BRD/RNG/SMN/BLU/PUP/SCH/GEO/RUN' })  -- CASTER score 32 [RARE,EX]
table.insert(g.waist, { id =  26360, name = 'Gerdr Belt'                        , cost =  60, jobs = 'WAR/MNK/RDM/THF/PLD/DRK/BST/BRD/SAM/NIN/DRG/BLU/COR/DNC/RUN' })  -- DPS score 92
table.insert(g.waist, { id =  28437, name = 'Flume Belt +1'                     , cost =  60, jobs = 'WAR/RDM/THF/PLD/DRK/BST/BRD/RNG/SAM/NIN/DRG/BLU/COR/DNC/RUN' })  -- TANK score 55 [RARE]
table.insert(g.waist, { id =  26351, name = 'Sacro Cord'                        , cost =  60, jobs = 'WHM/BLM/RDM/BLU/SCH/GEO' })  -- CASTER score 64 [RARE,EX]
table.insert(g.waist, { id =  28420, name = 'Fotia Belt'                        , cost =  60, jobs = 'All' })  -- WS score 80 [RARE,EX]

-- ear
table.insert(g.ear, { id =  25421, name = 'Boii Earring +1'                   , cost =  60, jobs = 'WAR' })  -- DPS score 51 [EX]
table.insert(g.ear, { id =  28478, name = 'Etiolation Earring'                , cost =  60, jobs = 'All' })  -- TANK score 43 [RARE,EX]
table.insert(g.ear, { id =  26085, name = 'Regal Earring'                     , cost =  60, jobs = 'WHM/BLM/RDM/BRD/BLU/SCH/GEO' })  -- CASTER score 52 [RARE,EX]
table.insert(g.ear, { id =  13421, name = 'Medicine Earring'                  , cost =  60, jobs = 'WHM' })  -- HEAL score 45 [RARE]
table.insert(g.ear, { id =  26107, name = 'Thrud Earring'                     , cost =  60, jobs = 'WAR/PLD/DRK/BST/SAM/DRG' })  -- WS score 35 [RARE,EX]
table.insert(g.ear, { id =  26116, name = 'Schere Earring'                    , cost =  60, jobs = 'WAR/MNK/DRK/SAM/PUP' })  -- DPS score 48 [RARE,EX]
table.insert(g.ear, { id =  28483, name = 'Cryptic Earring'                   , cost =  60, jobs = 'All' })  -- TANK score 36 [RARE,EX]
table.insert(g.ear, { id =  25438, name = 'Wicce Earring'                     , cost =  60, jobs = 'BLM' })  -- CASTER score 49 [EX]

-- ring
table.insert(g.ring, { id =  10766, name = 'Lunette Ring'                      , cost =  60, jobs = 'All' })  -- DPS score 66 [RARE]
table.insert(g.ring, { id =  10769, name = 'Gelatinous Ring +1'                , cost =  60, jobs = 'All' })  -- TANK score 64 [RARE,EX]
table.insert(g.ring, { id =  28472, name = 'Freke Ring'                        , cost =  60, jobs = 'WHM/BLM/RDM/SMN/SCH/GEO' })  -- CASTER score 49 [RARE,EX]
table.insert(g.ring, { id =  26184, name = 'Stikini Ring +1'                   , cost =  60, jobs = 'All' })  -- HEAL score 63
table.insert(g.ring, { id =  10783, name = 'Veneficium Ring'                   , cost =  60, jobs = 'All' })  -- DPS score 66 [RARE]
table.insert(g.ring, { id =  13566, name = 'Defending Ring'                    , cost =  60, jobs = 'All' })  -- TANK score 60 [RARE,EX]
table.insert(g.ring, { id =  26192, name = 'Adoulin Ring +1'                   , cost =  60, jobs = 'All' })  -- CASTER score 43 [RARE,EX]
table.insert(g.ring, { id =  26193, name = 'Woltaris Ring +1'                  , cost =  60, jobs = 'All' })  -- HEAL score 60 [RARE,EX]

-- back
table.insert(g.back, { id =  28617, name = 'Maulers Mantle'                    , cost =  60, jobs = 'WAR' })  -- DPS score 60 [EX]
table.insert(g.back, { id =  28591, name = 'Aenotherus Mantle +1'              , cost =  60, jobs = 'WHM/BLM/RDM/PLD/DRK/SMN/BLU/SCH/GEO/RUN' })  -- TANK score 74
table.insert(g.back, { id =  28636, name = 'Bookworms Cape'                    , cost =  60, jobs = 'SCH' })  -- CASTER score 74 [EX]
table.insert(g.back, { id =  26268, name = 'Moonbeam Cape'                     , cost =  60, jobs = 'All' })  -- TANK score 68
table.insert(g.back, { id =  28624, name = 'Niht Mantle'                       , cost =  60, jobs = 'DRK' })  -- WS score 62 [EX]
table.insert(g.back, { id =  28628, name = 'Takaha Mantle'                     , cost =  60, jobs = 'SAM' })  -- DPS score 58 [EX]
table.insert(g.back, { id =  10971, name = 'Strendu Mantle'                    , cost =  60, jobs = 'WAR/PLD/DRK/BST/DRG' })  -- TANK score 73 [RARE,EX]
table.insert(g.back, { id =  28620, name = 'Bane Cape'                         , cost =  60, jobs = 'BLM' })  -- CASTER score 64 [EX]


-----------------------------------
-- INFAMY TIER  (top-5-per-slot BiS + Sortie JSE +2 earrings)
--   Not sold by the Accessory NPC. Promoted to the Dungeon Infamy
--   Vendor by tools/build_infamy_top_picks.py.
-----------------------------------
catalog.infamy = emptySlots()
local inf = catalog.infamy

-- neck (top 5 by score -> Infamy Vendor)
table.insert(inf.neck, { id =  26023, name = 'Sanctity Necklace'                 , cost = 300, jobs = 'All' })  -- CASTER score 252 [RARE,EX]
table.insert(inf.neck, { id =  26004, name = 'Lissome Necklace'                  , cost = 300, jobs = 'All' })  -- DPS score 140 [RARE,EX]
table.insert(inf.neck, { id =  11607, name = 'Artemiss Medal'                    , cost = 300, jobs = 'All' })  -- CASTER score 95 [RARE]
table.insert(inf.neck, { id =  25461, name = 'Abyssal Bead Necklace +2'          , cost = 300, jobs = 'DRK' })  -- WS score 90
table.insert(inf.neck, { id =  25497, name = 'Dragoons Collar +2'                , cost = 300, jobs = 'DRG' })  -- WS score 83

-- waist (top 5 by score -> Infamy Vendor)
table.insert(inf.waist, { id =  26357, name = 'Skrymir Cord +1'                   , cost = 300, jobs = 'All' })  -- CASTER score 175
table.insert(inf.waist, { id =  26341, name = 'Moonbow Belt +1'                   , cost = 300, jobs = 'MNK/PUP' })  -- DPS score 162
table.insert(inf.waist, { id =  26361, name = 'Gerdr Belt +1'                     , cost = 300, jobs = 'WAR/MNK/RDM/THF/PLD/DRK/BST/BRD/SAM/NIN/DRG/BLU/COR/DNC/RUN' })  -- DPS score 136
table.insert(inf.waist, { id =  26334, name = 'Ioskeha Belt +1'                   , cost = 300, jobs = 'WAR/DRK/SAM/DRG/RUN' })  -- DPS score 94
table.insert(inf.waist, { id =  26359, name = 'Orpheuss Sash'                     , cost = 300, jobs = 'All' })  -- DPS score 92 [RARE]

-- ear (top 5 by score -> Infamy Vendor)
table.insert(inf.ear, { id =  26088, name = 'Malignance Earring'                , cost = 300, jobs = 'WHM/BLM/RDM/DRK/SMN/SCH/GEO' })  -- CASTER score 76 [RARE,EX]
table.insert(inf.ear, { id =  26084, name = 'Sherida Earring'                   , cost = 300, jobs = 'MNK/RDM/THF/BST/RNG/DRG/DNC/RUN' })  -- DPS score 60 [RARE,EX]
table.insert(inf.ear, { id =  25439, name = 'Wicce Earring +1'                  , cost = 300, jobs = 'BLM' })  -- CASTER score 56 [EX]
table.insert(inf.ear, { id =  25535, name = 'Arbatel Earring +1'                , cost = 300, jobs = 'SCH' })  -- CASTER score 56 [EX]
table.insert(inf.ear, { id =  26108, name = 'Odr Earring'                       , cost = 300, jobs = 'MNK/THF/RNG/NIN/BLU/COR/DNC/RUN' })  -- DPS score 55 [RARE,EX]

-- ring (top 5 by score -> Infamy Vendor)
table.insert(inf.ring, { id =  26190, name = 'Moonlight Ring'                    , cost = 300, jobs = 'WAR/THF/PLD/DRK/BST/BRD/DRG/DNC/RUN' })  -- TANK score 85
table.insert(inf.ring, { id =  26191, name = 'Regal Ring'                        , cost = 300, jobs = 'WAR/MNK/THF/PLD/DRK/BST/RNG/SAM/NIN/DRG/COR/PUP/DNC/RUN' })  -- WS score 85 [RARE,EX]
table.insert(inf.ring, { id =  28471, name = 'Gere Ring'                         , cost = 300, jobs = 'MNK/THF/BST/NIN/PUP/DNC' })  -- DPS score 76 [RARE,EX]
table.insert(inf.ring, { id =  26186, name = 'Ilabrat Ring'                      , cost = 300, jobs = 'MNK/WHM/RDM/THF/BST/BRD/RNG/SAM/NIN/BLU/COR/DNC/RUN' })  -- WS score 72 [RARE,EX]
table.insert(inf.ring, { id =  26227, name = 'Cornelias Ring'                    , cost = 300, jobs = 'All' })  -- WS score 70 [RARE,EX]

-- back (top 5 by score -> Infamy Vendor)
table.insert(inf.back, { id =  27620, name = 'Aurists Cape +1'                   , cost = 300, jobs = 'WHM/BLM/RDM/BRD/SMN/BLU/PUP/SCH/GEO' })  -- CASTER score 177 [RARE,EX]
table.insert(inf.back, { id =  26269, name = 'Moonlight Cape'                    , cost = 300, jobs = 'All' })  -- TANK score 171
table.insert(inf.back, { id =  27615, name = 'Reiki Cloak'                       , cost = 300, jobs = 'WAR/MNK/RDM/THF/PLD/DRK/BST/BRD/RNG/SAM/NIN/DRG/BLU/COR/DNC/RUN' })  -- TANK score 153 [RARE,EX]
table.insert(inf.back, { id =  13655, name = 'Sand Mantle'                       , cost = 300, jobs = 'WAR/MNK/RDM/THF/PLD/DRK/BST/BRD/RNG/SAM/NIN/DRG/BLU/COR/DNC/RUN' })  -- TANK score 108 [RARE]
table.insert(inf.back, { id =  28607, name = 'Aput Mantle +1'                    , cost = 300, jobs = 'WAR/MNK/RDM/THF/PLD/DRK/BST/BRD/RNG/SAM/NIN/DRG/BLU/COR/DNC/RUN' })  -- CASTER score 80

-- ear (Sortie +2, one per job)
table.insert(inf.ear, { id =  25422, name = 'Boii Earring +2'                   , cost = 300, jobs = 'WAR' })  -- DPS score 51
table.insert(inf.ear, { id =  25428, name = 'Bhikku Earring +2'                 , cost = 300, jobs = 'MNK' })  -- DPS score 0
table.insert(inf.ear, { id =  25434, name = 'Ebers Earring +2'                  , cost = 300, jobs = 'WHM' })  -- HEAL score 6
table.insert(inf.ear, { id =  25440, name = 'Wicce Earring +2'                  , cost = 300, jobs = 'BLM' })  -- CASTER score 56
table.insert(inf.ear, { id =  25446, name = 'Lethargy Earring +2'               , cost = 300, jobs = 'RDM' })  -- CASTER score 16
table.insert(inf.ear, { id =  25452, name = 'Skulkers Earring +2'               , cost = 300, jobs = 'THF' })  -- DPS score 0
table.insert(inf.ear, { id =  25458, name = 'Chevaliers Earring +2'             , cost = 300, jobs = 'PLD' })  -- TANK score 0
table.insert(inf.ear, { id =  25464, name = 'Heathens Earring +2'               , cost = 300, jobs = 'DRK' })  -- DPS score 0
table.insert(inf.ear, { id =  25470, name = 'Nukumi Earring +2'                 , cost = 300, jobs = 'BST' })  -- DPS score 0
table.insert(inf.ear, { id =  25476, name = 'Fili Earring +2'                   , cost = 300, jobs = 'BRD' })  -- DPS score 0
table.insert(inf.ear, { id =  25482, name = 'Amini Earring +2'                  , cost = 300, jobs = 'RNG' })  -- DPS score 0
table.insert(inf.ear, { id =  25488, name = 'Kasuga Earring +2'                 , cost = 300, jobs = 'SAM' })  -- DPS score 16
table.insert(inf.ear, { id =  25494, name = 'Hattori Earring +2'                , cost = 300, jobs = 'NIN' })  -- DPS score 0
table.insert(inf.ear, { id =  25500, name = 'Peltasts Earring +2'               , cost = 300, jobs = 'DRG' })  -- DPS score 0
table.insert(inf.ear, { id =  25506, name = 'Beckoners Earring +2'              , cost = 300, jobs = 'SMN' })  -- CASTER score 0
table.insert(inf.ear, { id =  25512, name = 'Hashishin Earring +2'              , cost = 300, jobs = 'BLU' })  -- DPS score 0
table.insert(inf.ear, { id =  25518, name = 'Chasseurs Earring +2'              , cost = 300, jobs = 'COR' })  -- DPS score 0
table.insert(inf.ear, { id =  25524, name = 'Karagoz Earring +2'                , cost = 300, jobs = 'PUP' })  -- DPS score 3
table.insert(inf.ear, { id =  25530, name = 'Maculele Earring +2'               , cost = 300, jobs = 'DNC' })  -- DPS score 0
table.insert(inf.ear, { id =  25536, name = 'Arbatel Earring +2'                , cost = 300, jobs = 'SCH' })  -- CASTER score 56
table.insert(inf.ear, { id =  25542, name = 'Azimuth Earring +2'                , cost = 300, jobs = 'GEO' })  -- CASTER score 24
table.insert(inf.ear, { id =  25548, name = 'Erilaz Earring +2'                 , cost = 300, jobs = 'RUN' })  -- TANK score 2


return catalog
