-----------------------------------
-- Intense VD Ambuscade cosmetic reward pool.
--
-- A successful reward roll selects exactly one of these 100 entries with
-- uniform probability. Item restrictions are enforced by
-- modules/custom/sql/ambuscade_cosmetic_items.sql.
-----------------------------------
local catalog =
{
    dropChance = 33,
    items =
    {
        -- Yukata
        { id = 11316, name = 'Otokogusa Yukata' },
        { id = 11317, name = 'Onnagusa Yukata' },
        { id = 11318, name = 'Otokoeshi Yukata' },
        { id = 11319, name = 'Ominaeshi Yukata' },
        { id = 11861, name = 'Hikogami Yukata' },
        { id = 11862, name = 'Himegami Yukata' },
        { id = 13819, name = 'Onoko Yukata' },
        { id = 13820, name = 'Omina Yukata' },
        { id = 13821, name = "Lord's Yukata" },
        { id = 13822, name = "Lady's Yukata" },
        { id = 14532, name = 'Otoko Yukata' },
        { id = 14533, name = 'Onago Yukata' },
        { id = 14534, name = 'Otokogimi Yukata' },
        { id = 14535, name = 'Onnagimi Yukata' },

        -- Seasonal and formal
        { id = 13916, name = 'Pumpkin Head' },
        { id = 15176, name = 'Pumpkin Head II' },
        { id = 16075, name = 'Witch Hat' },
        { id = 11490, name = 'Snow Bunny Hat' },
        { id = 11491, name = 'Snow Bunny Hat +1' },
        { id = 10251, name = 'Decennial Coat' },
        { id = 10252, name = 'Decennial Dress' },
        { id = 10430, name = 'Decennial Crown' },
        { id = 10431, name = 'Decennial Tiara' },
        { id = 10593, name = 'Decennial Tights' },
        { id = 10594, name = 'Decennial Hose' },
        { id = 10796, name = 'Decennial Ring' },
        { id = 11355, name = 'Dinner Jacket' },
        { id = 16378, name = 'Dinner Hose' },
        { id = 14386, name = 'Wedding Dress' },
        { id = 14251, name = 'Wedding Hose' },
        { id = 14126, name = 'Wedding Boots' },
        { id = 13933, name = 'Bridal Corsage' },

        -- Event suits, masks, and shirts
        { id = 10250, name = 'Moogle Suit' },
        { id = 10429, name = 'Moogle Masque' },
        { id = 10809, name = 'Moogle Guard' },
        { id = 16118, name = 'Moogle Cap' },
        { id = 26546, name = 'Moogle Shirt' },
        { id = 23791, name = 'Adenium Suit' },
        { id = 25711, name = 'Botulus Suit' },
        { id = 25715, name = 'Korrigan Suit' },
        { id = 25726, name = 'Kupo Suit' },
        { id = 25756, name = 'Wyrmking Suit' },
        { id = 26954, name = 'Behemoth Suit' },
        { id = 27854, name = 'Mandragora Suit' },
        { id = 27866, name = 'Goblin Suit' },
        { id = 27911, name = 'Chocobo Suit' },
        { id = 10384, name = 'Cumulus Masque' },
        { id = 23790, name = 'Adenium Masque' },
        { id = 25639, name = 'Korrigan Masque' },
        { id = 26703, name = 'Lycopodium Masque' },
        { id = 11500, name = 'Chocobo Beret' },
        { id = 25585, name = 'Black Chocobo Cap' },
        { id = 23731, name = 'Ryl. Chocobo Beret' },
        { id = 15178, name = 'Dream Hat' },
        { id = 26719, name = 'Sheep Cap' },
        { id = 25722, name = 'Jubilee Shirt' },
        { id = 25758, name = 'Rhapsody Shirt' },
        { id = 26517, name = 'Shadow Lord Shirt' },

        -- Swimwear
        { id = 10256, name = 'Marine Gilet' },
        { id = 10257, name = 'Marine Top' },
        { id = 10258, name = 'Woodsy Gilet' },
        { id = 10259, name = 'Woodsy Top' },
        { id = 10260, name = 'Creek Maillot' },
        { id = 10261, name = 'Creek Top' },
        { id = 10262, name = 'River Top' },
        { id = 10263, name = 'Dune Gilet' },
        { id = 10264, name = 'Marine Gilet +1' },
        { id = 10265, name = 'Marine Top +1' },
        { id = 10266, name = 'Woodsy Gilet +1' },
        { id = 10267, name = 'Woodsy Top +1' },
        { id = 10268, name = 'Creek Maillot +1' },
        { id = 10269, name = 'Creek Top +1' },
        { id = 10270, name = 'River Top +1' },
        { id = 10271, name = 'Dune Gilet +1' },
        { id = 10330, name = 'Marine Boxers' },
        { id = 10331, name = 'Marine Shorts' },
        { id = 10332, name = 'Woodsy Boxers' },
        { id = 10333, name = 'Woodsy Shorts' },
        { id = 10334, name = 'Creek Boxers' },
        { id = 10335, name = 'Creek Shorts' },
        { id = 10336, name = 'River Shorts' },
        { id = 10337, name = 'Dune Boxers' },
        { id = 10338, name = 'Marine Boxers +1' },
        { id = 10339, name = 'Marine Shorts +1' },
        { id = 10340, name = 'Woodsy Boxers +1' },
        { id = 10341, name = 'Woodsy Shorts +1' },
        { id = 10342, name = 'Creek Boxers +1' },
        { id = 10343, name = 'Creek Shorts +1' },
        { id = 10344, name = 'River Shorts +1' },
        { id = 10345, name = 'Dune Boxers +1' },

        -- Additional appearance-only variants
        { id = 10253, name = 'Decennial Coat +1' },
        { id = 10254, name = 'Decennial Dress +1' },
        { id = 10432, name = 'Decennial Crown +1' },
        { id = 10433, name = 'Decennial Tiara +1' },
        { id = 10595, name = 'Decennial Tights +1' },
        { id = 10596, name = 'Decennial Hose +1' },
        { id = 10382, name = 'Dream Mittens' },
        { id = 10383, name = 'Dream Mittens +1' },
        { id = 10385, name = 'Cumulus Masque +1' },
        { id = 10293, name = 'Chocobo Shirt' },
    },
}

return catalog
