-----------------------------------
-- augment_dungeon_drops_data.lua
-- AUTO-GENERATED by tools/gen_augment_dungeon_drops.py -- DO NOT HAND-EDIT.
-- Re-run the script after augment_catalog.lua changes and commit both.
--
-- Per Augmentation Dungeon (dungeon_catalog.lua keys):
--   family : player-facing name of the stat family this dungeon owns
--   trash  : [slot 1-12] = fixed catalyst for that trash mob (roster order)
--   boss   : pool the boss draws from (family tier-3/4 remainder)
-- Consumed by augment_dungeon_drops.lua (runtime) and
-- tools/docgen/generators/augment_dungeon_drops.py (docs).
-----------------------------------
return {
    ordellesCaves =
    {
        family = 'Melee Offense',
        trash =
        {
            [1] = { id = 1620, tier = 1, cat = 1, label = 'STR', item = 'taurus_horn' },
            [2] = { id = 861, tier = 1, cat = 2, label = 'Attack', item = 'tiger_hide' },
            [3] = { id = 874, tier = 1, cat = 2, label = 'Attack Rng.Atk', item = 'amaltheia_hide' },
            [4] = { id = 883, tier = 1, cat = 2, label = 'Rng.Attack', item = 'behemoth_horn' },
            [5] = { id = 1591, tier = 1, cat = 2, label = 'Reverse Flourish', item = 'h.q._coeurl_hide' },
            [6] = { id = 926, tier = 1, cat = 3, label = 'Zanshin', item = 'lizard_tail' },
            [7] = { id = 947, tier = 1, cat = 3, label = 'Daken', item = 'firesand' },
            [8] = { id = 2150, tier = 1, cat = 3, label = 'DEX', item = 'colibri_feather' },
            [9] = { id = 895, tier = 2, cat = 1, label = 'Counter', item = 'ram_horn' },
            [10] = { id = 897, tier = 2, cat = 1, label = 'Martial Arts', item = 'scorpion_claw' },
            [11] = { id = 903, tier = 2, cat = 1, label = 'Kick Attacks Rate or Damage', item = 'dragon_talon' },
            [12] = { id = 2147, tier = 2, cat = 1, label = 'Counter', item = 'marid_tusk' },
        },
        boss =
        {
            { id = 880, tier = 3, cat = 2, label = 'Dbl.Atk. Crit.hit rate', item = 'bone_chip' },
            { id = 891, tier = 3, cat = 2, label = 'Triple Atk', item = 'bat_fang' },
            { id = 1621, tier = 3, cat = 3, label = 'Store TP', item = 'taurus_wing' },
            { id = 1690, tier = 3, cat = 3, label = 'Subtle Blow', item = 'hippogryph_tf.' },
            { id = 2148, tier = 3, cat = 3, label = 'Crit.hit rate', item = 'puk_wing' },
            { id = 1271, tier = 4, cat = 2, label = 'TP Bonus', item = 'pigeons_blood' },
            { id = 1293, tier = 4, cat = 2, label = 'Quadruple Attack', item = 'narasimha_hide' },
            { id = 2711, tier = 4, cat = 2, label = 'Meditate Effect Duration' },
            { id = 840, tier = 4, cat = 3, label = 'Store TP Subtle Blow', item = 'chocobo_fthr.' },
            { id = 2149, tier = 4, cat = 3, label = 'Crit. hit damage', item = 'apkallu_feather' },
        },
    },
    gusgenMines =
    {
        family = 'Survival & Defense',
        trash =
        {
            [1] = { id = 1617, tier = 0, cat = 8, label = 'Evasion', item = 'flytrap_leaf' },
            [2] = { id = 773, tier = 1, cat = 5, label = 'VIT', item = 'translucent_rock' },
            [3] = { id = 774, tier = 1, cat = 6, label = 'DEF', item = 'purple_rock' },
            [4] = { id = 881, tier = 1, cat = 6, label = 'DEF', item = 'crab_shell' },
            [5] = { id = 3504, tier = 1, cat = 6, label = 'Enemy crit. hit rate', item = 'peapuk_wing' },
            [6] = { id = 1713, tier = 1, cat = 8, label = 'Mag. Evasion', item = 'cashmere_thrd.' },
            [7] = { id = 860, tier = 1, cat = 16, label = 'HP', item = 'behemoth_hide' },
            [8] = { id = 769, tier = 2, cat = 6, label = 'Mag.Def.Bns', item = 'red_rock' },
            [9] = { id = 829, tier = 2, cat = 8, label = 'Snapshot', item = 'silk_cloth' },
            [10] = { id = 2831, tier = 2, cat = 22, label = 'Occ. inc. resist to stat ailments' },
            [11] = { id = 776, tier = 3, cat = 6, label = 'Parrying rate', item = 'white_rock' },
            [12] = { id = 858, tier = 3, cat = 6, label = 'Phys. dmg. taken', item = 'wolf_hide' },
        },
        boss =
        {
            { id = 936, tier = 3, cat = 6, label = 'Magic dmg. taken', item = 'rock_salt' },
            { id = 2151, tier = 3, cat = 6, label = 'Physical Damage Taken', item = 'marid_hide' },
            { id = 2158, tier = 3, cat = 6, label = 'Magic Damage Taken', item = 'hydra_fang' },
            { id = 867, tier = 3, cat = 16, label = 'HP MP', item = 'dragon_scales' },
            { id = 770, tier = 4, cat = 6, label = 'Shield Mastery', item = 'blue_rock' },
            { id = 771, tier = 4, cat = 6, label = 'Chance of successful block', item = 'yellow_rock' },
            { id = 772, tier = 4, cat = 6, label = 'Phalanx Received', item = 'green_rock' },
            { id = 1123, tier = 4, cat = 6, label = 'Damage Taken', item = 'manticore_fang' },
            { id = 1193, tier = 4, cat = 6, label = 'Breath dmg. taken', item = 'h.q._crab_shell' },
        },
    },
    kuftalTunnel =
    {
        family = 'Weapon Mastery & Speed',
        trash =
        {
            [1] = { id = 908, tier = 0, cat = 23, label = 'Treasure Hunter', item = 'adamantoise_shell' },
            [2] = { id = 1269, tier = 0, cat = 23, label = 'Ninja tool expertise' },
            [3] = { id = 2523, tier = 0, cat = 23, label = 'Exp. Point +33%', item = 'peiste_skin' },
            [4] = { id = 2641, tier = 0, cat = 23, label = 'Indi Effect Duration' },
            [5] = { id = 2729, tier = 0, cat = 23, label = 'Repair potency' },
            [6] = { id = 820, tier = 1, cat = 9, label = 'Haste', item = 'wool_thread' },
            [7] = { id = 824, tier = 1, cat = 23, label = 'Dark magic skill', item = 'grass_cloth' },
            [8] = { id = 831, tier = 1, cat = 23, label = 'Wind instrument skill', item = 'shining_cloth' },
            [9] = { id = 864, tier = 1, cat = 23, label = 'Dagger skill', item = 'fish_scales' },
            [10] = { id = 894, tier = 1, cat = 23, label = 'Sword skill', item = 'beetle_jaw' },
            [11] = { id = 916, tier = 1, cat = 23, label = 'Great Sword skill', item = 'cactuar_needle' },
            [12] = { id = 920, tier = 1, cat = 23, label = 'Axe skill', item = 'malboro_vine' },
        },
        boss =
        {
            { id = 821, tier = 4, cat = 9, label = 'Slow', item = 'rainbow_thread' },
            { id = 828, tier = 4, cat = 9, label = 'Resist Slow', item = 'velvet_cloth' },
            { id = 832, tier = 4, cat = 9, label = 'Phantom Roll ability delay', item = 'sheep_wool' },
            { id = 876, tier = 4, cat = 9, label = 'Blood Pact ability delay', item = 'manta_skin' },
            { id = 912, tier = 4, cat = 9, label = 'Call Beast ability delay', item = 'beehive_chip' },
            { id = 1623, tier = 4, cat = 9, label = 'Quick Draw ability delay', item = 'eft_skin' },
            { id = 865, tier = 4, cat = 24, label = 'Sklchn.dmg', item = 'nidhogg_scales' },
            { id = 889, tier = 4, cat = 24, label = 'Dmg (melee,not ranged)', item = 'beetle_shell' },
            { id = 1875, tier = 5, cat = 23, label = 'Phantom Roll effect', item = 'anct._beastcoin' },
            { id = 1473, tier = 5, cat = 24, label = 'Weapon skill damage', item = 'h.q._scp._shell' },
        },
    },
    gustavTunnel =
    {
        family = 'Ranged & Pet',
        trash =
        {
            [1] = { id = 852, tier = 0, cat = 20, label = 'Blood Boon', item = 'lizard_skin' },
            [2] = { id = 856, tier = 0, cat = 20, label = 'Pet TP Bonus', item = 'rabbit_hide' },
            [3] = { id = 1156, tier = 0, cat = 20, label = 'Avatar perpetuation cost', item = 'crawler_calculus' },
            [4] = { id = 1272, tier = 0, cat = 20, label = 'Elemental Siphon', item = 'arioch_fang' },
            [5] = { id = 1408, tier = 0, cat = 20, label = 'Pet Enmity', item = 'illuminink' },
            [6] = { id = 1453, tier = 0, cat = 20, label = 'Pet Enmity', item = 'm._silverpiece' },
            [7] = { id = 846, tier = 1, cat = 4, label = 'Accuracy', item = 'insect_wing' },
            [8] = { id = 847, tier = 1, cat = 4, label = 'Rng.Accuracy', item = 'bird_feather' },
            [9] = { id = 768, tier = 1, cat = 20, label = 'Pet Mag.Def.Bns', item = 'flint_stone' },
            [10] = { id = 775, tier = 1, cat = 20, label = 'Pet Magic Dmg. Taken', item = 'black_rock' },
            [11] = { id = 786, tier = 1, cat = 20, label = 'Pet Damage taken', item = 'ruby' },
            [12] = { id = 803, tier = 1, cat = 20, label = 'Pet VIT', item = 'sunstone' },
        },
        boss =
        {
            { id = 810, tier = 3, cat = 20, label = 'Sic and Ready ability delay', item = 'fluorite' },
            { id = 1199, tier = 4, cat = 4, label = 'Barrage', item = 'northern_fur' },
            { id = 1619, tier = 4, cat = 4, label = 'Rapid Shot', item = 'hippogryph_fthr.' },
            { id = 1268, tier = 4, cat = 20, label = 'Fire Affinity Avatar perp. cost', item = 'doll_gizmo' },
            { id = 1270, tier = 4, cat = 20, label = 'Ice Affinity Avatar perp. cost', item = 'arachne_web' },
            { id = 1295, tier = 4, cat = 20, label = 'Wind Affinity Avatar perp. cost', item = 'twincoon' },
            { id = 1311, tier = 4, cat = 20, label = 'Earth Affinity Avatar perp. cost', item = 'oxblood' },
            { id = 1313, tier = 4, cat = 20, label = 'Water Affinity Avatar perp. cost', item = 'sirens_hair' },
            { id = 1414, tier = 4, cat = 20, label = 'Light Affinity Avatar perp. cost', item = 'wisteria_lumber' },
            { id = 1443, tier = 4, cat = 20, label = 'Dark Affinity Avatar perp. cost', item = 'dried_mugwort' },
            { id = 1830, tier = 4, cat = 20, label = 'Thunder Affinity Avatar perp. cost', item = 'lugworm_sand' },
            { id = 2518, tier = 4, cat = 20, label = 'Beast Affinity' },
        },
    },
    ifritsCauldron =
    {
        family = 'Nuking & Magic Offense',
        trash =
        {
            [1] = { id = 849, tier = 0, cat = 11, label = 'Elemental Magic Recast Delay', item = 'undead_skin' },
            [2] = { id = 859, tier = 0, cat = 11, label = 'Enfeebling Magic Recast Delay', item = 'ram_skin' },
            [3] = { id = 868, tier = 0, cat = 11, label = 'Enhancing Magic Recast Delay', item = 'pugil_scales' },
            [4] = { id = 921, tier = 1, cat = 10, label = 'INT', item = 'ahriman_tears' },
            [5] = { id = 2510, tier = 1, cat = 10, label = 'Enhancing Magic Effect Duration' },
            [6] = { id = 854, tier = 1, cat = 11, label = 'Spell interruption rate down 1%', item = 'cockatrice_skin' },
            [7] = { id = 886, tier = 1, cat = 11, label = 'Mag. Acc', item = 'demon_skull' },
            [8] = { id = 2427, tier = 1, cat = 11, label = 'Fast Cast', item = 'wivre_maul' },
            [9] = { id = 2834, tier = 1, cat = 11, label = 'Spell Interruption Rate Down 2%' },
            [10] = { id = 2943, tier = 1, cat = 11, label = 'Drain/Aspir Potency', item = 'balaur_skull' },
            [11] = { id = 909, tier = 2, cat = 11, label = 'Mag. Acc./Mag. Dmg', item = 'guivres_skull' },
            [12] = { id = 2338, tier = 2, cat = 11, label = 'Enspell Dmg', item = 'wamoura_scale' },
        },
        boss =
        {
            { id = 842, tier = 3, cat = 11, label = 'Magic crit. hit rate', item = 'giant_bird_fthr.' },
            { id = 2426, tier = 3, cat = 11, label = 'Mag.Atk.Bns', item = 'wivre_horn' },
            { id = 2498, tier = 3, cat = 11, label = 'Magic Damage' },
            { id = 2776, tier = 3, cat = 11, label = 'Magic burst dmg', item = 'pumice_stone' },
            { id = 2777, tier = 3, cat = 11, label = 'Mag. crit. hit dmg', item = 'magicked_blood' },
            { id = 2640, tier = 4, cat = 10, label = 'Helix Effect Duration' },
            { id = 905, tier = 4, cat = 11, label = 'Mag. Acc. Mag.Atk.Bns', item = 'wyvern_skull' },
            { id = 2335, tier = 4, cat = 11, label = 'Helix Damage' },
            { id = 2428, tier = 4, cat = 11, label = 'Occult Acumen', item = 'wivre_hide' },
            { id = 2507, tier = 4, cat = 11, label = 'Occ. quickens spellcasting' },
            { id = 3941, tier = 4, cat = 11, label = 'Fire Affinity Magic Accuracy Recast time', item = 'chapuli_wing' },
            { id = 2506, tier = 5, cat = 11, label = 'Fire Affinity Magic Accuracy', item = 'ladybug_wing' },
            { id = 2509, tier = 5, cat = 11, label = 'Ice Affinity Magic Accuracy', item = 'slug_eye' },
            { id = 2522, tier = 5, cat = 11, label = 'Wind Affinity Magic Accuracy', item = 'gnat_wing' },
            { id = 2531, tier = 5, cat = 11, label = 'Spikes Dmg' },
            { id = 2749, tier = 5, cat = 11, label = 'Earth Affinity Magic Accuracy', item = 'gargouille_eye' },
            { id = 2875, tier = 5, cat = 11, label = 'Immunobreak Chance+' },
            { id = 2890, tier = 5, cat = 11, label = 'Lightning Affinity Magic Accuracy', item = 'clionid_wing' },
            { id = 2938, tier = 5, cat = 11, label = 'Water Affinity Magic Accuracy', item = 'bakkas_wing' },
            { id = 3502, tier = 5, cat = 11, label = 'Light Affinity Magic Accuracy', item = 'umbral_marrow' },
            { id = 3930, tier = 5, cat = 11, label = 'Dark Affinity Magic Accuracy', item = 'twitherym_wing' },
        },
    },
    feiYin =
    {
        family = 'Healing & MP Support',
        trash =
        {
            [1] = { id = 1122, tier = 0, cat = 17, label = 'HP recovered while healing', item = 'wyvern_skin' },
            [2] = { id = 791, tier = 0, cat = 18, label = 'MP recovered while healing', item = 'aquamarine' },
            [3] = { id = 888, tier = 1, cat = 12, label = 'MND', item = 'seashell' },
            [4] = { id = 792, tier = 1, cat = 13, label = 'Healing magic skill', item = 'pearl' },
            [5] = { id = 833, tier = 1, cat = 13, label = 'Cure potency', item = 'moko_grass' },
            [6] = { id = 838, tier = 1, cat = 13, label = 'Healing Magic Recast Delay', item = 'spider_web' },
            [7] = { id = 887, tier = 1, cat = 13, label = 'Potency of Cure received', item = 'coral_fragment' },
            [8] = { id = 1741, tier = 1, cat = 13, label = 'Waltz potency', item = 'h.q._eft_skin' },
            [9] = { id = 850, tier = 1, cat = 17, label = 'Regen Potency', item = 'sheep_leather' },
            [10] = { id = 841, tier = 1, cat = 18, label = 'MP', item = 'yagudo_feather' },
            [11] = { id = 919, tier = 1, cat = 19, label = 'Refresh', item = 'boyahda_moss' },
            [12] = { id = 1119, tier = 1, cat = 19, label = 'Conserve MP' },
        },
        boss =
        {
            { id = 793, tier = 4, cat = 13, label = 'Cure spellcasting time', item = 'black_pearl' },
            { id = 801, tier = 4, cat = 13, label = 'Waltz ability delay', item = 'chrysoberyl' },
            { id = 836, tier = 4, cat = 13, label = 'Waltz TP cost', item = 'damascene_cloth' },
            { id = 848, tier = 4, cat = 17, label = 'Regen', item = 'dhalmel_leather' },
        },
    },
    ranguemontPass =
    {
        family = 'Songs, Utility & Affinity',
        trash =
        {
            [1] = { id = 1132, tier = 0, cat = 21, label = 'All elemental resists', item = 'raxa' },
            [2] = { id = 1850, tier = 0, cat = 21, label = 'Enhances', item = 'first_virtue' },
            [3] = { id = 834, tier = 1, cat = 7, label = 'Recycle', item = 'saruta_cotton' },
            [4] = { id = 878, tier = 1, cat = 7, label = 'AGI', item = 'karakul_skin' },
            [5] = { id = 817, tier = 1, cat = 14, label = 'Song recast delay', item = 'grass_thread' },
            [6] = { id = 902, tier = 1, cat = 14, label = 'Charm', item = 'demon_horn' },
            [7] = { id = 1858, tier = 1, cat = 14, label = 'Gilfinder', item = 'moblumin_ingot' },
            [8] = { id = 2372, tier = 1, cat = 14, label = 'Resist Charm', item = 'khimaira_mane' },
            [9] = { id = 2827, tier = 1, cat = 14, label = 'Song spellcasting time', item = 'rgd._gld._thread' },
            [10] = { id = 2841, tier = 1, cat = 14, label = 'CHR', item = 'qdv._silv._ingot' },
            [11] = { id = 787, tier = 1, cat = 15, label = 'Enmity', item = 'diamond' },
            [12] = { id = 901, tier = 1, cat = 15, label = 'Enmity', item = 'venomous_claw' },
        },
        boss =
        {
            { id = 1165, tier = 4, cat = 21, label = 'Fire Affinity', item = 'doll_shard' },
            { id = 1186, tier = 4, cat = 21, label = 'Ice Affinity', item = 'bomb_queen_core' },
            { id = 1187, tier = 4, cat = 21, label = 'Wind Affinity', item = 'bomb_queen_ash' },
            { id = 1200, tier = 4, cat = 21, label = 'Earth Affinity', item = 'eastern_pottery' },
            { id = 1201, tier = 4, cat = 21, label = 'Lightning Affinity', item = 'southern_mummy' },
            { id = 1236, tier = 4, cat = 21, label = 'Water Affinity', item = 'cactus_stems' },
            { id = 1237, tier = 4, cat = 21, label = 'Light Affinity', item = 'tree_cuttings' },
            { id = 1263, tier = 4, cat = 21, label = 'Dark Affinity', item = 'leshonki_bulb' },
            { id = 1291, tier = 5, cat = 14, label = 'All songs', item = 'golden_hktk._eye' },
        },
    },
}
