-----------------------------------
-- augment_dungeon_drops_data.lua
-- AUTO-GENERATED by tools/gen_augment_dungeon_drops.py -- DO NOT HAND-EDIT.
-- Re-run the script after augment_catalog.lua changes and commit both.
--
-- Per Augmentation Dungeon (dungeon_catalog.lua keys):
--   family : player-facing name of the stat family this dungeon owns
--   trash  : [slot 1-12] = fixed catalyst for that trash mob (roster order)
--   boss   : pool the boss draws from (family tier-3/4 remainder)
-- Consumed by augment_dungeon_drops.lua (runtime) and
-- tools/docgen/generators/augment_dungeon_drops.py (docs).
-----------------------------------
return {
    ordellesCaves =
    {
        family = 'Melee Offense',
        trash =
        {
            [1] = { id = 846, tier = 0, cat = 2, label = 'Accuracy', item = 'insect_wing' },
            [2] = { id = 847, tier = 0, cat = 2, label = 'Rng.Accuracy', item = 'bird_feather' },
            [3] = { id = 855, tier = 0, cat = 2, label = 'TP Bonus', item = 'square_of_black_tiger_leather' },
            [4] = { id = 861, tier = 0, cat = 2, label = 'Attack', item = 'black_tiger_hide' },
            [5] = { id = 880, tier = 0, cat = 2, label = 'Dbl.Atk. Crit.hit rate', item = 'bone_chip' },
            [6] = { id = 882, tier = 0, cat = 2, label = 'Dbl.Atk', item = 'sheep_tooth' },
            [7] = { id = 884, tier = 0, cat = 2, label = 'Accuracy Attack', item = 'black_tiger_fang' },
            [8] = { id = 891, tier = 0, cat = 2, label = 'Triple Atk', item = 'bat_fang' },
            [9] = { id = 927, tier = 0, cat = 2, label = 'Accuracy Rng.Acc', item = 'coeurl_whisker' },
            [10] = { id = 935, tier = 0, cat = 2, label = 'Store TP Subtle Blow', item = 'ahriman_wing' },
            [11] = { id = 937, tier = 0, cat = 2, label = 'Rng.Attack', item = 'block_of_animal_glue' },
            [12] = { id = 1116, tier = 0, cat = 2, label = 'Rng.Acc. Rng.Atk', item = 'manticore_hide' },
        },
        boss =
        {
            { id = 1163, tier = 0, cat = 2, label = 'Sklchn.dmg', item = 'lock_of_manticore_hair' },
            { id = 1473, tier = 0, cat = 2, label = 'Weapon skill damage', item = 'high-quality_scorpion_shell' },
            { id = 1516, tier = 0, cat = 2, label = 'Save TP', item = 'griffon_hide' },
            { id = 1521, tier = 0, cat = 2, label = 'Weapon Skill Acc', item = 'vial_of_slime_juice' },
            { id = 1591, tier = 0, cat = 2, label = 'Quadruple Attack', item = 'high-quality_coeurl_hide' },
            { id = 1621, tier = 0, cat = 2, label = 'Store TP', item = 'taurus_wing' },
            { id = 1622, tier = 0, cat = 2, label = 'Attack Rng.Atk', item = 'bugard_tusk' },
            { id = 1690, tier = 0, cat = 2, label = 'Subtle Blow', item = 'hippogryph_tailfeather' },
            { id = 2148, tier = 0, cat = 2, label = 'Crit.hit rate', item = 'puk_wing' },
            { id = 2149, tier = 0, cat = 2, label = 'Crit. hit damage', item = 'apkallu_feather' },
            { id = 2157, tier = 0, cat = 2, label = 'Conserve TP', item = 'imp_horn' },
        },
    },
    ifritsCauldron =
    {
        family = 'Magic Offense',
        trash =
        {
            [1] = { id = 842, tier = 0, cat = 3, label = 'Magic crit. hit rate', item = 'giant_bird_feather' },
            [2] = { id = 886, tier = 0, cat = 3, label = 'Mag. Acc', item = 'demon_skull' },
            [3] = { id = 909, tier = 0, cat = 3, label = 'Mag. Acc./Mag. Dmg', item = 'guivres_skull' },
            [4] = { id = 943, tier = 0, cat = 3, label = 'Mag. crit. hit dmg', item = 'pinch_of_poison_dust' },
            [5] = { id = 954, tier = 0, cat = 3, label = 'Mag. Acc. Mag.Atk.Bns', item = 'magic_pot_shard' },
            [6] = { id = 955, tier = 0, cat = 3, label = 'Enhances', item = 'golem_shard' },
            [7] = { id = 1474, tier = 0, cat = 3, label = 'Magic Damage', item = 'infinity_core' },
            [8] = { id = 1606, tier = 0, cat = 3, label = 'Immunobreak Chance+', item = 'remnant_of_a_burning_memory' },
            [9] = { id = 2166, tier = 0, cat = 3, label = 'Spell Interruption Rate Down', item = 'lock_of_marid_hair' },
            [10] = { id = 2335, tier = 0, cat = 3, label = 'Helix Damage', item = 'soulflayer_tentacle' },
            [11] = { id = 2338, tier = 0, cat = 3, label = 'Enspell Dmg', item = 'wamoura_scale' },
            [12] = { id = 2426, tier = 0, cat = 3, label = 'Mag.Atk.Bns', item = 'wivre_horn' },
        },
        boss =
        {
            { id = 2427, tier = 0, cat = 3, label = 'Fast Cast', item = 'wivre_maul' },
            { id = 2428, tier = 0, cat = 3, label = 'Occult Acumen', item = 'wivre_hide' },
            { id = 2507, tier = 0, cat = 3, label = 'Occ. quickens spellcasting', item = 'lycopodium_flower' },
            { id = 2531, tier = 0, cat = 3, label = 'Spikes Dmg', item = 'shard_of_obsidian' },
            { id = 2889, tier = 0, cat = 3, label = 'Magic burst dmg', item = 'limule_pincer' },
        },
    },
    gusgenMines =
    {
        family = 'Survival & Defense',
        trash =
        {
            [1] = { id = 858, tier = 0, cat = 4, label = 'Phys. dmg. taken', item = 'wolf_hide' },
            [2] = { id = 881, tier = 0, cat = 4, label = 'Mag.Def.Bns', item = 'crab_shell' },
            [3] = { id = 889, tier = 0, cat = 4, label = 'Chance of successful block', item = 'beetle_shell' },
            [4] = { id = 928, tier = 0, cat = 4, label = 'DEF', item = 'pinch_of_bomb_ash' },
            [5] = { id = 936, tier = 0, cat = 4, label = 'Magic dmg. taken', item = 'chunk_of_rock_salt' },
            [6] = { id = 1123, tier = 0, cat = 4, label = 'Damage Taken', item = 'manticore_fang' },
            [7] = { id = 1193, tier = 0, cat = 4, label = 'Breath dmg. taken', item = 'high-quality_crab_shell' },
            [8] = { id = 1449, tier = 0, cat = 4, label = 'Phalanx Received', item = 'tukuku_whiteshell' },
            [9] = { id = 1470, tier = 0, cat = 4, label = 'Resist Charm', item = 'sparkling_stone' },
            [10] = { id = 1617, tier = 0, cat = 4, label = 'Evasion', item = 'flytrap_leaf' },
            [11] = { id = 1638, tier = 0, cat = 4, label = 'Occ. inc. resist to stat ailments', item = 'moblin_mask' },
            [12] = { id = 2151, tier = 0, cat = 4, label = 'Physical Damage Taken', item = 'marid_hide' },
        },
        boss =
        {
            { id = 2235, tier = 0, cat = 4, label = 'Enmity', item = 'bag_of_wildgrass_seeds' },
            { id = 2505, tier = 0, cat = 4, label = 'Parrying rate', item = 'heavy_quadav_backplate' },
            { id = 2520, tier = 0, cat = 4, label = 'Mag. Evasion', item = 'yagudo_kote' },
            { id = 2549, tier = 0, cat = 4, label = 'All elemental resists', item = 'pinch_of_djinn_ash' },
            { id = 2747, tier = 0, cat = 4, label = 'Magic Damage Taken', item = 'gargouille_horn' },
            { id = 3504, tier = 0, cat = 4, label = 'Enemy crit. hit rate', item = 'peapuk_wing' },
        },
    },
    gustavTunnel =
    {
        family = 'Pet Mastery',
        trash =
        {
            [1] = { id = 768, tier = 0, cat = 7, label = 'Pet Mag.Def.Bns', item = 'flint_stone' },
            [2] = { id = 821, tier = 0, cat = 7, label = 'Pet Haste', item = 'spool_of_rainbow_thread' },
            [3] = { id = 825, tier = 0, cat = 7, label = 'Pet Evasion', item = 'square_of_cotton_cloth' },
            [4] = { id = 827, tier = 0, cat = 7, label = 'Pet Mag. Evasion', item = 'square_of_wool_cloth' },
            [5] = { id = 839, tier = 0, cat = 7, label = 'Pet Acc R.Acc Atk. R.Atk', item = 'piece_of_crawler_cocoon' },
            [6] = { id = 852, tier = 0, cat = 7, label = 'Blood Boon', item = 'lizard_skin' },
            [7] = { id = 856, tier = 0, cat = 7, label = 'Pet TP Bonus', item = 'rabbit_hide' },
            [8] = { id = 914, tier = 0, cat = 7, label = 'Sic and Ready ability delay', item = 'vial_of_mercury' },
            [9] = { id = 918, tier = 0, cat = 7, label = 'Pet Subtle Blow', item = 'sprig_of_mistletoe' },
            [10] = { id = 938, tier = 0, cat = 7, label = 'Pet STR DEX VIT', item = 'sprig_of_papaka_grass' },
            [11] = { id = 939, tier = 0, cat = 7, label = 'Pet Enemy crit. hit rate', item = 'hecteyes_eye' },
            [12] = { id = 959, tier = 0, cat = 7, label = 'Pet DEF', item = 'dahlia' },
        },
        boss =
        {
            { id = 1133, tier = 0, cat = 7, label = 'Pet Regen', item = 'vial_of_dragon_blood' },
            { id = 1156, tier = 0, cat = 7, label = 'Avatar perpetuation cost', item = 'crawler_calculus' },
            { id = 1452, tier = 0, cat = 7, label = 'Avatar Blood Pact Dmg', item = 'ordelle_bronzepiece' },
            { id = 1518, tier = 0, cat = 7, label = 'Pet Mag.Acc. Mag.Atk.Bns', item = 'colossal_skull' },
            { id = 2153, tier = 0, cat = 7, label = 'Pet Phy. Dmg. Taken', item = 'qiqirn_sandbag' },
            { id = 2163, tier = 0, cat = 7, label = 'Pet Magic Damage', item = 'imp_wing' },
            { id = 2504, tier = 0, cat = 7, label = 'Pet Magic Dmg. Taken', item = 'heavy_quadav_chestplate' },
            { id = 2518, tier = 0, cat = 7, label = 'Beast Affinity', item = 'smilodon_hide' },
            { id = 2521, tier = 0, cat = 7, label = 'Pet Dbl.Atk. Crit.hit rate', item = 'gnole_claw' },
            { id = 2543, tier = 0, cat = 7, label = 'Pet Store TP', item = 'goblin_weel' },
            { id = 2888, tier = 0, cat = 7, label = 'Pet Enmity', item = 'sanguinet' },
            { id = 3543, tier = 0, cat = 7, label = 'Elemental Siphon', item = 'fossilized_fang' },
        },
    },
    kuftalTunnel =
    {
        family = 'Speed, Skills & Growth',
        trash =
        {
            [1] = { id = 816, tier = 0, cat = 5, label = 'Waltz ability delay', item = 'spool_of_silk_thread' },
            [2] = { id = 817, tier = 0, cat = 5, label = 'Song recast delay', item = 'spool_of_grass_thread' },
            [3] = { id = 820, tier = 0, cat = 5, label = 'Haste', item = 'spool_of_wool_thread' },
            [4] = { id = 828, tier = 0, cat = 5, label = 'Resist Slow', item = 'square_of_velvet_cloth' },
            [5] = { id = 832, tier = 0, cat = 5, label = 'Phantom Roll ability delay', item = 'clump_of_sheep_wool' },
            [6] = { id = 838, tier = 0, cat = 5, label = 'Healing Magic Recast Delay', item = 'spider_web' },
            [7] = { id = 849, tier = 0, cat = 5, label = 'Elemental Magic Recast Delay', item = 'undead_skin' },
            [8] = { id = 859, tier = 0, cat = 5, label = 'Enfeebling Magic Recast Delay', item = 'ram_skin' },
            [9] = { id = 868, tier = 0, cat = 5, label = 'Enhancing Magic Recast Delay', item = 'handful_of_pugil_scales' },
            [10] = { id = 876, tier = 0, cat = 5, label = 'Blood Pact ability delay', item = 'manta_skin' },
            [11] = { id = 912, tier = 0, cat = 5, label = 'Call Beast ability delay', item = 'beehive_chip' },
            [12] = { id = 1623, tier = 0, cat = 5, label = 'Quick Draw ability delay', item = 'eft_skin' },
        },
        boss =
        {
            { id = 1667, tier = 0, cat = 5, label = 'Song spellcasting time', item = 'cluster_core' },
            { id = 2198, tier = 0, cat = 5, label = 'Cure spellcasting time', item = 'water_spiders_web' },
            { id = 863, tier = 0, cat = 9, label = 'Treasure Hunter', item = 'coeurl_hide' },
            { id = 1607, tier = 0, cat = 9, label = 'Shield skill', item = 'remnant_of_a_bitter_memory' },
            { id = 1608, tier = 0, cat = 9, label = 'Parrying Skill', item = 'remnant_of_a_fleeting_memory' },
            -- 1616 'Melee skill', 1663 'Ranged skill', 1889 'Magic skill'
            -- removed with the catalog rows (all three are automaton-only mods).
            { id = 942, tier = 0, cat = 10, label = 'Cap. Point +33%', item = 'philosophers_stone' },
            { id = 2523, tier = 0, cat = 10, label = 'Exp. Point +33%', item = 'peiste_skin' },
        },
    },
    feiYin =
    {
        family = 'Potency & Duration',
        trash =
        {
            [1] = { id = 2510, tier = 0, cat = 6, label = 'Enhancing Magic Effect Duration', item = 'orc_helmet' },
            [2] = { id = 2640, tier = 0, cat = 6, label = 'Helix Effect Duration', item = 'murex_spicule' },
            [3] = { id = 2641, tier = 0, cat = 6, label = 'Indi Effect Duration', item = 'amoeban_pseudopod' },
            [4] = { id = 2711, tier = 0, cat = 6, label = 'Meditate Effect Duration', item = 'khroma_nugget' },
            [5] = { id = 848, tier = 0, cat = 8, label = 'Regen', item = 'square_of_dhalmel_leather' },
            [6] = { id = 850, tier = 0, cat = 8, label = 'Regen Potency', item = 'square_of_sheep_leather' },
            [7] = { id = 887, tier = 0, cat = 8, label = 'Potency of Cure received', item = 'coral_fragment' },
            [8] = { id = 919, tier = 0, cat = 8, label = 'Refresh', item = 'clump_of_boyahda_moss' },
            [9] = { id = 952, tier = 0, cat = 8, label = 'Cure potency', item = 'bag_of_poison_flour' },
            [10] = { id = 1119, tier = 0, cat = 8, label = 'Conserve MP', item = 'tonberry_coat' },
            [11] = { id = 1122, tier = 0, cat = 8, label = 'HP recovered while healing', item = 'wyvern_skin' },
            [12] = { id = 1196, tier = 0, cat = 8, label = 'Waltz potency', item = 'qiqirn_cape' },
        },
        boss =
        {
            { id = 1609, tier = 0, cat = 8, label = 'Drain/Aspir Potency', item = 'remnant_of_a_profane_memory' },
            { id = 1875, tier = 0, cat = 8, label = 'Phantom Roll effect', item = 'ancient_beastcoin' },
            { id = 2514, tier = 0, cat = 8, label = 'MP recovered while healing', item = 'rafflesia_petal' },
            { id = 2748, tier = 0, cat = 8, label = 'Repair potency', item = 'gargouille_shank' },
        },
    },
    ranguemontPass =
    {
        family = 'Foundations & Utility',
        trash =
        {
            [1] = { id = 818, tier = 0, cat = 1, label = 'HP MP', item = 'spool_of_cotton_thread' },
            [2] = { id = 841, tier = 0, cat = 1, label = 'MP', item = 'yagudo_feather' },
            [3] = { id = 853, tier = 0, cat = 1, label = 'HP', item = 'raptor_skin' },
            [4] = { id = 878, tier = 0, cat = 1, label = 'AGI', item = 'karakul_skin' },
            [5] = { id = 888, tier = 0, cat = 1, label = 'MND', item = 'seashell' },
            [6] = { id = 921, tier = 0, cat = 1, label = 'INT', item = 'bottle_of_ahriman_tears' },
            [7] = { id = 922, tier = 0, cat = 1, label = 'VIT', item = 'bat_wing' },
            [8] = { id = 1620, tier = 0, cat = 1, label = 'STR', item = 'taurus_horn' },
            [9] = { id = 2150, tier = 0, cat = 1, label = 'DEX', item = 'colibri_feather' },
            [10] = { id = 2823, tier = 0, cat = 1, label = 'CHR', item = 'iridium_ingot' },
            [11] = { id = 770, tier = 0, cat = 11, label = 'Shield Mastery', item = 'blue_rock' },
            [12] = { id = 829, tier = 0, cat = 11, label = 'Snapshot', item = 'square_of_silk_cloth' },
        },
        boss =
        {
            { id = 834, tier = 0, cat = 11, label = 'Recycle', item = 'ball_of_saruta_cotton' },
            { id = 836, tier = 0, cat = 11, label = 'Waltz TP cost', item = 'square_of_damascene_cloth' },
            { id = 857, tier = 0, cat = 11, label = 'Reverse Flourish', item = 'dhalmel_hide' },
            { id = 895, tier = 0, cat = 11, label = 'Counter', item = 'ram_horn' },
            { id = 897, tier = 0, cat = 11, label = 'Martial Arts', item = 'scorpion_claw' },
            { id = 902, tier = 0, cat = 11, label = 'Charm', item = 'demon_horn' },
            { id = 926, tier = 0, cat = 11, label = 'Zanshin', item = 'lizard_tail' },
            { id = 947, tier = 0, cat = 11, label = 'Daken', item = 'jar_of_firesand' },
            { id = 1199, tier = 0, cat = 11, label = 'Barrage', item = 'northern_fur' },
            { id = 1269, tier = 0, cat = 11, label = 'Ninja tool expertise', item = 'mana_barrel' },
            { id = 1615, tier = 0, cat = 11, label = 'Kick Attacks Rate or Damage', item = 'buffalo_horn' },
            { id = 1619, tier = 0, cat = 11, label = 'Rapid Shot', item = 'hippogryph_feather' },
            { id = 1630, tier = 0, cat = 11, label = 'Gilfinder', item = 'pinch_of_cluster_ash' },
            { id = 1888, tier = 0, cat = 11, label = 'All songs', item = 'sack_of_silica' },
        },
    },
}
