-----------------------------------
-- augment_dungeon_drops_data.lua
-- AUTO-GENERATED by tools/gen_augment_dungeon_drops.py -- DO NOT HAND-EDIT.
-- Re-run the script after augment_catalog.lua changes and commit both.
--
-- Per Augmentation Dungeon (dungeon_catalog.lua keys):
--   family : player-facing name of the stat family this dungeon owns
--   trash  : [slot 1-12] = fixed catalyst for that trash mob (roster order)
--   boss   : pool the boss draws from (family tier-3/4 remainder)
-- Consumed by augment_dungeon_drops.lua (runtime) and
-- tools/docgen/generators/augment_dungeon_drops.py (docs).
-----------------------------------
return {
    ordellesCaves =
    {
        family = 'Melee Offense',
        trash =
        {
            [1] = { id = 840, tier = 0, cat = 2, label = 'Store TP Subtle Blow', item = 'chocobo_fthr.' },
            [2] = { id = 846, tier = 0, cat = 2, label = 'Accuracy', item = 'insect_wing' },
            [3] = { id = 847, tier = 0, cat = 2, label = 'Rng.Accuracy', item = 'bird_feather' },
            [4] = { id = 861, tier = 0, cat = 2, label = 'Attack', item = 'tiger_hide' },
            [5] = { id = 865, tier = 0, cat = 2, label = 'Sklchn.dmg', item = 'nidhogg_scales' },
            [6] = { id = 874, tier = 0, cat = 2, label = 'Attack Rng.Atk', item = 'amaltheia_hide' },
            [7] = { id = 880, tier = 0, cat = 2, label = 'Dbl.Atk. Crit.hit rate', item = 'bone_chip' },
            [8] = { id = 882, tier = 0, cat = 2, label = 'Dbl.Atk', item = 'sheep_tooth' },
            [9] = { id = 883, tier = 0, cat = 2, label = 'Rng.Attack', item = 'behemoth_horn' },
            [10] = { id = 884, tier = 0, cat = 2, label = 'Accuracy Attack', item = 'blk._tiger_fang' },
            [11] = { id = 891, tier = 0, cat = 2, label = 'Triple Atk', item = 'bat_fang' },
            [12] = { id = 1108, tier = 0, cat = 2, label = 'Conserve TP', item = 'sulfur' },
        },
        boss =
        {
            { id = 1110, tier = 0, cat = 2, label = 'Weapon Skill Acc', item = 'beetle_blood' },
            { id = 1116, tier = 0, cat = 2, label = 'Rng.Acc. Rng.Atk', item = 'manticore_hide' },
            { id = 1271, tier = 0, cat = 2, label = 'TP Bonus', item = 'pigeons_blood' },
            { id = 1292, tier = 0, cat = 2, label = 'Accuracy Rng.Acc', item = 'damp_hktk._eye' },
            { id = 1473, tier = 0, cat = 2, label = 'Weapon skill damage', item = 'h.q._scp._shell' },
            { id = 1516, tier = 0, cat = 2, label = 'Save TP', item = 'griffon_hide' },
            { id = 1591, tier = 0, cat = 2, label = 'Quadruple Attack', item = 'h.q._coeurl_hide' },
            { id = 1621, tier = 0, cat = 2, label = 'Store TP', item = 'taurus_wing' },
            { id = 1690, tier = 0, cat = 2, label = 'Subtle Blow', item = 'hippogryph_tf.' },
            { id = 2148, tier = 0, cat = 2, label = 'Crit.hit rate', item = 'puk_wing' },
            { id = 2149, tier = 0, cat = 2, label = 'Crit. hit damage', item = 'apkallu_feather' },
        },
    },
    ifritsCauldron =
    {
        family = 'Magic Offense',
        trash =
        {
            [1] = { id = 842, tier = 0, cat = 3, label = 'Magic crit. hit rate', item = 'giant_bird_fthr.' },
            [2] = { id = 886, tier = 0, cat = 3, label = 'Mag. Acc', item = 'demon_skull' },
            [3] = { id = 905, tier = 0, cat = 3, label = 'Mag. Acc. Mag.Atk.Bns', item = 'wyvern_skull' },
            [4] = { id = 909, tier = 0, cat = 3, label = 'Mag. Acc./Mag. Dmg', item = 'guivres_skull' },
            [5] = { id = 1850, tier = 0, cat = 3, label = 'Enhances', item = 'first_virtue' },
            [6] = { id = 2335, tier = 0, cat = 3, label = 'Helix Damage' },
            [7] = { id = 2338, tier = 0, cat = 3, label = 'Enspell Dmg', item = 'wamoura_scale' },
            [8] = { id = 2426, tier = 0, cat = 3, label = 'Mag.Atk.Bns', item = 'wivre_horn' },
            [9] = { id = 2427, tier = 0, cat = 3, label = 'Fast Cast', item = 'wivre_maul' },
            [10] = { id = 2428, tier = 0, cat = 3, label = 'Occult Acumen', item = 'wivre_hide' },
            [11] = { id = 2498, tier = 0, cat = 3, label = 'Magic Damage' },
            [12] = { id = 2507, tier = 0, cat = 3, label = 'Occ. quickens spellcasting' },
        },
        boss =
        {
            { id = 2531, tier = 0, cat = 3, label = 'Spikes Dmg' },
            { id = 2776, tier = 0, cat = 3, label = 'Magic burst dmg', item = 'pumice_stone' },
            { id = 2777, tier = 0, cat = 3, label = 'Mag. crit. hit dmg', item = 'magicked_blood' },
            { id = 2834, tier = 0, cat = 3, label = 'Spell Interruption Rate Down' },
            { id = 2875, tier = 0, cat = 3, label = 'Immunobreak Chance+' },
        },
    },
    gusgenMines =
    {
        family = 'Survival & Defense',
        trash =
        {
            [1] = { id = 769, tier = 0, cat = 4, label = 'Mag.Def.Bns', item = 'red_rock' },
            [2] = { id = 771, tier = 0, cat = 4, label = 'Chance of successful block', item = 'yellow_rock' },
            [3] = { id = 772, tier = 0, cat = 4, label = 'Phalanx Received', item = 'green_rock' },
            [4] = { id = 774, tier = 0, cat = 4, label = 'DEF', item = 'purple_rock' },
            [5] = { id = 776, tier = 0, cat = 4, label = 'Parrying rate', item = 'white_rock' },
            [6] = { id = 787, tier = 0, cat = 4, label = 'Enmity', item = 'diamond' },
            [7] = { id = 858, tier = 0, cat = 4, label = 'Phys. dmg. taken', item = 'wolf_hide' },
            [8] = { id = 936, tier = 0, cat = 4, label = 'Magic dmg. taken', item = 'rock_salt' },
            [9] = { id = 1123, tier = 0, cat = 4, label = 'Damage Taken', item = 'manticore_fang' },
            [10] = { id = 1132, tier = 0, cat = 4, label = 'All elemental resists', item = 'raxa' },
            [11] = { id = 1193, tier = 0, cat = 4, label = 'Breath dmg. taken', item = 'h.q._crab_shell' },
            [12] = { id = 1617, tier = 0, cat = 4, label = 'Evasion', item = 'flytrap_leaf' },
        },
        boss =
        {
            { id = 1713, tier = 0, cat = 4, label = 'Mag. Evasion', item = 'cashmere_thrd.' },
            { id = 2151, tier = 0, cat = 4, label = 'Physical Damage Taken', item = 'marid_hide' },
            { id = 2158, tier = 0, cat = 4, label = 'Magic Damage Taken', item = 'hydra_fang' },
            { id = 2372, tier = 0, cat = 4, label = 'Resist Charm', item = 'khimaira_mane' },
            { id = 2831, tier = 0, cat = 4, label = 'Occ. inc. resist to stat ailments' },
            { id = 3504, tier = 0, cat = 4, label = 'Enemy crit. hit rate', item = 'peapuk_wing' },
        },
    },
    gustavTunnel =
    {
        family = 'Pet Mastery',
        trash =
        {
            [1] = { id = 768, tier = 0, cat = 7, label = 'Pet Mag.Def.Bns', item = 'flint_stone' },
            [2] = { id = 775, tier = 0, cat = 7, label = 'Pet Magic Dmg. Taken', item = 'black_rock' },
            [3] = { id = 810, tier = 0, cat = 7, label = 'Sic and Ready ability delay', item = 'fluorite' },
            [4] = { id = 825, tier = 0, cat = 7, label = 'Pet Evasion', item = 'cotton_cloth' },
            [5] = { id = 826, tier = 0, cat = 7, label = 'Pet Haste', item = 'linen_cloth' },
            [6] = { id = 827, tier = 0, cat = 7, label = 'Pet Mag. Evasion', item = 'wool_cloth' },
            [7] = { id = 839, tier = 0, cat = 7, label = 'Pet Acc R.Acc Atk. R.Atk', item = 'crawler_cocoon' },
            [8] = { id = 852, tier = 0, cat = 7, label = 'Blood Boon', item = 'lizard_skin' },
            [9] = { id = 856, tier = 0, cat = 7, label = 'Pet TP Bonus', item = 'rabbit_hide' },
            [10] = { id = 939, tier = 0, cat = 7, label = 'Pet Enemy crit. hit rate', item = 'hecteyes_eye' },
            [11] = { id = 1133, tier = 0, cat = 7, label = 'Pet Regen', item = 'dragon_blood' },
            [12] = { id = 1156, tier = 0, cat = 7, label = 'Avatar perpetuation cost', item = 'crawler_calculus' },
        },
        boss =
        {
            { id = 1272, tier = 0, cat = 7, label = 'Elemental Siphon', item = 'arioch_fang' },
            { id = 1289, tier = 0, cat = 7, label = 'Pet Store TP', item = 'burning_hktk._eye' },
            { id = 1290, tier = 0, cat = 7, label = 'Pet Subtle Blow', item = 'earthen_hktk._eye' },
            { id = 1408, tier = 0, cat = 7, label = 'Pet Enmity', item = 'illuminink' },
            { id = 1445, tier = 0, cat = 7, label = 'Avatar Blood Pact Dmg', item = 'freyas_tear' },
            { id = 1518, tier = 0, cat = 7, label = 'Pet Mag.Acc. Mag.Atk.Bns', item = 'colossal_skull' },
            { id = 1718, tier = 0, cat = 7, label = 'Pet Dbl.Atk. Crit.hit rate', item = 'm-bugard_tusk' },
            { id = 1979, tier = 0, cat = 7, label = 'Pet Phy. Dmg. Taken', item = 'leech_saliva' },
            { id = 2163, tier = 0, cat = 7, label = 'Pet Magic Damage', item = 'imp_wing' },
            { id = 2169, tier = 0, cat = 7, label = 'Pet STR DEX VIT', item = 'cerberus_hide' },
            { id = 2518, tier = 0, cat = 7, label = 'Beast Affinity' },
            { id = 2854, tier = 0, cat = 7, label = 'Pet DEF', item = 'stately_crab_sh.' },
        },
    },
    kuftalTunnel =
    {
        family = 'Speed, Skills & Growth',
        trash =
        {
            [1] = { id = 793, tier = 0, cat = 5, label = 'Cure spellcasting time', item = 'black_pearl' },
            [2] = { id = 801, tier = 0, cat = 5, label = 'Waltz ability delay', item = 'chrysoberyl' },
            [3] = { id = 817, tier = 0, cat = 5, label = 'Song recast delay', item = 'grass_thread' },
            [4] = { id = 820, tier = 0, cat = 5, label = 'Haste', item = 'wool_thread' },
            [5] = { id = 828, tier = 0, cat = 5, label = 'Resist Slow', item = 'velvet_cloth' },
            [6] = { id = 832, tier = 0, cat = 5, label = 'Phantom Roll ability delay', item = 'sheep_wool' },
            [7] = { id = 838, tier = 0, cat = 5, label = 'Healing Magic Recast Delay', item = 'spider_web' },
            [8] = { id = 849, tier = 0, cat = 5, label = 'Elemental Magic Recast Delay', item = 'undead_skin' },
            [9] = { id = 859, tier = 0, cat = 5, label = 'Enfeebling Magic Recast Delay', item = 'ram_skin' },
            [10] = { id = 868, tier = 0, cat = 5, label = 'Enhancing Magic Recast Delay', item = 'pugil_scales' },
            [11] = { id = 876, tier = 0, cat = 5, label = 'Blood Pact ability delay', item = 'manta_skin' },
            [12] = { id = 912, tier = 0, cat = 5, label = 'Call Beast ability delay', item = 'beehive_chip' },
        },
        boss =
        {
            { id = 1623, tier = 0, cat = 5, label = 'Quick Draw ability delay', item = 'eft_skin' },
            { id = 2827, tier = 0, cat = 5, label = 'Song spellcasting time', item = 'rgd._gld._thread' },
            { id = 1616, tier = 0, cat = 9, label = 'Melee skill', item = 'antlion_jaw' },
            { id = 1663, tier = 0, cat = 9, label = 'Ranged skill', item = 'arnica_root' },
            { id = 1864, tier = 0, cat = 9, label = 'Magic skill', item = 'h.q._antlion_jaw' },
            { id = 2936, tier = 0, cat = 9, label = 'Shield skill', item = 'chasmic_stinger' },
            { id = 2937, tier = 0, cat = 9, label = 'Parrying Skill', item = 'raskovnik_vine' },
            { id = 942, tier = 0, cat = 10, label = 'Cap. Point +33%', item = 'phil._stone' },
            { id = 2523, tier = 0, cat = 10, label = 'Exp. Point +33%', item = 'peiste_skin' },
        },
    },
    feiYin =
    {
        family = 'Potency & Duration',
        trash =
        {
            [1] = { id = 2510, tier = 0, cat = 6, label = 'Enhancing Magic Effect Duration' },
            [2] = { id = 2640, tier = 0, cat = 6, label = 'Helix Effect Duration' },
            [3] = { id = 2641, tier = 0, cat = 6, label = 'Indi Effect Duration' },
            [4] = { id = 2711, tier = 0, cat = 6, label = 'Meditate Effect Duration' },
            [5] = { id = 791, tier = 0, cat = 8, label = 'MP recovered while healing', item = 'aquamarine' },
            [6] = { id = 833, tier = 0, cat = 8, label = 'Cure potency', item = 'moko_grass' },
            [7] = { id = 848, tier = 0, cat = 8, label = 'Regen', item = 'dhalmel_leather' },
            [8] = { id = 850, tier = 0, cat = 8, label = 'Regen Potency', item = 'sheep_leather' },
            [9] = { id = 887, tier = 0, cat = 8, label = 'Potency of Cure received', item = 'coral_fragment' },
            [10] = { id = 919, tier = 0, cat = 8, label = 'Refresh', item = 'boyahda_moss' },
            [11] = { id = 1119, tier = 0, cat = 8, label = 'Conserve MP' },
            [12] = { id = 1122, tier = 0, cat = 8, label = 'HP recovered while healing', item = 'wyvern_skin' },
        },
        boss =
        {
            { id = 1741, tier = 0, cat = 8, label = 'Waltz potency', item = 'h.q._eft_skin' },
            { id = 1875, tier = 0, cat = 8, label = 'Phantom Roll effect', item = 'anct._beastcoin' },
            { id = 2729, tier = 0, cat = 8, label = 'Repair potency' },
            { id = 2943, tier = 0, cat = 8, label = 'Drain/Aspir Potency', item = 'balaur_skull' },
        },
    },
    ranguemontPass =
    {
        family = 'Foundations & Utility',
        trash =
        {
            [1] = { id = 773, tier = 0, cat = 1, label = 'VIT', item = 'translucent_rock' },
            [2] = { id = 841, tier = 0, cat = 1, label = 'MP', item = 'yagudo_feather' },
            [3] = { id = 860, tier = 0, cat = 1, label = 'HP', item = 'behemoth_hide' },
            [4] = { id = 867, tier = 0, cat = 1, label = 'HP MP', item = 'dragon_scales' },
            [5] = { id = 878, tier = 0, cat = 1, label = 'AGI', item = 'karakul_skin' },
            [6] = { id = 888, tier = 0, cat = 1, label = 'MND', item = 'seashell' },
            [7] = { id = 921, tier = 0, cat = 1, label = 'INT', item = 'ahriman_tears' },
            [8] = { id = 1620, tier = 0, cat = 1, label = 'STR', item = 'taurus_horn' },
            [9] = { id = 2150, tier = 0, cat = 1, label = 'DEX', item = 'colibri_feather' },
            [10] = { id = 2841, tier = 0, cat = 1, label = 'CHR', item = 'qdv._silv._ingot' },
            [11] = { id = 770, tier = 0, cat = 11, label = 'Shield Mastery', item = 'blue_rock' },
            [12] = { id = 829, tier = 0, cat = 11, label = 'Snapshot', item = 'silk_cloth' },
        },
        boss =
        {
            { id = 834, tier = 0, cat = 11, label = 'Recycle', item = 'saruta_cotton' },
            { id = 836, tier = 0, cat = 11, label = 'Waltz TP cost', item = 'damascene_cloth' },
            { id = 895, tier = 0, cat = 11, label = 'Counter', item = 'ram_horn' },
            { id = 897, tier = 0, cat = 11, label = 'Martial Arts', item = 'scorpion_claw' },
            { id = 902, tier = 0, cat = 11, label = 'Charm', item = 'demon_horn' },
            { id = 903, tier = 0, cat = 11, label = 'Kick Attacks Rate or Damage', item = 'dragon_talon' },
            { id = 908, tier = 0, cat = 11, label = 'Treasure Hunter', item = 'adamantoise_shell' },
            { id = 926, tier = 0, cat = 11, label = 'Zanshin', item = 'lizard_tail' },
            { id = 947, tier = 0, cat = 11, label = 'Daken', item = 'firesand' },
            { id = 1199, tier = 0, cat = 11, label = 'Barrage', item = 'northern_fur' },
            { id = 1269, tier = 0, cat = 11, label = 'Ninja tool expertise' },
            { id = 1291, tier = 0, cat = 11, label = 'All songs', item = 'golden_hktk._eye' },
            { id = 1293, tier = 0, cat = 11, label = 'Reverse Flourish', item = 'narasimha_hide' },
            { id = 1619, tier = 0, cat = 11, label = 'Rapid Shot', item = 'hippogryph_fthr.' },
            { id = 1858, tier = 0, cat = 11, label = 'Gilfinder', item = 'moblumin_ingot' },
        },
    },
}
