-----------------------------------
-- augment_catalyst_mobs.lua  (REGENERATED 2026-06-28: every catalyst drops from
-- a NON-NM mob in a classic, accessible Vana'diel zone. NM- and custom/instanced-
-- assigned catalysts were rebased onto level-banded normal mobs by tier.
-- CLEANED 2026-07-10: dropped 21 entries whose itemId is no longer in
-- augment_catalog.lua -- removed augments like the Resist/Delay lines; the
-- Moogle can't accept those items, so their mobs now use the random fallback.)
--
-- Mob internal name (mob:getName()) -> the augment catalyst itemId it drops.
-- Each mob appears at most once; a few catalysts have TWO source mobs.
-- Consumed by augment_catalyst_drops.lua (drops, 60%) and
-- tools/gen_catalyst_warp_table.py (!augwarp + website drop locations --
-- re-run it and tools/docgen after ANY edit here so all surfaces stay in sync).
-----------------------------------
return {
    ['Abashed_Heartwing'] = 2151,  -- Physical Damage Taken (T4, Abashed Heartwing L109)
    ['Abraxas'] = 1196,  -- Delay (melee,not ranged) (T3, Abraxas L86)
    ['Abxzomit'] = 895,  -- Counter / Ram Horn (T3, Abxzomit L80)
    ['Strato_Hippogryph'] = 1690,  -- Subtle Blow (T0, Strato Hippogryph L54)
    ['Abyssobugard'] = 927,  -- Delay (melee,not ranged) (T3, Abyssobugard L85)
    ['Accursed_Sorcerer'] = 848,  -- Regen (T3, Accursed Sorcerer L89)
    ['Acerbic_Jagil'] = 858,  -- Phys. dmg. taken (T4, Acerbic Jagil L104)
    ['Desert_Manticore'] = 1123,  -- Damage Taken (T0, Desert Manticore L53)
    ['Acid_Grease'] = 2338,  -- Enspell Dmg (T2, Acid Grease L54)
    ['Treefrost_Gefyrst'] = 820,  -- Haste (T0, Treefrost Gefyrst L104)
    ['Adasaurus'] = 882,  -- Dbl.Atk (T3, Adasaurus L84)
    ['Adjudicator_Demon'] = 2889,  -- Magic burst dmg (T3, Adjudicator Demon L83)
    ['Peapuk'] = 3504,  -- Enemy crit. hit rate (T0, Peapuk L81)
    ['Tyrannotaur'] = 1621,  -- Store TP (T0, Tyrannotaur L72)
    ['Gespenst'] = 829,  -- Snapshot (T0, Gespenst L68)
    ['Brontotaur'] = 1620,  -- STR (T0, Brontotaur L68)
    ['Aestutaur'] = 842,  -- Magic crit. hit rate (T3, Aestutaur L81)
    ['Agloolik'] = 853,  -- HP (T3, Agloolik L80)
    ['Aht_Urhgan_Attercop'] = 884,  -- Accuracy Attack (T2, Aht Urhgan Attercop L65)
    ['Ajattara'] = 1473,  -- Weapon skill damage (T3, Ajattara L83)
    ['Akrab'] = 2531,  -- Spikes Dmg (T3, Akrab L83)
    ['Monarch_Ogrefly'] = 846,  -- Accuracy (T0, Monarch Ogrefly L65)
    ['Amber_Quadav'] = 955,  -- Enhances (T0, Amber Quadav L8)
    ['Ameretat'] = 1521,  -- Weapon Skill Acc (T2, Ameretat L68)
    ['Amethyst_Quadav'] = 1449,  -- Phalanx Received (T2, Amethyst Quadav L63)
    ['Qiqirn_Mireguide'] = 2153,  -- Pet Phy. Dmg. Taken (T0, Qiqirn Mireguide L67)
    ['Ancient_Bomb'] = 2543,  -- Pet Store TP (T1, Ancient Bomb L40)
    ['Wild_Rabbit'] = 856,  -- Pet TP Bonus (T0, Wild Rabbit L1)
    ['Kraken'] = 770,  -- Shield Mastery (T0, Kraken L37)
    ['Lesser_Manticore'] = 1116,  -- Rng.Acc. Rng.Atk (T0, Lesser Manticore L47)
    ['Anemone'] = 878,  -- AGI (T2, Anemone L54)
    ['Djinn'] = 2549,  -- All elemental resists (T0, Djinn L53)
    ['Antican_Antesignanus'] = 2823,  -- CHR (T2, Antican Antesignanus L72)
    ['Antican_Centurio'] = 2150,  -- DEX (T2, Antican_Centurio L50)
    ['Antican_Faber'] = 959,  -- Pet DEF (T1, Antican Faber L39)
    ['Antican_Funditor'] = 2505,  -- Parrying rate (T1, Antican Funditor L39)
    ['Antican_Hoplomachus'] = 821,  -- Pet Haste (T2, Antican Hoplomachus L58)
    ['Antican_Veles'] = 881,  -- Mag.Def.Bns (T2, Antican_Veles L50)
    ['Antlion_Fly'] = 2426,  -- Mag.Atk.Bns (T2, Antlion Fly L64)
    ['Apex_Idle_Drifter'] = 863,  -- Dmg (ranged,not melee) (T4, Apex Idle Drifter L142)
    ['Apocalyptic_Weapon'] = 937,  -- Rng.Attack (T3, Apocalyptic Weapon L80)
    ['Appetent_Umbril'] = 2149,  -- Crit. hit damage (T4, Appetent Umbril L101)
    ['Escarp_Murex'] = 2640,  -- Helix Effect Duration (T0, Escarp Murex L77)
    ['Flying_Manta'] = 876,  -- Blood Pact ability delay (T0, Flying Manta L55)
    ['Wivre'] = 2427,  -- Fast Cast (T0, Wivre L68)
    ['Atomic_Cluster'] = 918,  -- Pet Subtle Blow (T1, Atomic Cluster L46)
    ['Abyssal_Demon'] = 902,  -- Charm (T0, Abyssal Demon L64)
    ['Axe_Beak'] = 1156,  -- Avatar perpetuation cost (T0, Axe Beak L28)
    ['Huge_Hornet'] = 912,  -- Call Beast ability delay (T0, Huge Hornet L1)
    ['Azren_Kuguza'] = 2711,  -- Meditate Effect Duration (T1, Azren Kuguza L43)
    ['Balayang'] = 1591,  -- Quadruple Attack (h.q. coeurl hide, Balayang L95)
    ['Smilodon'] = 2518,  -- Beast Affinity (T0, Smilodon L46)
    ['Bastion_Bats'] = 947,  -- Daken (T0, Bastion Bats L21)
    ['Battering_Ram'] = 928,  -- Wind resist (T0, Battering Ram L23)
    ['Battle_Bat'] = 836,  -- Waltz TP cost (T0, Battle Bat L20)
    ['Battrap'] = 2520,  -- Mag. Evasion (T1, Battrap L37)
    ['Battue_Bats'] = 834,  -- Recycle (T0, Battue Bats L5)
    ['Puk'] = 2148,  -- Crit.hit rate (T0, Puk L68)
    ['Bigclaw'] = 1889,  -- Magic skill (T1, Bigclaw L48)
    ['Hawkertrap'] = 1617,  -- Evasion (T0, Hawkertrap L38)
    ['Blizzard_Gigas'] = 1663,  -- Ranged skill (T1, Blizzard Gigas L48)
    ['Blood_Soul'] = 954,  -- Mag. Acc. Mag.Atk.Bns (T2, Blood_Soul L50)
    ['Tunnel_Worm'] = 1470,  -- Resist Charm (T0, Tunnel Worm L1)
    ['Boribaba'] = 936,  -- Magic dmg. taken (T4, Boribaba L95)
    ['Moblin_Chapman'] = 1638,  -- Occ. inc. resist to stat ailments (T0, Moblin Chapman L33)
    ['Brook_Sahagin'] = 1609,  -- Drain/Aspir Potency (T1, Brook Sahagin L45)
    ['Bugard'] = 939,  -- Pet Enemy crit. hit rate (T1, Bugard L37)
    ['Bugbear_Servingman'] = 2510,  -- Enhancing Magic Effect Duration (T1, Bugbear Servingman L35)
    ['Guard_Skeleton'] = 880,  -- Dbl.Atk. Crit.hit rate (T0, Guard Skeleton L66)
    ['Giant_Lobber'] = 1199,  -- Barrage (T0, Giant Lobber L28)
    ['Canal_Bats'] = 839,  -- Pet Acc R.Acc Atk. R.Atk (T1, Canal Bats L46)
    ['Labyrinth_Scorpion'] = 897,  -- Martial Arts (T0, Labyrinth Scorpion L30)
    ['Carmine_Eruca'] = 1163,  -- Sklchn.dmg (T3, Carmine_Eruca L70)
    ['Caterchipillar'] = 1518,  -- Pet Mag.Acc. Mag.Atk.Bns (T1, Caterchipillar L31)
    ['Cave_Scorpion'] = 827,  -- Pet Mag. Evasion (T1, Cave Scorpion L33)
    ['Caveberry'] = 825,  -- Pet Evasion (T1, Caveberry L44)
    ['Chamber_Beetle'] = 928,  -- DEF (T2, Chamber Beetle L58)
    ['Charging_Sheep'] = 2514,  -- MP recovered while healing (T1, Charging_Sheep L28)
    ['Land_Pugil'] = 1888,  -- All songs (T0, Land Pugil L17)
    ['Yagudo_Acolyte'] = 1606,  -- Immunobreak Chance+ (T0, Yagudo Acolyte L1)
    ['Clipper'] = 2198,  -- Cure spellcasting time (T1, Clipper L29)
    ['Cockatrice'] = 850,  -- Regen Potency (T2, Cockatrice L50)
    ['Yagudo_Initiate'] = 841,  -- MP (T0, Yagudo Initiate L1)
    ['Eft'] = 1623,  -- Quick Draw ability delay (T0, Eft L33)
    ['Marsh_Sahagin'] = 888,  -- MND (T0, Marsh Sahagin L52)
    ['Cloud_Hippogryph'] = 1619,  -- Rapid Shot (T0, Cloud Hippogryph L45)
    ['Goblin_Weaver'] = 817,  -- Song recast delay (T0, Goblin Weaver L1)
    ['Craver'] = 1875,  -- Phantom Roll effect (T1, Craver L29)
    ['Tonberry_Cutter'] = 1119,  -- Conserve MP (T0, Tonberry Cutter L51)
    ['Goblin_Conjurer'] = 3543,  -- Elemental Siphon (T0, Goblin Conjurer L86)
    ['Death_Jacket'] = 2504,  -- Pet Magic Dmg. Taken (T1, Death Jacket L48)
    ['Wild_Dhalmel'] = 857,  -- Reverse Flourish (T0, Wild Dhalmel L14)
    ['Demon_Warlock'] = 886,  -- Mag. Acc (T2, Demon_Warlock L50)
    ['Deviling_Bats'] = 2747,  -- Magic Damage Taken (T4, Deviling_Bats L95)
    ['Crawler'] = 816,  -- Waltz ability delay (T0, Crawler L3)
    ['Ding_Bats'] = 868,  -- Enhancing Magic Recast Delay (T0, Ding_Bats L1)
    ['Carrion_Worm'] = 943,  -- Mag. crit. hit dmg (T0, Carrion Worm L1)
    ['Goobbue'] = 919,  -- Refresh (T0, Goobbue L22)
    ['Uleguerand_Tiger'] = 861,  -- Attack (T0, Uleguerand Tiger L60)
    ['Savanna_Rarab'] = 818,  -- HP MP (T0, Savanna Rarab L1)
    ['Battle_Bugard'] = 1622,  -- Attack Rng.Atk (T0, Battle Bugard L78)
    ['Drowned_Bones'] = 855,  -- TP Bonus (T4, Drowned_Bones L95)
    ['Stream_Amoeban'] = 2641,  -- Indi Effect Duration (T0, Stream Amoeban L77)
    ['Evil_Spirit'] = 1608,  -- Parrying Skill (T1, Evil Spirit L43)
    ['Magic_Pot'] = 914,  -- Sic and Ready ability delay (T0, Magic Pot L28)
    ['Fallen_Knight'] = 1474,  -- Magic Damage (T2, Fallen_Knight L50)
    ['Fledermaus'] = 2166,  -- Spell Interruption Rate Down 2% (T1, Fledermaus L47)
    ['Forest_Hare'] = 918,  -- Ice resist (T0, Forest_Hare L1)
    ['Dire_Gargouille'] = 2748,  -- Repair potency (T0, Dire Gargouille L78)
    ['Cluster'] = 1630,  -- Gilfinder (T0, Cluster L38)
    ['Giant_Ranger'] = 2507,  -- Occ. quickens spellcasting (T1, Giant_Ranger L28)
    ['Soulflayer'] = 2335,  -- Helix Damage (T0, Soulflayer L82)
    ['Goblin_Hunter'] = 921,  -- INT (T2, Goblin_Hunter L50)
    ['Goblin_Trader'] = 828,  -- Resist Slow (T0, Goblin Trader L40)
    ['Goblin_Pathfinder'] = 938,  -- Pet STR DEX VIT (T1, Goblin_Pathfinder L28)
    ['Goblin_Shaman'] = 942,  -- Cap. Point +33% (T1, Goblin_Shaman L28)
    ['Goblin_Smithy'] = 1616,  -- Melee skill (T1, Goblin_Smithy L28)
    ['Gnole'] = 2521,  -- Pet Dbl.Atk. Crit.hit rate (T0, Gnole L65)
    ['Goblin_Thug'] = 937,  -- Earth resist (T0, Goblin_Thug L1)
    ['Giant_Buffalo'] = 1615,  -- Kick Attacks Rate or Damage (T0, Giant Buffalo L68)
    ['Gold_Quadav'] = 847,  -- Rng.Accuracy (T2, Gold_Quadav L50)
    ['Gigadaphnia'] = 2888,  -- Pet Enmity (T0, Gigadaphnia L74)
    ['Graupel_Formation'] = 1163,  -- Resist Sleep (T0, Graupel_Formation L1)
    ['Orcish_Veteran'] = 1516,  -- Save TP (T0, Orcish Veteran L50)
    ['Mesa_Wivre'] = 2428,  -- Occult Acumen (T0, Mesa Wivre L78)
    ['Delta_Sahagin'] = 887,  -- Potency of Cure received (T0, Delta Sahagin L62)
    ['Hornfly'] = 927,  -- Accuracy Rng.Acc (T2, Hornfly L50)
    ['Orderly_Imp'] = 2157,  -- Conserve TP (T0, Orderly Imp L63)
    ['Huge_Spider'] = 1607,  -- Shield skill (T1, Huge_Spider L28)
    ['Goblin_Gambler'] = 952,  -- Cure potency (T0, Goblin Gambler L20)
    ['Morbid_Eye'] = 935,  -- Store TP Subtle Blow (T0, Morbid Eye L52)
    ['Giant_Spider'] = 838,  -- Healing Magic Recast Delay (T0, Giant Spider L30)
    ['River_Crab'] = 1269,  -- Ninja tool expertise (T0, River Crab L1)
    ['Yagudo_Scribe'] = 2235,  -- Enmity (T0, Yagudo Scribe L1)
    ['Rock_Lizard'] = 926,  -- Zanshin (T0, Rock Lizard L3)
    ['Makara'] = 1193,  -- Breath dmg. taken (T1, Makara L29)
    ['Tremor_Ram'] = 859,  -- Enfeebling Magic Recast Delay (T0, Tremor Ram L21)
    ['Meat_Maggot'] = 889,  -- Chance of successful block (T1, Meat_Maggot L29)
    ['Mummy'] = 909,  -- Mag. Acc./Mag. Dmg (T2, Mummy L50)
    ['Mythril_Quadav'] = 922,  -- VIT (T2, Mythril_Quadav L50)
    ['Peiste'] = 2523,  -- Exp. Point +33% (T0, Peiste L66)
    ['Naraka_Bat'] = 891,  -- Triple Atk (T0, Naraka Bat L81)
    ['Nitro_Cluster'] = 1667,  -- Song spellcasting time (T0, Nitro Cluster L55)
    ['Protozoan'] = 2163,  -- Pet Magic Damage (T1, Protozoan L29)
    ['Pugil'] = 852,  -- Blood Boon (T0, Pugil L1)
    ['Stone_Eater'] = 832,  -- Phantom Roll ability delay (T0, Stone Eater L1)
    ['Addled_Tumor'] = 849,  -- Elemental Magic Recast Delay (T0, Addled Tumor L36)
    ['Seether'] = 1133,  -- Pet Regen (T1, Seether L28)
    ['Spinous_Pugil'] = 1122,  -- HP recovered while healing (T1, Spinous_Pugil L29)
    ['Spunkie'] = 1452,  -- Avatar Blood Pact Dmg (T1, Spunkie L28)
    ['Yuhtunga_Mandragora'] = 768,  -- Pet Mag.Def.Bns (T1, Yuhtunga_Mandragora L29)
}
