-----------------------------------
-- augment_dungeon_drops.lua
--
-- Augment-catalyst drops inside the seven "Augmentation Dungeons"
-- (dungeon_catalog.lua category). Each dungeon owns a stat FAMILY:
--
--   * Trash mobs (roster slots 1-12) each carry ONE fixed catalyst from the
--     family's low tiers -- the killing blow rolls TRASH_RATE% to award it
--     STRAIGHT TO THE KILLER's inventory (1:1 mob->item model). (Originally a
--     treasure-pool drop, but player:addTreasure silently no-ops when the killer
--     has no usable pool -- which is the case for SOLO players and inside these
--     private instances -- so catalysts never arrived. Direct award works solo,
--     partied, and instanced; the boss payout already hands out per-member.)
--   * The boss (last roster slot, spawned ONLY after a full clear) pays every
--     party member a catalyst from the family's tier-3+ pool, straight to
--     inventory, GUARANTEED on every clear: BOSS_QTY on the first clear of the
--     UTC day, BOSS_REPEAT_QTY on repeats (never nothing).
--
-- The slot -> catalyst mapping lives in augment_dungeon_drops_data.lua
-- (AUTO-GENERATED by tools/gen_augment_dungeon_drops.py -- rerun it after
-- augment_catalog.lua changes). Called from dungeon_instance.lua's per-mob
-- onMobDeath dispatch; dungeon mobs spawn with NO_DROPS so this is their
-- only loot channel. SOFT gating: open-world catalyst sources are untouched.
--
-- Plain require()-library. xi.* only inside functions (call-time), per the
-- module auto-load rule.
--
-- HOT-RELOADABLE: dungeon_instance.lua captures THIS table via require and its
-- live mobs call `augmentDrops.onDungeonMobDeath` by field lookup at kill time.
-- FileWatcher re-runs modules/ files on save (discarding the return value), and
-- package.loaded still holds the original table during that re-run -- so we grab
-- it and mutate its fields in place instead of returning a fresh table. That
-- makes edits (e.g. a rate tweak) go live WITHOUT a map restart. On first load
-- package.loaded is nil, so this is just `{}`.
-----------------------------------
local M = package.loaded['modules/custom/lua/augment_dungeon_drops']
if type(M) ~= 'table' then M = {} end

local TRASH_RATE      = 30 -- % chance the assigned trash catalyst drops to the killer (rolled once, on the killing blow)
local BOSS_QTY        = 5  -- catalysts each member receives on the FIRST full clear of the UTC day
local BOSS_REPEAT_QTY = 2  -- catalysts each member receives on every REPEAT full clear that day (guaranteed -- a clear is never nothing)

local data
local function drops()
    if not data then
        local ok, t = pcall(require, 'modules/custom/lua/augment_dungeon_drops_data')
        data = (ok and type(t) == 'table') and t or {}
    end
    return data
end

local function prettyItem(entry)
    if not entry.item then
        return entry.label
    end
    local n = entry.item:gsub('_', ' '):gsub("(%a[%w']*)", function(w)
        return w:sub(1, 1):upper() .. w:sub(2)
    end)
    return string.format('%s -- %s', n, entry.label)
end

-- Catalyst payout (used by BOTH the boss and trash paths): hand `qty` of
-- `entry`'s catalyst straight to `player`'s inventory. Returns true when handed
-- over (false = inventory full, so the boss path doesn't burn that member's
-- daily guarantee).
local function awardDirect(player, entry, qty)
    local display = string.format('%s (T%d)', prettyItem(entry), entry.tier)

    if player:getFreeSlotsCount() <= 0 then
        player:printToPlayer(string.format(
            '[Dungeon] %s x%d dropped, but your inventory is full!', display, qty),
            xi.msg.channel.SYSTEM_3)
        return false
    end

    pcall(function() player:addItem({ id = entry.id, quantity = qty }) end)
    player:printToPlayer(string.format(
        '[Dungeon] Catalyst dropped: %s x%d.', display, qty),
        xi.msg.channel.SYSTEM_3)
    return true
end

-- Called once per alliance member per kill; we act only on the killing-blow
-- dispatch (optParams.isKiller is true exactly once per kill).
M.onDungeonMobDeath = function(dungeonKey, instance, deadMob, player, optParams, slotArg, isBossArg)
    if player == nil or type(optParams) ~= 'table' or not optParams.isKiller then
        return
    end

    local d = drops()[dungeonKey]
    if not d then
        return -- not an Augmentation Dungeon (Challenge/Progression run)
    end

    -- Roster slot + boss flag are passed straight from dungeon_instance's spawn
    -- closure. The DungeonMobIndex / DungeonBossMob localvars do NOT survive on
    -- these dynamic mobs (they read 0 at death -> nothing ever dropped), so the
    -- passed args are authoritative; the localvar reads are only a fallback.
    local slot = slotArg or deadMob:getLocalVar('DungeonMobIndex')
    print(string.format('[augchk] key=%s slot=%s isBoss=%s', tostring(dungeonKey), tostring(slot), tostring(isBossArg)))
    if not slot or slot == 0 then
        return
    end

    -- Belt-and-braces: never pay the same corpse twice.
    if deadMob:getLocalVar('DungeonAugRolled') ~= 0 then
        return
    end
    deadMob:setLocalVar('DungeonAugRolled', 1)

    local isBoss = isBossArg
    if isBoss == nil then
        isBoss = (deadMob:getLocalVar('DungeonBossMob') == 1)
    end
    if isBoss then
        if #d.boss == 0 then
            return
        end

        local today    = tonumber(os.date('!%Y%j')) -- UTC Julian day (matches daily_login_bonus)
        local dailyVar = 'AugDgnDaily_' .. dungeonKey

        for _, member in ipairs(instance:getChars()) do
            -- The boss only spawns after a full clear (dungeon_instance withholds
            -- it), so every boss kill pays out -- players asked for "100% boss loot
            -- on full clear". First clear each UTC day pays the full BOSS_QTY;
            -- repeats still pay, at BOSS_REPEAT_QTY, so a clear is never nothing.
            local firstOfDay = member:getCharVar(dailyVar) ~= today
            local qty        = firstOfDay and BOSS_QTY or BOSS_REPEAT_QTY
            -- Burn the daily guarantee only if the catalyst actually landed
            -- (award fails on a full inventory).
            if awardDirect(member, d.boss[math.random(#d.boss)], qty) and firstOfDay then
                member:setCharVar(dailyVar, today)
            end
        end
    else
        local entry = d.trash[slot]
        if entry and math.random(100) <= TRASH_RATE then
            print('[augchk] TRASH AWARD slot=' .. tostring(slot) .. ' id=' .. tostring(entry.id) .. ' -> ' .. player:getName())
            awardDirect(player, entry, 1)  -- straight to the killer (see note on awardDirect)
        end
    end
end

return M
