-----------------------------------
-- gear_progression_catalog.lua
-- Weapons-only progression catalog for the Gear Progression NPC.
--
-- HOW TO ADD A WEAPON:
--   Pick a tier (bronze / silver / gold) and the matching weapon category.
--   Add a line in that category's `items` list:
--     { id = xi.item.ITEM_CONSTANT, name = 'Display Name', cost = N, jobs = 'JOB/JOB' }
--   If the item has no xi.item constant, use the raw numeric ID instead.
--   Find item IDs in: scripts/enum/item.lua
--
-- MEDAL COSTS (suggested baseline - adjust freely):
--   Bronze : 10-30  Beastmens Medals
--   Silver : 10-30  Kindreds Medals
--   Gold   : 10-30  Demons Medals
--
-- The NPC only shows categories that contain at least one item - adding
-- new categories below with empty `items` lists is fine; they stay hidden
-- until you populate them.
-----------------------------------
local catalog = {}

-----------------------------------
-- ZONE / NPC PLACEMENT
--   Single source of truth for:
--     - GearProgression_NPC.lua : override registration + NPC position
--     - docgen                  : gear-vendors.md location table + zone name
-----------------------------------
catalog.zoneId    = xi.zone.ESCHA_ZITAH
catalog.zonePath  = 'xi.zones.Escha_ZiTah'
catalog.vendorPos = { x =  -6.0000, y = -0.5000, z = -30.0000, rot = 128 }

-----------------------------------
-- SEAL CURRENCY DEFINITIONS
-----------------------------------
-- All three are orphan currency items in item_basic.sql (no current drop
-- source) - exclusive Hunting League currency loop. Raw IDs because
-- xi.item.* enum entries don't exist for these medals.
catalog.seals =
{
    bronze = { id = 9539, name = "Beastmens Medal" },
    silver = { id = 9541, name = "Kindreds Medal"  },
    gold   = { id = 9543, name = "Demons Medal"    },
}

-----------------------------------
-- Weapon category template
--   Used by all three tiers - copy/paste this shape when adding tiers.
-----------------------------------
local function emptyCategories()
    return
    {
        { label = 'Swords',         items = {} },
        { label = 'Daggers',        items = {} },
        { label = 'Clubs',          items = {} },
        { label = 'Staves',         items = {} },
        { label = 'Great Swords',   items = {} },
        { label = 'Axes',           items = {} },
        { label = 'Great Axes',     items = {} },
        { label = 'Scythes',        items = {} },
        { label = 'Polearms',       items = {} },
        { label = 'Katana',         items = {} },
        { label = 'Great Katana',   items = {} },
        { label = 'Archery',        items = {} },
        { label = 'Marksmanship',   items = {} },
        { label = 'Hand-to-Hand',   items = {} },
        { label = 'Instruments',    items = {} },
    }
end

-- Convenience: index by category label so we can append without remembering
-- the slot index (Swords = [1], etc.).
local function cat(weaponsList, label)
    for _, g in ipairs(weaponsList) do
        if g.label == label then return g.items end
    end
    error('unknown weapon category: ' .. label)
end

-----------------------------------
-- BRONZE TIER  (auto-generated by tools/score_weapons.py)
--   Role-balanced top picks per weapon category, expanded as needed
--   to guarantee >= 1 option per applicable job.
--   To regenerate after edits to weights or new DB content:
--     python tools/score_weapons.py
-----------------------------------
catalog.bronze = { weapons = emptyCategories() }
do
    -- Hand-to-Hand: 8 pick(s)
    local h2h = cat(catalog.bronze.weapons, 'Hand-to-Hand')
    table.insert(h2h, { id = 20507, name = "Comeuppances", cost = 12, jobs = 'MNK/PUP' })  -- WS score 179, DMG 162/Dly 561
    table.insert(h2h, { id = 20512, name = "Verethragna 119 Iii", cost = 12, jobs = 'MNK/PUP' })  -- WS score 179, DMG 158/Dly 561
    table.insert(h2h, { id = 20523, name = "Chastisers", cost = 12, jobs = 'MNK/PUP' })  -- WS score 176, DMG 148/Dly 570
    table.insert(h2h, { id = 21510, name = "Voluspa Knuckles", cost = 12, jobs = 'WAR/MNK/RDM/THF/PLD/DRK/BST/PUP/DNC' })  -- WS score 170, DMG 121/Dly 576
    table.insert(h2h, { id = 20518, name = "Eshus", cost = 12, jobs = 'MNK/PUP' })  -- DPS score 170, DMG 154/Dly 606
    table.insert(h2h, { id = 21517, name = "Eletta Knuckles", cost = 12, jobs = 'WAR/MNK/RDM/THF/DRK/BST/NIN/PUP/DNC' })  -- WS score 150, DMG 151/Dly 576
    table.insert(h2h, { id = 20517, name = "Fleshcarvers", cost = 12, jobs = 'MNK/PUP' })  -- WS score 144, DMG 114/Dly 570
    table.insert(h2h, { id = 20529, name = "Calved Claws", cost = 12, jobs = 'WAR/MNK/RDM/THF/DRK/BST/NIN/PUP/DNC' })  -- WS score 124, DMG 114/Dly 570

    -- Daggers: 9 pick(s)
    local daggers = cat(catalog.bronze.weapons, 'Daggers')
    table.insert(daggers, { id = 20555, name = "Mandau 119", cost = 12, jobs = 'RDM/THF/BRD' })  -- DPS score 170, DMG 91/Dly 176
    table.insert(daggers, { id = 20556, name = "Mandau 119 Ii", cost = 12, jobs = 'RDM/THF/BRD' })  -- DPS score 170, DMG 91/Dly 176
    table.insert(daggers, { id = 20636, name = "Izhiikoh", cost = 12, jobs = 'THF/BRD/DNC' })  -- DPS score 138, DMG 108/Dly 200
    table.insert(daggers, { id = 20610, name = "Rhadamanthus", cost = 12, jobs = 'THF/BRD/COR/DNC' })  -- DPS score 133, DMG 106/Dly 195
    table.insert(daggers, { id = 20563, name = "Twashtar", cost = 12, jobs = 'THF/BRD/DNC' })  -- DPS score 101, DMG 89/Dly 176
    table.insert(daggers, { id = 21586, name = "Prime Dagger", cost = 12, jobs = 'RDM/THF/BRD/DNC' })  -- DPS score 80, DMG 117/Dly 176
    table.insert(daggers, { id = 21587, name = "Mpu Gandring", cost = 12, jobs = 'RDM/THF/BRD/DNC' })  -- DPS score 80, DMG 117/Dly 176
    table.insert(daggers, { id = 20620, name = "Sabebus", cost = 12, jobs = 'WAR/THF/PLD/DRK/BRD/RNG/SAM/NIN/DRG/COR/PUP/DNC' })  -- DPS score 70, DMG 101/Dly 196
    table.insert(daggers, { id = 20605, name = "Odium", cost = 12, jobs = 'WAR/RDM/THF/BST/BRD/RNG/NIN/COR/DNC' })  -- DPS score 65, DMG 113/Dly 208

    -- Swords: 8 pick(s)
    local swords = cat(catalog.bronze.weapons, 'Swords')
    table.insert(swords, { id = 20690, name = "Reikiko", cost = 12, jobs = 'WAR/PLD/DRK/RUN' })  -- DPS score 197, DMG 164/Dly 268
    table.insert(swords, { id = 21622, name = "Voluspa Sword", cost = 12, jobs = 'WAR/RDM/PLD/DRK/BLU/COR/RUN' })  -- DPS score 190, DMG 126/Dly 233
    table.insert(swords, { id = 21635, name = "Malignance Sword", cost = 12, jobs = 'WAR/PLD/DRK/RUN' })  -- WS score 144, DMG 183/Dly 264
    table.insert(swords, { id = 20738, name = "Buramenkah", cost = 12, jobs = 'RDM/PLD/BLU' })  -- DPS score 135, DMG 130/Dly 240
    table.insert(swords, { id = 20611, name = "Sangarius", cost = 12, jobs = 'WAR/DRK' })  -- DPS score 135, DMG 157/Dly 290
    table.insert(swords, { id = 20699, name = "Koboto", cost = 12, jobs = 'WAR/THF/DRK/BST/RNG/SAM' })  -- DPS score 134, DMG 144/Dly 240
    table.insert(swords, { id = 20716, name = "Perfervid Sword", cost = 12, jobs = 'WAR/THF/DRK/BST/RNG/SAM/BLU' })  -- DPS score 117, DMG 110/Dly 236
    table.insert(swords, { id = 20613, name = "Pukulatmuj", cost = 12, jobs = 'WAR/RDM/THF/PLD/DRK/BRD/RNG/NIN/DRG/BLU/RUN' })  -- DPS score 113, DMG 115/Dly 231

    -- Great Swords: 6 pick(s)
    local greatswords = cat(catalog.bronze.weapons, 'Great Swords')
    table.insert(greatswords, { id = 20765, name = "Tunglmyrkvi", cost = 12, jobs = 'WAR/PLD/DRK/RUN' })  -- WS score 186, DMG 264/Dly 489
    table.insert(greatswords, { id = 20764, name = "Crobaci +2", cost = 12, jobs = 'PLD/DRK/RUN' })  -- WS score 162, DMG 245/Dly 501
    table.insert(greatswords, { id = 21684, name = "Caladbolg", cost = 12, jobs = 'PLD/DRK' })  -- WS score 152, DMG 303/Dly 430
    table.insert(greatswords, { id = 20770, name = "Mesyohi Sword", cost = 12, jobs = 'WAR/PLD/DRK/RUN' })  -- WS score 143, DMG 247/Dly 456
    table.insert(greatswords, { id = 20763, name = "Kbiroj", cost = 12, jobs = 'WAR/PLD/DRK/RUN' })  -- WS score 133, DMG 242/Dly 456
    table.insert(greatswords, { id = 21699, name = "Nibiru Faussar", cost = 12, jobs = 'PLD/DRK/RUN' })  -- WS score 130, DMG 259/Dly 456

    -- Axes: 5 pick(s)
    local axes = cat(catalog.bronze.weapons, 'Axes')
    table.insert(axes, { id = 21720, name = "Eletta Axe", cost = 12, jobs = 'WAR/DRK/BST/RNG/RUN' })  -- WS score 163, DMG 176/Dly 288
    table.insert(axes, { id = 20808, name = "Tramontane Axe", cost = 12, jobs = 'WAR/DRK/BST/RUN' })  -- DPS score 128, DMG 156/Dly 288
    table.insert(axes, { id = 20827, name = "Kerehcatl", cost = 12, jobs = 'WAR/BST' })  -- WS score 117, DMG 156/Dly 288
    table.insert(axes, { id = 20794, name = "Farsha", cost = 12, jobs = 'WAR/BST' })  -- WS score 96, DMG 140/Dly 276
    table.insert(axes, { id = 20813, name = "Emxgha", cost = 12, jobs = 'WAR/DRK/BST/RUN' })  -- WS score 82, DMG 164/Dly 312

    -- Great Axes: 1 pick(s)
    local greataxes = cat(catalog.bronze.weapons, 'Great Axes')
    table.insert(greataxes, { id = 20846, name = "Jokushuono", cost = 12, jobs = 'WAR/DRK' })  -- WS score 174, DMG 302/Dly 504

    -- Polearms: 1 pick(s)
    local polearms = cat(catalog.bronze.weapons, 'Polearms')
    table.insert(polearms, { id = 20945, name = "Nativus Halberd", cost = 12, jobs = 'WAR/PLD/SAM/DRG' })  -- WS score 129, DMG 207/Dly 396

    -- Katana: 0 pick(s) + 1 manual
    local katana = cat(catalog.bronze.weapons, 'Katana')
    table.insert(katana, { id = 21919, name = "Ajja Katana", cost = 12, jobs = 'NIN' })  -- MANUAL, DMG 132/Dly 227

    -- Staves: 3 pick(s)
    local staves = cat(catalog.bronze.weapons, 'Staves')
    table.insert(staves, { id = 21170, name = "Nilgal Pole", cost = 12, jobs = 'MNK/WHM/PLD/DRG' })  -- DPS score 176, DMG 223/Dly 412
    table.insert(staves, { id = 21168, name = "Ungeri Staff", cost = 12, jobs = 'WAR/MNK/WHM/BLM/PLD/BRD/DRG/SMN/SCH/GEO' })  -- WS score 156, DMG 220/Dly 412
    table.insert(staves, { id = 21166, name = "Staccato Staff", cost = 12, jobs = 'WAR/MNK/WHM/BLM/RDM/BST/BRD/SMN/SCH/GEO' })  -- CASTER score 140, DMG 198/Dly 366

    -- Archery: 2 pick(s)
    local archery = cat(catalog.bronze.weapons, 'Archery')
    table.insert(archery, { id = 22108, name = "Tokko Bow", cost = 12, jobs = 'WAR/RDM/THF/PLD/DRK/BST/RNG/SAM/NIN' })  -- WS score 177, DMG 136/Dly 360
    table.insert(archery, { id = 22110, name = "Eletta Bow", cost = 12, jobs = 'WAR/RDM/THF/PLD/DRK/BST/RNG/SAM/NIN' })  -- WS score 157, DMG 157/Dly 360

    -- Marksmanship: 3 pick(s)
    local marksmanship = cat(catalog.bronze.weapons, 'Marksmanship')
    table.insert(marksmanship, { id = 21274, name = "Donar Gun", cost = 12, jobs = 'THF/RNG/NIN/COR' })  -- WS score 172, DMG 103/Dly 548
    table.insert(marksmanship, { id = 21284, name = "Vanir Gun", cost = 12, jobs = 'RNG/COR' })  -- WS score 170, DMG 113/Dly 600
    table.insert(marksmanship, { id = 21479, name = "Tsoabichi Crossbow", cost = 12, jobs = 'WAR/THF/DRK/RNG' })  -- WS score 156, DMG 104/Dly 288

end

-----------------------------------
-- SILVER TIER
-----------------------------------
catalog.silver = { weapons = emptyCategories() }
do
    -- Hand-to-Hand: 1 pick(s)
    local h2h = cat(catalog.silver.weapons, 'Hand-to-Hand')
    table.insert(h2h, { id = 21529, name = "Premium Heart", cost = 25, jobs = 'MNK/PUP' })  -- WS score 206, DMG 172/Dly 576

    -- Daggers: 8 pick(s)
    local daggers = cat(catalog.silver.weapons, 'Daggers')
    table.insert(daggers, { id = 21588, name = "Mpu Gandring", cost = 25, jobs = 'RDM/THF/BRD/DNC' })  -- DPS score 240, DMG 124/Dly 176
    table.insert(daggers, { id = 21561, name = "Tokko Knife", cost = 25, jobs = 'RDM/THF/BST/BRD/RNG/NIN/COR/PUP/DNC' })  -- DPS score 239, DMG 97/Dly 180
    table.insert(daggers, { id = 20583, name = "Mandau 119 Iii", cost = 25, jobs = 'RDM/THF/BRD' })  -- DPS score 233, DMG 124/Dly 176
    table.insert(daggers, { id = 21569, name = "Chocobo Knife", cost = 25, jobs = 'RDM/THF/BRD/RNG/DNC' })  -- DPS score 218, DMG 121/Dly 176
    table.insert(daggers, { id = 21570, name = "Air Knife", cost = 25, jobs = 'THF/DNC' })  -- DPS score 217, DMG 103/Dly 150
    table.insert(daggers, { id = 21568, name = "Acrontica", cost = 25, jobs = 'THF/DNC' })  -- DPS score 214, DMG 138/Dly 201
    table.insert(daggers, { id = 20615, name = "Levante Dagger", cost = 25, jobs = 'WAR/BLM/RDM/THF/PLD/DRK/BST/BRD/RNG/SAM/NIN/DRG/SMN/SCH/GEO' })  -- DPS score 212, DMG 95/Dly 183
    table.insert(daggers, { id = 21566, name = "Voluspa Knife", cost = 25, jobs = 'WAR/THF/PLD/DRK/BRD/RNG/SAM/NIN/DRG/COR/PUP/DNC' })  -- DPS score 209, DMG 104/Dly 195

    -- Swords: 1 pick(s)
    local swords = cat(catalog.silver.weapons, 'Swords')
    table.insert(swords, { id = 21617, name = "Tokko Sword", cost = 25, jobs = 'WAR/RDM/THF/PLD/DRK/BST/BRD/RNG/NIN/DRG/BLU/COR/RUN' })  -- DPS score 220, DMG 130/Dly 240

    -- Great Swords: 5 pick(s)
    local greatswords = cat(catalog.silver.weapons, 'Great Swords')
    table.insert(greatswords, { id = 21670, name = "Tokko Claymore", cost = 25, jobs = 'WAR/PLD/DRK/RUN' })  -- WS score 246, DMG 260/Dly 480
    table.insert(greatswords, { id = 21665, name = "Voluspa Blade", cost = 25, jobs = 'PLD/RUN' })  -- WS score 227, DMG 260/Dly 480
    table.insert(greatswords, { id = 20745, name = "Ragnarok 119", cost = 25, jobs = 'WAR/PLD/DRK' })  -- WS score 226, DMG 224/Dly 431
    table.insert(greatswords, { id = 20746, name = "Ragnarok 119 Ii", cost = 25, jobs = 'WAR/PLD/DRK' })  -- WS score 226, DMG 224/Dly 431
    table.insert(greatswords, { id = 21672, name = "Eletta Claymore", cost = 25, jobs = 'WAR/PLD/DRK/RUN' })  -- WS score 222, DMG 293/Dly 480

    -- Great Axes: 1 pick(s)
    local greataxes = cat(catalog.silver.weapons, 'Great Axes')
    table.insert(greataxes, { id = 21769, name = "Voluspa Chopper", cost = 25, jobs = 'WAR/DRK/RUN' })  -- WS score 232, DMG 273/Dly 504

    -- Scythes: 2 pick(s)
    local scythes = cat(catalog.silver.weapons, 'Scythes')
    table.insert(scythes, { id = 21826, name = "Tokko Scythe", cost = 25, jobs = 'WAR/BLM/DRK/BST' })  -- WS score 212, DMG 286/Dly 528
    table.insert(scythes, { id = 20893, name = "Shukuyus Scythe", cost = 25, jobs = 'WAR/DRK/BST' })  -- WS score 204, DMG 288/Dly 480

    -- Katana: 0 pick(s) + 1 manual
    local katana = cat(catalog.silver.weapons, 'Katana')
    table.insert(katana, { id = 21915, name = "Koga Shinobi-Gatana", cost = 25, jobs = 'NIN' })  -- MANUAL, DMG 152/Dly 227

    -- Archery: 4 pick(s)
    local archery = cat(catalog.silver.weapons, 'Archery')
    table.insert(archery, { id = 21228, name = "Falubeza", cost = 25, jobs = 'RNG' })  -- WS score 243, DMG 243/Dly 540
    table.insert(archery, { id = 22118, name = "Venery Bow", cost = 25, jobs = 'RNG' })  -- WS score 243, DMG 243/Dly 600
    table.insert(archery, { id = 22133, name = "Voluspa Bow", cost = 25, jobs = 'RNG' })  -- WS score 238, DMG 204/Dly 540
    table.insert(archery, { id = 22111, name = "Kaja Bow", cost = 25, jobs = 'WAR/RDM/THF/PLD/DRK/BST/RNG/SAM/NIN' })  -- WS score 219, DMG 164/Dly 360

    -- Marksmanship: 3 pick(s)
    local marksmanship = cat(catalog.silver.weapons, 'Marksmanship')
    table.insert(marksmanship, { id = 22144, name = "Voluspa Gun", cost = 25, jobs = 'RNG/COR' })  -- WS score 204, DMG 113/Dly 600
    table.insert(marksmanship, { id = 22119, name = "Wochowsen", cost = 25, jobs = 'RNG' })  -- WS score 202, DMG 135/Dly 288
    table.insert(marksmanship, { id = 21256, name = "Illapa", cost = 25, jobs = 'RNG' })  -- WS score 202, DMG 135/Dly 432

end

-----------------------------------
-- GOLD TIER
-----------------------------------
catalog.gold = { weapons = emptyCategories() }
do
    -- Hand-to-Hand: 1 pick(s)
    local h2h = cat(catalog.gold.weapons, 'Hand-to-Hand')
    table.insert(h2h, { id = 21533, name = "Varga Purnikawa", cost = 50, jobs = 'MNK/PUP' })  -- WS score 254, DMG 192/Dly 596

    -- Daggers: 1 pick(s)
    local daggers = cat(catalog.gold.weapons, 'Daggers')
    table.insert(daggers, { id = 20632, name = "Vanir Knife", cost = 50, jobs = 'WAR/RDM/THF/BST/BRD/RNG/NIN/COR/DNC' })  -- CASTER score 295, DMG 111/Dly 205

    -- Swords: 7 pick(s)
    local swords = cat(catalog.gold.weapons, 'Swords')
    table.insert(swords, { id = 20689, name = "Almace", cost = 50, jobs = 'RDM/PLD/BLU' })  -- CASTER score 744, DMG 158/Dly 224
    table.insert(swords, { id = 20677, name = "Colada", cost = 50, jobs = 'RDM/PLD/BLU' })  -- CASTER score 572, DMG 140/Dly 240
    table.insert(swords, { id = 20706, name = "Vampirism", cost = 50, jobs = 'WAR/RDM/THF/PLD/DRK/BRD/RNG/NIN/DRG/BLU/RUN' })  -- CASTER score 534, DMG 127/Dly 240
    table.insert(swords, { id = 20698, name = "Fettering Blade", cost = 50, jobs = 'WAR/RDM/PLD/DRK/COR/RUN' })  -- CASTER score 516, DMG 134/Dly 231
    table.insert(swords, { id = 20715, name = "Acclimator", cost = 50, jobs = 'RDM/PLD/BLU' })  -- CASTER score 414, DMG 130/Dly 240
    table.insert(swords, { id = 20717, name = "Arendsi Fleuret", cost = 50, jobs = 'WAR/RDM/PLD/BRD/DRG/COR/DNC' })  -- CASTER score 397, DMG 119/Dly 224
    table.insert(swords, { id = 20733, name = "Anahera Saber", cost = 50, jobs = 'RDM/BLU' })  -- CASTER score 372, DMG 130/Dly 240

    -- Axes: 0 pick(s) + 3 manual
    local axes = cat(catalog.gold.weapons, 'Axes')
    table.insert(axes, { id = 21722, name = "Dolichenus", cost = 50, jobs = 'WAR/DRK/BST/RNG/RUN' })  -- MANUAL, DMG 200/Dly 288
    table.insert(axes, { id = 21730, name = "Spalirisos", cost = 50, jobs = 'BST' })  -- MANUAL, DMG 250/Dly 280
    table.insert(axes, { id = 21751, name = "Aymur", cost = 50, jobs = 'BST' })  -- MANUAL, DMG 195/Dly 312

    -- Katana: 0 pick(s) + 1 manual
    local katana = cat(catalog.gold.weapons, 'Katana')
    table.insert(katana, { id = 21936, name = "Yagyu Darkblade", cost = 50, jobs = 'NIN' })  -- MANUAL, DMG 173/Dly 227

    -- Clubs: 8 pick(s)
    local clubs = cat(catalog.gold.weapons, 'Clubs')
    table.insert(clubs, { id = 22029, name = "Eletta Rod", cost = 50, jobs = 'WHM/BLM/RDM/SMN/BLU/SCH/GEO' })  -- CASTER score 905, DMG 176/Dly 288
    table.insert(clubs, { id = 21089, name = "Rubicundity", cost = 50, jobs = 'WHM/BLM/RDM/SMN/SCH/GEO' })  -- CASTER score 632, DMG 160/Dly 288
    table.insert(clubs, { id = 21116, name = "Cagliostros Rod", cost = 50, jobs = 'WHM/BLM/SMN/SCH/GEO' })  -- CASTER score 602, DMG 156/Dly 288
    table.insert(clubs, { id = 21103, name = "Vadose Rod", cost = 50, jobs = 'WHM/BLM/SMN/SCH/GEO' })  -- CASTER score 577, DMG 156/Dly 288
    table.insert(clubs, { id = 21122, name = "Mesyohi Rod", cost = 50, jobs = 'WHM/BLM/SMN/SCH/GEO' })  -- CASTER score 572, DMG 125/Dly 288
    table.insert(clubs, { id = 21112, name = "Gabaxorea", cost = 50, jobs = 'WHM/BLM/RDM/SMN/BLU/SCH/GEO' })  -- CASTER score 565, DMG 112/Dly 216
    table.insert(clubs, { id = 22027, name = "Tokko Rod", cost = 50, jobs = 'WHM/BLM/RDM/SMN/BLU/SCH/GEO' })  -- CASTER score 499, DMG 156/Dly 288
    table.insert(clubs, { id = 21102, name = "Mafic Cudgel", cost = 50, jobs = 'WAR/MNK/WHM/BLM/RDM/THF/PLD/DRK/BST/BRD/RNG/SAM/NIN/DRG/SMN/BLU/COR/PUP/DNC/SCH/GEO/RUN' })  -- DPS score 262, DMG 142/Dly 278

    -- Staves: 8 pick(s)
    local staves = cat(catalog.gold.weapons, 'Staves')
    table.insert(staves, { id = 22057, name = "Contemplator", cost = 50, jobs = 'WHM/BLM/RDM/BRD/SMN/SCH/GEO' })  -- CASTER score 1000, DMG 231/Dly 402
    table.insert(staves, { id = 21152, name = "Reikikon", cost = 50, jobs = 'MNK/WHM/BLM/PLD/DRG/SMN/SCH/GEO' })  -- CASTER score 986, DMG 242/Dly 402
    table.insert(staves, { id = 22054, name = "Grioavolr", cost = 50, jobs = 'WHM/BLM/RDM/BRD/SMN/SCH/GEO' })  -- CASTER score 983, DMG 202/Dly 366
    table.insert(staves, { id = 21181, name = "Venabulum", cost = 50, jobs = 'WHM/BLM/RDM/BRD/SMN/SCH/GEO' })  -- CASTER score 938, DMG 198/Dly 366
    table.insert(staves, { id = 21161, name = "Mindmelter", cost = 50, jobs = 'BLM/SCH/GEO' })  -- CASTER score 920, DMG 223/Dly 412
    table.insert(staves, { id = 22064, name = "Hvergelmir", cost = 50, jobs = 'BLM/SMN/SCH' })  -- CASTER score 870, DMG 275/Dly 390
    table.insert(staves, { id = 22056, name = "Gozuki Mezuki", cost = 50, jobs = 'WAR/MNK/WHM/BLM/RDM/THF/PLD/DRK/BST/BRD/RNG/SAM/NIN/DRG/SMN/BLU/COR/PUP/DNC/SCH/GEO/RUN' })  -- WS score 302, DMG 266/Dly 412
    table.insert(staves, { id = 22087, name = "Malignance Pole", cost = 50, jobs = 'MNK/WHM/BLM/PLD/DRG/SMN/SCH/GEO' })  -- TANK score 275, DMG 286/Dly 412

    -- Archery: 3 pick(s)
    local archery = cat(catalog.gold.weapons, 'Archery')
    table.insert(archery, { id = 21227, name = "Hangaku-No-Yumi", cost = 50, jobs = 'RNG/SAM' })  -- WS score 271, DMG 251/Dly 600
    table.insert(archery, { id = 21229, name = "Cibitshavore", cost = 50, jobs = 'RNG/SAM' })  -- WS score 266, DMG 261/Dly 600
    table.insert(archery, { id = 22107, name = "Ullr", cost = 50, jobs = 'WAR/RDM/THF/PLD/DRK/BST/RNG/SAM/NIN' })  -- WS score 260, DMG 178/Dly 360

    -- Marksmanship: 2 pick(s)
    local marksmanship = cat(catalog.gold.weapons, 'Marksmanship')
    table.insert(marksmanship, { id = 22120, name = "Imati", cost = 50, jobs = 'RNG' })  -- WS score 300, DMG 145/Dly 432
    table.insert(marksmanship, { id = 22143, name = "Fomalhaut", cost = 50, jobs = 'RNG/COR' })  -- WS score 270, DMG 167/Dly 600

end

-----------------------------------
-- INFAMY TIER  (top-5-per-category; promoted to the Dungeon Infamy
--   Vendor by tools/build_infamy_top_picks.py. Inert here: the
--   Weapons NPC only sells bronze/silver/gold.)
-----------------------------------
catalog.infamy = { weapons = emptyCategories() }
do
    -- Hand-to-Hand: 5 pick(s) -> Infamy Vendor
    local inf_h2h = cat(catalog.infamy.weapons, 'Hand-to-Hand')
    table.insert(inf_h2h, { id = 21535, name = "Varga Purnikawa", cost = 500, jobs = 'MNK/PUP' })  -- WS score 329, DMG 213/Dly 596
    table.insert(inf_h2h, { id = 21519, name = "Karambit", cost = 500, jobs = 'WAR/MNK/RDM/THF/DRK/BST/NIN/PUP/DNC' })  -- WS score 275, DMG 180/Dly 576
    table.insert(inf_h2h, { id = 21527, name = "Sakpatas Fists", cost = 500, jobs = 'MNK/PUP' })  -- DPS score 275, DMG 165/Dly 576
    table.insert(inf_h2h, { id = 21518, name = "Kaja Knuckles", cost = 500, jobs = 'WAR/MNK/RDM/THF/DRK/BST/NIN/PUP/DNC' })  -- WS score 232, DMG 165/Dly 576
    table.insert(inf_h2h, { id = 21528, name = "Dragon Fangs", cost = 500, jobs = 'MNK/PUP' })  -- WS score 214, DMG 188/Dly 606

    -- Daggers: 5 pick(s) -> Infamy Vendor
    local inf_daggers = cat(catalog.infamy.weapons, 'Daggers')
    table.insert(inf_daggers, { id = 21565, name = "Tauret", cost = 500, jobs = 'RDM/THF/BST/BRD/RNG/NIN/COR/PUP/DNC' })  -- CASTER score 973, DMG 125/Dly 180
    table.insert(inf_daggers, { id = 21564, name = "Kaja Knife", cost = 500, jobs = 'RDM/THF/BST/BRD/RNG/NIN/COR/PUP/DNC' })  -- CASTER score 939, DMG 117/Dly 180
    table.insert(inf_daggers, { id = 21563, name = "Eletta Knife", cost = 500, jobs = 'RDM/THF/BST/BRD/RNG/NIN/COR/PUP/DNC' })  -- CASTER score 890, DMG 110/Dly 180
    table.insert(inf_daggers, { id = 21567, name = "Gletis Knife", cost = 500, jobs = 'RDM/THF/BRD/RNG/NIN/COR/DNC' })  -- DPS score 326, DMG 133/Dly 200
    table.insert(inf_daggers, { id = 21590, name = "Mpu Gandring", cost = 500, jobs = 'RDM/THF/BRD/DNC' })  -- DPS score 322, DMG 137/Dly 176

    -- Swords: 5 pick(s) -> Infamy Vendor
    local inf_swords = cat(catalog.infamy.weapons, 'Swords')
    table.insert(inf_swords, { id = 20672, name = "Ice Brand", cost = 500, jobs = 'RDM/PLD/BLU' })  -- CASTER score 1060, DMG 187/Dly 264
    table.insert(inf_swords, { id = 21637, name = "Sakpatas Sword", cost = 500, jobs = 'RDM/PLD/BLU' })  -- CASTER score 977, DMG 160/Dly 240
    table.insert(inf_swords, { id = 21620, name = "Kaja Sword", cost = 500, jobs = 'WAR/RDM/THF/PLD/DRK/BST/BRD/RNG/NIN/DRG/BLU/COR/RUN' })  -- CASTER score 939, DMG 156/Dly 240
    table.insert(inf_swords, { id = 21646, name = "Caliburnus", cost = 500, jobs = 'RDM/PLD/BLU' })  -- CASTER score 935, DMG 181/Dly 233
    table.insert(inf_swords, { id = 21619, name = "Eletta Sword", cost = 500, jobs = 'WAR/RDM/THF/PLD/DRK/BST/BRD/RNG/NIN/DRG/BLU/COR/RUN' })  -- CASTER score 920, DMG 146/Dly 240

    -- Great Swords: 5 pick(s) -> Infamy Vendor
    local inf_greatswords = cat(catalog.infamy.weapons, 'Great Swords')
    table.insert(inf_greatswords, { id = 21674, name = "Nandaka", cost = 500, jobs = 'WAR/PLD/DRK/RUN' })  -- WS score 312, DMG 333/Dly 480
    table.insert(inf_greatswords, { id = 21683, name = "Ragnarok 119 Iii", cost = 500, jobs = 'WAR/PLD/DRK' })  -- WS score 296, DMG 304/Dly 431
    table.insert(inf_greatswords, { id = 21673, name = "Kaja Claymore", cost = 500, jobs = 'WAR/PLD/DRK/RUN' })  -- WS score 276, DMG 313/Dly 480
    table.insert(inf_greatswords, { id = 21653, name = "Helheim", cost = 500, jobs = 'WAR/PLD/DRK/RUN' })  -- WS score 264, DMG 318/Dly 431
    table.insert(inf_greatswords, { id = 21663, name = "Raetic Algol +1", cost = 500, jobs = 'WAR/PLD/DRK/RUN' })  -- WS score 256, DMG 327/Dly 474

    -- Axes: 5 pick(s) -> Infamy Vendor
    local inf_axes = cat(catalog.infamy.weapons, 'Axes')
    table.insert(inf_axes, { id = 21707, name = "Barbarity +1", cost = 500, jobs = 'WAR/BST' })  -- WS score 250, DMG 189/Dly 280
    table.insert(inf_axes, { id = 21722, name = "Dolichenus", cost = 500, jobs = 'WAR/DRK/BST/RNG/RUN' })  -- WS score 235, DMG 200/Dly 288
    table.insert(inf_axes, { id = 21721, name = "Kaja Axe", cost = 500, jobs = 'WAR/DRK/BST/RNG/RUN' })  -- WS score 204, DMG 188/Dly 288
    table.insert(inf_axes, { id = 21718, name = "Tokko Axe", cost = 500, jobs = 'WAR/DRK/BST/RNG/RUN' })  -- DPS score 204, DMG 156/Dly 288
    table.insert(inf_axes, { id = 21712, name = "Voluspa Axe", cost = 500, jobs = 'WAR/DRK/BST/RUN' })  -- WS score 185, DMG 169/Dly 312

    -- Great Axes: 5 pick(s) -> Infamy Vendor
    local inf_greataxes = cat(catalog.infamy.weapons, 'Great Axes')
    table.insert(inf_greataxes, { id = 21779, name = "Lycurgos", cost = 500, jobs = 'WAR/DRK/RUN' })  -- WS score 364, DMG 359/Dly 508
    table.insert(inf_greataxes, { id = 21778, name = "Kaja Chopper", cost = 500, jobs = 'WAR/DRK/RUN' })  -- WS score 319, DMG 338/Dly 508
    table.insert(inf_greataxes, { id = 21766, name = "Hepatizon Axe +1", cost = 500, jobs = 'WAR/DRK/RUN' })  -- WS score 273, DMG 330/Dly 489
    table.insert(inf_greataxes, { id = 21768, name = "Raetic Chopper +1", cost = 500, jobs = 'WAR/BLM/DRK/BRD/SMN/SCH/RUN' })  -- WS score 262, DMG 337/Dly 489
    table.insert(inf_greataxes, { id = 21775, name = "Tokko Chopper", cost = 500, jobs = 'WAR/DRK/RUN' })  -- WS score 252, DMG 275/Dly 508

    -- Scythes: 5 pick(s) -> Infamy Vendor
    local inf_scythes = cat(catalog.infamy.weapons, 'Scythes')
    table.insert(inf_scythes, { id = 21830, name = "Drepanum", cost = 500, jobs = 'WAR/BLM/DRK/BST' })  -- CASTER score 1003, DMG 366/Dly 528
    table.insert(inf_scythes, { id = 21829, name = "Kaja Scythe", cost = 500, jobs = 'WAR/BLM/DRK/BST' })  -- CASTER score 969, DMG 344/Dly 528
    table.insert(inf_scythes, { id = 21828, name = "Eletta Scythe", cost = 500, jobs = 'WAR/BLM/DRK/BST' })  -- CASTER score 890, DMG 322/Dly 528
    table.insert(inf_scythes, { id = 21816, name = "Maliya Sickle +1", cost = 500, jobs = 'WAR/BLM/DRK/BST' })  -- WS score 272, DMG 328/Dly 490
    table.insert(inf_scythes, { id = 21819, name = "Raetic Scythe +1", cost = 500, jobs = 'WAR/BLM/DRK/BST' })  -- WS score 270, DMG 353/Dly 513

    -- Polearms: 5 pick(s) -> Infamy Vendor
    local inf_polearms = cat(catalog.infamy.weapons, 'Polearms')
    table.insert(inf_polearms, { id = 21883, name = "Shining One", cost = 500, jobs = 'WAR/PLD/SAM/DRG' })  -- WS score 312, DMG 333/Dly 480
    table.insert(inf_polearms, { id = 21870, name = "Exalted Spear +1", cost = 500, jobs = 'WAR/PLD/SAM/DRG' })  -- WS score 278, DMG 259/Dly 385
    table.insert(inf_polearms, { id = 21882, name = "Kaja Lance", cost = 500, jobs = 'WAR/PLD/SAM/DRG' })  -- WS score 276, DMG 313/Dly 480
    table.insert(inf_polearms, { id = 21879, name = "Tokko Lance", cost = 500, jobs = 'WAR/PLD/SAM/DRG' })  -- WS score 262, DMG 260/Dly 480
    table.insert(inf_polearms, { id = 21872, name = "Raetic Halberd +1", cost = 500, jobs = 'WAR/BLM/PLD/BRD/SAM/DRG/SMN/SCH' })  -- WS score 226, DMG 265/Dly 385

    -- Great Katana: 5 pick(s) -> Infamy Vendor
    local inf_gkatana = cat(catalog.infamy.weapons, 'Great Katana')
    table.insert(inf_gkatana, { id = 21975, name = "Hachimonji", cost = 500, jobs = 'SAM/NIN' })  -- WS score 344, DMG 318/Dly 450
    table.insert(inf_gkatana, { id = 21974, name = "Kaja Tachi", cost = 500, jobs = 'SAM/NIN' })  -- WS score 300, DMG 300/Dly 450
    table.insert(inf_gkatana, { id = 21964, name = "Beryllium Tachi +1", cost = 500, jobs = 'SAM/NIN' })  -- WS score 286, DMG 275/Dly 407
    table.insert(inf_gkatana, { id = 21971, name = "Tokko Tachi", cost = 500, jobs = 'SAM/NIN' })  -- WS score 255, DMG 243/Dly 450
    table.insert(inf_gkatana, { id = 21973, name = "Eletta Tachi", cost = 500, jobs = 'SAM/NIN' })  -- WS score 216, DMG 281/Dly 450

    -- Clubs: 5 pick(s) -> Infamy Vendor
    local inf_clubs = cat(catalog.infamy.weapons, 'Clubs')
    table.insert(inf_clubs, { id = 22002, name = "Lorg Mor", cost = 500, jobs = 'WHM/GEO' })  -- CASTER score 1061, DMG 227/Dly 308
    table.insert(inf_clubs, { id = 22042, name = "Wizards Rod", cost = 500, jobs = 'BLM/RDM/SCH/GEO' })  -- CASTER score 1060, DMG 149/Dly 216
    table.insert(inf_clubs, { id = 22040, name = "Daybreak", cost = 500, jobs = 'WHM/BLM/RDM/BRD/SMN/SCH/GEO' })  -- CASTER score 1033, DMG 150/Dly 216
    table.insert(inf_clubs, { id = 21071, name = "Cath Palug Hammer", cost = 500, jobs = 'WHM/GEO' })  -- CASTER score 1013, DMG 212/Dly 300
    table.insert(inf_clubs, { id = 22031, name = "Maxentius", cost = 500, jobs = 'WHM/BLM/RDM/SMN/BLU/SCH/GEO' })  -- CASTER score 988, DMG 200/Dly 288

    -- Staves: 5 pick(s) -> Infamy Vendor
    local inf_staves = cat(catalog.infamy.weapons, 'Staves')
    table.insert(inf_staves, { id = 22106, name = "Opashoro", cost = 500, jobs = 'BLM/SMN/SCH' })  -- CASTER score 1215, DMG 304/Dly 390
    table.insert(inf_staves, { id = 22055, name = "Oranyan", cost = 500, jobs = 'WHM/BLM/RDM/BRD/SMN/SCH/GEO' })  -- CASTER score 1054, DMG 230/Dly 366
    table.insert(inf_staves, { id = 22081, name = "Raetic Staff +1", cost = 500, jobs = 'WAR/MNK/WHM/BLM/RDM/BST/BRD/SMN/SCH/GEO' })  -- CASTER score 1019, DMG 245/Dly 356
    table.insert(inf_staves, { id = 22086, name = "Xoanon", cost = 500, jobs = 'WAR/MNK/WHM/BLM/RDM/BST/BRD/SMN/SCH/GEO' })  -- CASTER score 1018, DMG 254/Dly 366
    table.insert(inf_staves, { id = 22058, name = "Contemplator +1", cost = 500, jobs = 'WHM/BLM/RDM/BRD/SMN/SCH/GEO' })  -- CASTER score 1004, DMG 232/Dly 390

    -- Archery: 5 pick(s) -> Infamy Vendor
    local inf_archery = cat(catalog.infamy.weapons, 'Archery')
    table.insert(inf_archery, { id = 22114, name = "Steinthor", cost = 500, jobs = 'RNG' })  -- WS score 346, DMG 290/Dly 600
    table.insert(inf_archery, { id = 21221, name = "Brahmastra", cost = 500, jobs = 'RNG' })  -- WS score 326, DMG 261/Dly 600
    table.insert(inf_archery, { id = 22113, name = "Teller", cost = 500, jobs = 'RNG' })  -- WS score 322, DMG 270/Dly 600
    table.insert(inf_archery, { id = 22123, name = "Arasy Bow +1", cost = 500, jobs = 'RNG' })  -- WS score 295, DMG 227/Dly 524
    table.insert(inf_archery, { id = 21220, name = "Paloma Bow +1", cost = 500, jobs = 'RNG' })  -- WS score 272, DMG 220/Dly 480

    -- Marksmanship: 5 pick(s) -> Infamy Vendor
    local inf_marksmanship = cat(catalog.infamy.weapons, 'Marksmanship')
    table.insert(inf_marksmanship, { id = 22164, name = "Earp", cost = 500, jobs = 'RNG/COR' })  -- WS score 448, DMG 162/Dly 582
    table.insert(inf_marksmanship, { id = 22121, name = "Imati +1", cost = 500, jobs = 'RNG' })  -- WS score 307, DMG 146/Dly 424
    table.insert(inf_marksmanship, { id = 21485, name = "Fomalhaut", cost = 500, jobs = 'RNG/COR' })  -- WS score 270, DMG 167/Dly 600
    table.insert(inf_marksmanship, { id = 22136, name = "Arasy Gun +1", cost = 500, jobs = 'RNG/COR' })  -- WS score 252, DMG 108/Dly 582
    table.insert(inf_marksmanship, { id = 19209, name = "Molybdosis", cost = 500, jobs = 'COR' })  -- WS score 222, DMG 103/Dly 480

end
return catalog
