-----------------------------------
-- hades_armor_catalog.lua
--
-- Weekend Mail stalls. Two pieces per UTC week, same names for
-- every player. Generated by tools/gen_hades_armor_pool.ps1
-- from exports/gear_source_audit.csv.
--
-- sourced = has a retail or curated relaunch source.
-- Invasion-only pieces are unsourced and cost 1499.
-- Sourced pieces cost 499-999 from +tier and score.
-- Omen Caturae bodies stay sourced but cost OMEN_BODY_PRICE: Invasion is
-- retired, Omen is not a live farm, and those bodies are 1% even when it is.
-----------------------------------
local CATALOG_KEY = 'modules/custom/lua/hades_armor_catalog'
local C = package.loaded[CATALOG_KEY]
if type(C) ~= 'table' then
    C = {}
end
package.loaded[CATALOG_KEY] = C

C.UNSOURCED_PRICE = 1499
C.SOURCED_LO      = 499
C.SOURCED_HI      = 999
C.OMEN_BODY_PRICE = 949

C.items =
{
    { id = 23461, name = 'Maxixi Casaque +3', slot = 'Body', sourced = false, price = 1499 },
    { id = 23733, name = 'Malignance Tabard', slot = 'Body', sourced = true, price = 551 },
    { id = 23734, name = 'Malignance Gloves', slot = 'Hands', sourced = true, price = 547 },
    { id = 23735, name = 'Malignance Tights', slot = 'Legs', sourced = true, price = 542 },
    { id = 23736, name = 'Malignance Boots', slot = 'Feet', sourced = true, price = 544 },
    { id = 23744, name = 'Hervor Mouffles', slot = 'Hands', sourced = true, price = 529 },
    { id = 23745, name = 'Heidrek Gloves', slot = 'Hands', sourced = true, price = 529 },
    { id = 23747, name = 'Hervor Brayettes', slot = 'Legs', sourced = true, price = 530 },
    { id = 23748, name = 'Heidrek Brais', slot = 'Legs', sourced = true, price = 529 },
    { id = 23755, name = 'Ikengas Hat', slot = 'Head', sourced = false, price = 1499 },
    { id = 23756, name = 'Gletis Mask', slot = 'Head', sourced = false, price = 1499 },
    { id = 23757, name = 'Sakpatas Helm', slot = 'Head', sourced = false, price = 1499 },
    { id = 23758, name = 'Mpacas Cap', slot = 'Head', sourced = false, price = 1499 },
    { id = 23759, name = 'Agwus Cap', slot = 'Head', sourced = false, price = 1499 },
    { id = 23760, name = 'Bunzis Hat', slot = 'Head', sourced = false, price = 1499 },
    { id = 23761, name = 'Nyame Helm', slot = 'Head', sourced = false, price = 1499 },
    { id = 23762, name = 'Ikengas Vest', slot = 'Body', sourced = false, price = 1499 },
    { id = 23763, name = 'Gletis Cuirass', slot = 'Body', sourced = false, price = 1499 },
    { id = 23764, name = 'Sakpatas Breastplate', slot = 'Body', sourced = false, price = 1499 },
    { id = 23765, name = 'Mpacas Doublet', slot = 'Body', sourced = false, price = 1499 },
    { id = 23766, name = 'Agwus Robe', slot = 'Body', sourced = false, price = 1499 },
    { id = 23767, name = 'Bunzis Robe', slot = 'Body', sourced = false, price = 1499 },
    { id = 23768, name = 'Nyame Mail', slot = 'Body', sourced = false, price = 1499 },
    { id = 23769, name = 'Ikengas Gloves', slot = 'Hands', sourced = false, price = 1499 },
    { id = 23770, name = 'Gletis Gauntlets', slot = 'Hands', sourced = false, price = 1499 },
    { id = 23771, name = 'Sakpatas Gauntlets', slot = 'Hands', sourced = false, price = 1499 },
    { id = 23772, name = 'Mpacas Gloves', slot = 'Hands', sourced = false, price = 1499 },
    { id = 23773, name = 'Agwus Gages', slot = 'Hands', sourced = false, price = 1499 },
    { id = 23774, name = 'Bunzis Gloves', slot = 'Hands', sourced = false, price = 1499 },
    { id = 23775, name = 'Nyame Gauntlets', slot = 'Hands', sourced = false, price = 1499 },
    { id = 23776, name = 'Ikengas Trousers', slot = 'Legs', sourced = false, price = 1499 },
    { id = 23777, name = 'Gletis Breeches', slot = 'Legs', sourced = false, price = 1499 },
    { id = 23778, name = 'Sakpatas Cuisses', slot = 'Legs', sourced = false, price = 1499 },
    { id = 23779, name = 'Mpacas Hose', slot = 'Legs', sourced = false, price = 1499 },
    { id = 23780, name = 'Agwus Slops', slot = 'Legs', sourced = false, price = 1499 },
    { id = 23781, name = 'Bunzis Pants', slot = 'Legs', sourced = false, price = 1499 },
    { id = 23782, name = 'Nyame Flanchard', slot = 'Legs', sourced = false, price = 1499 },
    { id = 23783, name = 'Ikengas Clogs', slot = 'Feet', sourced = false, price = 1499 },
    { id = 23784, name = 'Gletis Boots', slot = 'Feet', sourced = false, price = 1499 },
    { id = 23785, name = 'Sakpatas Leggings', slot = 'Feet', sourced = false, price = 1499 },
    { id = 23786, name = 'Mpacas Boots', slot = 'Feet', sourced = false, price = 1499 },
    { id = 23787, name = 'Agwus Pigaches', slot = 'Feet', sourced = false, price = 1499 },
    { id = 23788, name = 'Bunzis Sabots', slot = 'Feet', sourced = false, price = 1499 },
    { id = 23789, name = 'Nyame Sollerets', slot = 'Feet', sourced = false, price = 1499 },
    { id = 23798, name = 'Crepuscular Mail', slot = 'Body', sourced = true, price = 557 },
    { id = 23958, name = 'Maxixi Casaque +4', slot = 'Body', sourced = false, price = 1499 },
    { id = 24003, name = 'Maxixi Bangles +4', slot = 'Hands', sourced = false, price = 1499 },
    { id = 24093, name = 'Maxixi Toe Shoes +4', slot = 'Feet', sourced = false, price = 1499 },
    { id = 24128, name = 'Revelation Gauntlets', slot = 'Hands', sourced = true, price = 552 },
    { id = 24131, name = 'Revelation Brais', slot = 'Legs', sourced = true, price = 554 },
    { id = 24166, name = 'Magnificent Crown', slot = 'Head', sourced = true, price = 551 },
    { id = 24178, name = 'Magnificent Sollerets', slot = 'Feet', sourced = true, price = 548 },
    { id = 24182, name = 'Clemency Somen', slot = 'Head', sourced = true, price = 553 },
    { id = 24188, name = 'Clemency Kote', slot = 'Hands', sourced = true, price = 553 },
    { id = 25552, name = 'Kendatsuba Jinpachi +1', slot = 'Head', sourced = true, price = 667 },
    { id = 25554, name = 'Ea Hat +1', slot = 'Head', sourced = true, price = 666 },
    { id = 25558, name = 'Arke Zuchetto +1', slot = 'Head', sourced = true, price = 668 },
    { id = 25563, name = 'Heyoka Cap', slot = 'Head', sourced = true, price = 534 },
    { id = 25564, name = 'Heyoka Cap +1', slot = 'Head', sourced = true, price = 661 },
    { id = 25568, name = 'Turms Cap +1', slot = 'Head', sourced = true, price = 669 },
    { id = 25569, name = 'Flamma Zucchetto +2', slot = 'Head', sourced = false, price = 1499 },
    { id = 25570, name = 'Mummu Bonnet +2', slot = 'Head', sourced = false, price = 1499 },
    { id = 25571, name = 'Mallquis Chapeau +2', slot = 'Head', sourced = false, price = 1499 },
    { id = 25572, name = 'Ayanmo Zucchetto +2', slot = 'Head', sourced = false, price = 1499 },
    { id = 25573, name = 'Taliah Turban +2', slot = 'Head', sourced = false, price = 1499 },
    { id = 25574, name = 'Sulevias Mask +2', slot = 'Head', sourced = false, price = 1499 },
    { id = 25575, name = 'Meghanada Visor +2', slot = 'Head', sourced = false, price = 1499 },
    { id = 25576, name = 'Hizamaru Somen +2', slot = 'Head', sourced = false, price = 1499 },
    { id = 25577, name = 'Inyanga Tiara +2', slot = 'Head', sourced = false, price = 1499 },
    { id = 25578, name = 'Jhakri Coronal +2', slot = 'Head', sourced = false, price = 1499 },
    { id = 25584, name = 'Mallquis Chapeau +1', slot = 'Head', sourced = false, price = 1499 },
    { id = 25592, name = 'Hjarrandi Helm', slot = 'Head', sourced = false, price = 1499 },
    { id = 25600, name = 'Maiitsoh Haube', slot = 'Head', sourced = true, price = 537 },
    { id = 25612, name = 'Ryuo Somen +1', slot = 'Head', sourced = true, price = 654 },
    { id = 25614, name = 'Adhemar Bonnet +1', slot = 'Head', sourced = true, price = 659 },
    { id = 25629, name = 'Genmei Kabuto', slot = 'Head', sourced = true, price = 547 },
    { id = 25636, name = 'Loess Barbuta +1', slot = 'Head', sourced = true, price = 658 },
    { id = 25640, name = 'Odyssean Helm', slot = 'Head', sourced = true, price = 535 },
    { id = 25681, name = 'Cohort Cloak +1', slot = 'Body', sourced = true, price = 677 },
    { id = 25685, name = 'Ryuo Domaru +1', slot = 'Body', sourced = true, price = 671 },
    { id = 25687, name = 'Adhemar Jacket +1', slot = 'Body', sourced = true, price = 668 },
    { id = 25702, name = 'Reiki Osode', slot = 'Body', sourced = true, price = 543 },
    { id = 25710, name = 'Obviation Cuirass +1', slot = 'Body', sourced = true, price = 674 },
    { id = 25748, name = 'Meghanada Cuirie +1', slot = 'Body', sourced = false, price = 1499 },
    { id = 25750, name = 'Hizamaru Haramaki +1', slot = 'Body', sourced = false, price = 1499 },
    { id = 25766, name = 'Hjarrandi Breastplate', slot = 'Body', sourced = false, price = 1499 },
    { id = 25783, name = 'Mallquis Saio', slot = 'Body', sourced = false, price = 1499 },
    { id = 25784, name = 'Mallquis Saio +1', slot = 'Body', sourced = false, price = 1499 },
    { id = 25785, name = 'Dagon Breastplate', slot = 'Body', sourced = true, price = 949 },
    { id = 25786, name = 'Ashera Harness', slot = 'Body', sourced = true, price = 949 },
    { id = 25787, name = 'Shamash Robe', slot = 'Body', sourced = true, price = 949 },
    { id = 25790, name = 'Sulevias Platemail +2', slot = 'Body', sourced = false, price = 1499 },
    { id = 25791, name = 'Meghanada Cuirie +2', slot = 'Body', sourced = false, price = 1499 },
    { id = 25792, name = 'Hizamaru Haramaki +2', slot = 'Body', sourced = false, price = 1499 },
    { id = 25793, name = 'Inyanga Jubbah +2', slot = 'Body', sourced = false, price = 1499 },
    { id = 25794, name = 'Jhakri Robe +2', slot = 'Body', sourced = false, price = 1499 },
    { id = 25795, name = 'Ayanmo Corazza +2', slot = 'Body', sourced = false, price = 1499 },
    { id = 25796, name = 'Taliah Manteel +2', slot = 'Body', sourced = false, price = 1499 },
    { id = 25797, name = 'Flamma Korazin +2', slot = 'Body', sourced = false, price = 1499 },
    { id = 25798, name = 'Mummu Jacket +2', slot = 'Body', sourced = false, price = 1499 },
    { id = 25799, name = 'Mallquis Saio +2', slot = 'Body', sourced = false, price = 1499 },
    { id = 25823, name = 'Mallquis Cuffs +1', slot = 'Hands', sourced = false, price = 1499 },
    { id = 25828, name = 'Sulevias Gauntlets +2', slot = 'Hands', sourced = false, price = 1499 },
    { id = 25829, name = 'Meghanada Gloves +2', slot = 'Hands', sourced = false, price = 1499 },
    { id = 25830, name = 'Hizamaru Kote +2', slot = 'Hands', sourced = false, price = 1499 },
    { id = 25831, name = 'Inyanga Dastanas +2', slot = 'Hands', sourced = false, price = 1499 },
    { id = 25832, name = 'Jhakri Cuffs +2', slot = 'Hands', sourced = false, price = 1499 },
    { id = 25833, name = 'Ayanmo Manopolas +2', slot = 'Hands', sourced = false, price = 1499 },
    { id = 25834, name = 'Taliah Gages +2', slot = 'Hands', sourced = false, price = 1499 },
    { id = 25835, name = 'Flamma Manopolas +2', slot = 'Hands', sourced = false, price = 1499 },
    { id = 25836, name = 'Mummu Wrists +2', slot = 'Hands', sourced = false, price = 1499 },
    { id = 25837, name = 'Mallquis Cuffs +2', slot = 'Hands', sourced = false, price = 1499 },
    { id = 25840, name = 'Odyssean Cuisses', slot = 'Legs', sourced = true, price = 531 },
    { id = 25841, name = 'Valorous Hose', slot = 'Legs', sourced = true, price = 533 },
    { id = 25843, name = 'Merlinic Shalwar', slot = 'Legs', sourced = true, price = 531 },
    { id = 25856, name = 'Tatenashi Haidate +1', slot = 'Legs', sourced = true, price = 654 },
    { id = 25877, name = 'Mallquis Trews', slot = 'Legs', sourced = false, price = 1499 },
    { id = 25878, name = 'Mallquis Trews +1', slot = 'Legs', sourced = false, price = 1499 },
    { id = 25879, name = 'Sulevias Cuisses +2', slot = 'Legs', sourced = false, price = 1499 },
    { id = 25880, name = 'Meghanada Chausses +2', slot = 'Legs', sourced = false, price = 1499 },
    { id = 25881, name = 'Hizamaru Hizayoroi +2', slot = 'Legs', sourced = false, price = 1499 },
    { id = 25882, name = 'Inyanga Shalwar +2', slot = 'Legs', sourced = false, price = 1499 },
    { id = 25883, name = 'Jhakri Slops +2', slot = 'Legs', sourced = false, price = 1499 },
    { id = 25884, name = 'Ayanmo Cosciales +2', slot = 'Legs', sourced = false, price = 1499 },
    { id = 25885, name = 'Taliah Seraweels +2', slot = 'Legs', sourced = false, price = 1499 },
    { id = 25886, name = 'Flamma Dirs +2', slot = 'Legs', sourced = false, price = 1499 },
    { id = 25887, name = 'Mummu Kecks +2', slot = 'Legs', sourced = false, price = 1499 },
    { id = 25888, name = 'Mallquis Trews +2', slot = 'Legs', sourced = false, price = 1499 },
    { id = 25892, name = 'Kendatsuba Hakama +1', slot = 'Legs', sourced = true, price = 664 },
    { id = 25894, name = 'Ea Slops +1', slot = 'Legs', sourced = true, price = 669 },
    { id = 25898, name = 'Arke Cosciales +1', slot = 'Legs', sourced = true, price = 672 },
    { id = 25908, name = 'Turms Subligar +1', slot = 'Legs', sourced = true, price = 673 },
    { id = 25922, name = 'Navon Crackows', slot = 'Feet', sourced = true, price = 526 },
    { id = 25945, name = 'Mallquis Clogs +1', slot = 'Feet', sourced = false, price = 1499 },
    { id = 25946, name = 'Sulevias Leggings +2', slot = 'Feet', sourced = false, price = 1499 },
    { id = 25947, name = 'Meghanada Jambeaux +2', slot = 'Feet', sourced = false, price = 1499 },
    { id = 25948, name = 'Hizamaru Sune-Ate +2', slot = 'Feet', sourced = false, price = 1499 },
    { id = 25949, name = 'Inyanga Crackows +2', slot = 'Feet', sourced = false, price = 1499 },
    { id = 25950, name = 'Jhakri Pigaches +2', slot = 'Feet', sourced = false, price = 1499 },
    { id = 25951, name = 'Ayanmo Gambieras +2', slot = 'Feet', sourced = false, price = 1499 },
    { id = 25952, name = 'Taliah Crackows +2', slot = 'Feet', sourced = false, price = 1499 },
    { id = 25953, name = 'Flamma Gambieras +2', slot = 'Feet', sourced = false, price = 1499 },
    { id = 25954, name = 'Mummu Gamashes +2', slot = 'Feet', sourced = false, price = 1499 },
    { id = 25955, name = 'Mallquis Clogs +2', slot = 'Feet', sourced = false, price = 1499 },
    { id = 25957, name = 'Oshosi Leggings +1', slot = 'Feet', sourced = true, price = 656 },
    { id = 25959, name = 'Kendatsuba Sune-Ate +1', slot = 'Feet', sourced = true, price = 668 },
    { id = 25971, name = 'Heyoka Leggings +1', slot = 'Feet', sourced = true, price = 664 },
    { id = 25981, name = 'Ea Cuffs +1', slot = 'Hands', sourced = true, price = 664 },
    { id = 25985, name = 'Arke Manopolas +1', slot = 'Hands', sourced = true, price = 664 },
    { id = 25995, name = 'Turms Mittens +1', slot = 'Hands', sourced = true, price = 666 },
    { id = 25997, name = 'Raetic Bangles +1', slot = 'Hands', sourced = true, price = 664 },
    { id = 26528, name = 'Kendatsuba Samue +1', slot = 'Body', sourced = true, price = 673 },
    { id = 26530, name = 'Ea Houppelande +1', slot = 'Body', sourced = true, price = 671 },
    { id = 26534, name = 'Arke Corazza +1', slot = 'Body', sourced = true, price = 678 },
    { id = 26540, name = 'Heyoka Harness +1', slot = 'Body', sourced = true, price = 672 },
    { id = 26544, name = 'Turms Harness +1', slot = 'Body', sourced = true, price = 679 },
    { id = 26671, name = 'Souveran Schaller +1', slot = 'Head', sourced = true, price = 672 },
    { id = 26673, name = 'Argosy Celata +1', slot = 'Head', sourced = true, price = 660 },
    { id = 26679, name = 'Carmine Mask +1', slot = 'Head', sourced = true, price = 658 },
    { id = 26702, name = 'Gavialis Helm', slot = 'Head', sourced = true, price = 530 },
    { id = 26721, name = 'Rabid Visor', slot = 'Head', sourced = true, price = 530 },
    { id = 26847, name = 'Souveran Cuirass +1', slot = 'Body', sourced = true, price = 672 },
    { id = 26871, name = 'Emet Harness +1', slot = 'Body', sourced = true, price = 671 },
    { id = 26882, name = 'Wildheitbrust', slot = 'Body', sourced = true, price = 542 },
    { id = 26947, name = 'Eschite Breastplate', slot = 'Body', sourced = true, price = 541 },
    { id = 26959, name = 'Kubira Meikogai', slot = 'Body', sourced = true, price = 549 },
    { id = 26963, name = 'Onca Suit', slot = 'Body', sourced = true, price = 599 },
    { id = 27023, name = 'Souveran Handschuhs +1', slot = 'Hands', sourced = true, price = 661 },
    { id = 27025, name = 'Argosy Mufflers +1', slot = 'Hands', sourced = true, price = 658 },
    { id = 27027, name = 'Rao Kote +1', slot = 'Hands', sourced = true, price = 653 },
    { id = 27045, name = 'Yorium Gauntlets', slot = 'Hands', sourced = true, price = 528 },
    { id = 27098, name = 'Despair Finger Gauntlets', slot = 'Hands', sourced = true, price = 527 },
    { id = 27118, name = 'Adhemar Wristbands +1', slot = 'Hands', sourced = true, price = 657 },
    { id = 27133, name = 'Kobo Kote', slot = 'Hands', sourced = true, price = 526 },
    { id = 27134, name = 'Kurys Gloves', slot = 'Hands', sourced = true, price = 530 },
    { id = 27138, name = 'Odyssean Gauntlets', slot = 'Hands', sourced = true, price = 527 },
    { id = 27140, name = 'Herculean Gloves', slot = 'Hands', sourced = true, price = 527 },
    { id = 27201, name = 'Argosy Breeches +1', slot = 'Legs', sourced = true, price = 655 },
    { id = 27203, name = 'Rao Haidate +1', slot = 'Legs', sourced = true, price = 659 },
    { id = 27207, name = 'Carmine Cuisses +1', slot = 'Legs', sourced = true, price = 664 },
    { id = 27227, name = 'Sombra Tights +1', slot = 'Legs', sourced = true, price = 654 },
    { id = 27283, name = 'Despair Cuisses', slot = 'Legs', sourced = true, price = 530 },
    { id = 27284, name = 'Naga Hakama', slot = 'Legs', sourced = true, price = 528 },
    { id = 27301, name = 'Ryuo Hakama +1', slot = 'Legs', sourced = true, price = 654 },
    { id = 27319, name = 'Obatala Subligar', slot = 'Legs', sourced = true, price = 529 },
    { id = 27375, name = 'Souveran Schuhs +1', slot = 'Feet', sourced = true, price = 661 },
    { id = 27377, name = 'Argosy Sollerets +1', slot = 'Feet', sourced = true, price = 655 },
    { id = 27379, name = 'Rao Sune-Ate +1', slot = 'Feet', sourced = true, price = 653 },
    { id = 27457, name = 'Eschite Greaves', slot = 'Feet', sourced = true, price = 528 },
    { id = 27472, name = 'Ryuo Sune-Ate +1', slot = 'Feet', sourced = true, price = 655 },
    { id = 27474, name = 'Adhemar Gamashes +1', slot = 'Feet', sourced = true, price = 656 },
    { id = 27495, name = 'Valorous Greaves', slot = 'Feet', sourced = true, price = 526 },
    { id = 27496, name = 'Herculean Boots', slot = 'Feet', sourced = true, price = 529 },
    { id = 27730, name = 'Iuitl Headgear +1', slot = 'Head', sourced = true, price = 656 },
    { id = 27731, name = 'Gendewitha Caubeen +1', slot = 'Head', sourced = true, price = 656 },
    { id = 27783, name = 'Skormoth Mask', slot = 'Head', sourced = true, price = 537 },
    { id = 27857, name = 'Respite Cloak', slot = 'Body', sourced = true, price = 555 },
    { id = 27994, name = 'Macabre Gauntlets +1', slot = 'Hands', sourced = true, price = 660 },
    { id = 28142, name = 'Brontes Cuisses', slot = 'Legs', sourced = true, price = 534 },
    { id = 28152, name = 'Gorney Brayettes +1', slot = 'Legs', sourced = true, price = 655 },
}

C.byId = {}
for _, row in ipairs(C.items) do
    C.byId[row.id] = row
end

function C.weeklyPiece(weekId, slot)
    local n = #C.items
    if n == 0 then
        return nil
    end
    weekId = weekId or tonumber(os.date('!%Y%W'))
    slot   = slot or 1
    local idx = (((weekId or 0) * 29 + (slot - 1) * 17) % n) + 1
    local row = C.items[idx]
    if slot > 1 then
        local first = C.weeklyPiece(weekId, 1)
        if first and row and first.id == row.id then
            row = C.items[(idx % n) + 1]
        end
    end
    return row
end

return C
