#!/usr/bin/env python3
"""Generate the status=2 (DISAPPEAR) SQL that hides the audited 'extra' NPCs --
plus a matching rollback. Applies NOTHING; it only writes .sql files.

Reads the reviewed proposal (npc_disable_candidates.json: {folder: [npcid,...]})
and writes:
  sql/zz_npc_declutter.sql            UPDATE npc_list SET status = 2 ...  (hide)
  sql/zz_npc_declutter_ROLLBACK.sql   UPDATE npc_list SET status = 0 ...  (undo)

status=2 is reversible and the entity still LOADS -- verified in zoneutils.cpp:
the NPC loader filters by zone only, never by status -- so GetNPCByID references
can't nil-crash. The change only becomes visible after a map restart (NPCs load
at boot), so applying the SQL mid-session disturbs nobody until you restart.

Usage:
  python gen_disable_sql.py                 # FLAVOR bucket, all reviewed zones
  python gen_disable_sql.py Port_Windurst   # PILOT: FLAVOR, one zone only
  python gen_disable_sql.py --cutscene      # FLAVOR + CUTSCENE, all zones
  python gen_disable_sql.py --cutscene Port_Windurst   # both buckets, one zone

The CUTSCENE bucket is riskier (a few may be mission cutscene steps), so it's
opt-in -- the default is the conservative flavor-only set.
"""
import json
import sys
from pathlib import Path

ROOT         = Path(r"D:/server")
JSON         = ROOT / "tools" / "npc_audit" / "npc_disable_candidates.json"
JSON_CUT     = ROOT / "tools" / "npc_audit" / "npc_disable_candidates_cutscene.json"
OUT_DISABLE  = ROOT / "sql" / "zz_npc_declutter.sql"
OUT_ROLLBACK = ROOT / "sql" / "zz_npc_declutter_ROLLBACK.sql"

# Flags (any order) + an optional zone-folder positional.
args        = sys.argv[1:]
include_cut = ("--cutscene" in args) or ("--both" in args)
zone_args   = [a for a in args if not a.startswith("-")]
only        = zone_args[0] if zone_args else None

proposal: dict[str, list[int]] = json.loads(JSON.read_text(encoding="utf-8"))
if include_cut and JSON_CUT.exists():
    # Fold the riskier CUTSCENE bucket in on request (default = flavor only).
    for folder, ids in json.loads(JSON_CUT.read_text(encoding="utf-8")).items():
        proposal[folder] = sorted(set(proposal.get(folder, [])) | set(ids))

if only:
    if only not in proposal:
        sys.exit(f"zone folder '{only}' not in proposal. Example keys: "
                 + ", ".join(sorted(proposal)[:6]) + " ...")
    proposal = {only: proposal[only]}


def build(target_status: int, undo: bool) -> tuple[str, int]:
    """Render one .sql; returns (text, npc_count). `undo` flips the guard so the
    rollback only touches rows we actually hid (status = 2)."""
    suffix = "_ROLLBACK" if undo else ""
    verb   = "RESTORE (undo)" if undo else "HIDE (status=2 DISAPPEAR)"
    guard  = "= 2" if undo else "<> 2"   # undo: only re-show what we hid
    out = [
        "-- ============================================================",
        f"-- zz_npc_declutter{suffix}.sql  --  {verb}",
        "-- GENERATED by tools/npc_audit/gen_disable_sql.py from the reviewed",
        "-- npc_disable_candidates.json.  status=2 hides, status=0 restores.",
        "-- Entity still LOADS either way (loader filters by zone only), so",
        "-- GetNPCByID refs are safe.  Takes effect on the next map restart.",
        "-- ============================================================",
        "",
    ]
    total = 0
    for folder in sorted(proposal):
        ids = sorted(set(proposal[folder]))
        if not ids:
            continue
        total += len(ids)
        out.append(f"-- {folder.replace('_', ' ')}  ({len(ids)} NPC(s))")
        out.append(f"UPDATE npc_list SET status = {target_status} "
                   f"WHERE status {guard} AND npcid IN ({', '.join(map(str, ids))});")
        out.append("")
    return "\n".join(out) + "\n", total


dis_text, n = build(2, undo=False)
rb_text, _  = build(0, undo=True)
OUT_DISABLE.write_text(dis_text, encoding="utf-8")
OUT_ROLLBACK.write_text(rb_text, encoding="utf-8")

scope = f"zone '{only}'" if only else f"{len(proposal)} zone(s)"
print(f"HIDE  -> {OUT_DISABLE}  ({n} NPCs, {scope})")
print(f"UNDO  -> {OUT_ROLLBACK}")
print()
print("Apply on the box during a quiet window:")
print("  sudo mariadb xidb < sql/zz_npc_declutter.sql")
print("  sudo systemctl restart xi_map        # NPCs load at boot")
print("Undo:")
print("  sudo mariadb xidb < sql/zz_npc_declutter_ROLLBACK.sql ; sudo systemctl restart xi_map")
