-- GENERATED by tools/unity_ranking_latents.py -- do not hand-edit; rerun the script.
-- Relaunch: retail "Unity Ranking: X+a~b" lines on Unity Wanted rewards, granted at their
-- MAXIMUM value, always on, no Unity pledge needed (owner decision 2026-09-11).
-- Latent 51 = JOB_LEVEL_ABOVE with param 1 -> active from level 1, i.e. unconditional.

DELETE FROM `item_latents`
 WHERE `latentId` = 51 AND `latentParam` = 1
   AND `itemId` IN (10768, 10769, 10770, 10771, 20507, 20508, 20521, 20522, 20527, 20528, 20580, 20581, 20603, 20604, 20606, 20607, 20611, 20612, 20613, 20614, 20679, 20680, 20681, 20682, 20696, 20697, 20708, 20709, 20799, 20800, 20804, 20805, 20806, 20807, 20851, 20852, 20853, 20854, 20898, 20899, 20942, 20943, 20980, 20981, 20987, 20988, 21029, 21030, 21034, 21035, 21075, 21076, 21090, 21091, 21099, 21100, 21159, 21160, 21162, 21163, 21164, 21165, 21219, 21220, 21222, 21223, 21343, 21344, 21349, 21350, 21418, 21419, 21483, 21484, 21688, 21689, 21690, 21691, 21695, 21696, 21702, 21703, 21748, 21749, 21805, 21806, 22057, 22058, 22120, 22121, 22254, 22255, 22266, 22267, 25601, 25602, 25635, 25636, 25680, 25681, 25709, 25710, 25732, 25733, 25855, 25856, 25923, 25924, 26001, 26002, 26021, 26022, 26401, 26402, 26709, 26710, 26714, 26715, 26731, 26732, 26784, 26785, 26786, 26787, 26868, 26869, 26870, 26871, 26872, 26873, 26887, 26888, 26896, 26897, 26942, 26943, 27106, 27107, 27108, 27109, 27148, 27149, 27150, 27151, 27230, 27231, 27407, 27408, 27409, 27410, 27508, 27509, 27517, 27518, 27532, 27533, 27542, 27543, 27548, 27549, 27560, 27561, 27562, 27563, 27601, 27602, 27609, 27610, 27636, 27637, 27638, 27639, 27640, 27641, 27993, 27994, 27995, 27996, 28134, 28135, 28136, 28137, 28273, 28274, 28275, 28276, 28352, 28353, 28412, 28413, 28423, 28424, 28427, 28428, 28429, 28430, 28481, 28482, 28486, 28487);

-- 10768 Gelatinous Ring: HP+10~35
INSERT INTO `item_latents` VALUES (10768, 2, 35, 51, 1);  -- HP +35

-- 10769 Gelatinous Ring +1: HP+10~35
INSERT INTO `item_latents` VALUES (10769, 2, 35, 51, 1);  -- HP +35

-- 10770 Cacoethic Ring: Enmity-1~5
INSERT INTO `item_latents` VALUES (10770, 27, -5, 51, 1);  -- ENMITY -5

-- 10771 Cacoethic Ring +1: Enmity-1~5
INSERT INTO `item_latents` VALUES (10771, 27, -5, 51, 1);  -- ENMITY -5

-- 20507 Comeuppances: "Double Attack"+1~5%
INSERT INTO `item_latents` VALUES (20507, 288, 5, 51, 1);  -- DOUBLE_ATTACK +5

-- 20508 Comeuppances +1: "Double Attack"+1~5%
INSERT INTO `item_latents` VALUES (20508, 288, 5, 51, 1);  -- DOUBLE_ATTACK +5

-- 20521 Emeici: Accuracy+10~20
INSERT INTO `item_latents` VALUES (20521, 25, 20, 51, 1);  -- ACC +20

-- 20522 Emeici +1: Accuracy+10~20
INSERT INTO `item_latents` VALUES (20522, 25, 20, 51, 1);  -- ACC +20

-- 20527 Fists of Fury: VIT+10~15
INSERT INTO `item_latents` VALUES (20527, 10, 15, 51, 1);  -- VIT +15

-- 20528 Fists of Fury +1: VIT+10~15
INSERT INTO `item_latents` VALUES (20528, 10, 15, 51, 1);  -- VIT +15

-- 20580 Kustawi: "Rapid Shot"+3~7
INSERT INTO `item_latents` VALUES (20580, 359, 7, 51, 1);  -- RAPID_SHOT +7

-- 20581 Kustawi +1: "Rapid Shot"+3~7
INSERT INTO `item_latents` VALUES (20581, 359, 7, 51, 1);  -- RAPID_SHOT +7

-- 20603 Ternion Dagger: AGI+10~15
INSERT INTO `item_latents` VALUES (20603, 11, 15, 51, 1);  -- AGI +15

-- 20604 Ternion Dagger +1: AGI+10~15
INSERT INTO `item_latents` VALUES (20604, 11, 15, 51, 1);  -- AGI +15

-- 20606 Anathema Harpe: "Store TP"+1~5
INSERT INTO `item_latents` VALUES (20606, 73, 5, 51, 1);  -- STORETP +5

-- 20607 Anathema Harpe +1: "Store TP"+1~5
INSERT INTO `item_latents` VALUES (20607, 73, 5, 51, 1);  -- STORETP +5

-- 20611 Sangarius: STR+1~7
INSERT INTO `item_latents` VALUES (20611, 8, 7, 51, 1);  -- STR +7

-- 20612 Sangarius +1: STR+1~7
INSERT INTO `item_latents` VALUES (20612, 8, 7, 51, 1);  -- STR +7

-- 20613 Pukulatmuj: INT+5~15
INSERT INTO `item_latents` VALUES (20613, 12, 15, 51, 1);  -- INT +15

-- 20614 Pukulatmuj +1: INT+5~15
INSERT INTO `item_latents` VALUES (20614, 12, 15, 51, 1);  -- INT +15

-- 20679 Tanmogayi: "Fast Cast"+3~6%
INSERT INTO `item_latents` VALUES (20679, 170, 6, 51, 1);  -- FASTCAST +6

-- 20680 Tanmogayi +1: "Fast Cast"+3~6%
INSERT INTO `item_latents` VALUES (20680, 170, 6, 51, 1);  -- FASTCAST +6

-- 20681 Flyssa: Accuracy+10~15
INSERT INTO `item_latents` VALUES (20681, 25, 15, 51, 1);  -- ACC +15

-- 20682 Flyssa +1: Accuracy+10~15
INSERT INTO `item_latents` VALUES (20682, 25, 15, 51, 1);  -- ACC +15

-- 20696 Combuster: Accuracy+10~20
INSERT INTO `item_latents` VALUES (20696, 25, 20, 51, 1);  -- ACC +20

-- 20697 Combuster +1: Accuracy+10~20
INSERT INTO `item_latents` VALUES (20697, 25, 20, 51, 1);  -- ACC +20

-- 20708 Demers. Degen: "Fast Cast"+1~3%
INSERT INTO `item_latents` VALUES (20708, 170, 3, 51, 1);  -- FASTCAST +3

-- 20709 Demers. Degen +1: "Fast Cast"+1~3%
INSERT INTO `item_latents` VALUES (20709, 170, 3, 51, 1);  -- FASTCAST +3

-- 20799 Mdomo Axe: Enmity-3~7
INSERT INTO `item_latents` VALUES (20799, 27, -7, 51, 1);  -- ENMITY -7

-- 20800 Mdomo Axe +1: Enmity-3~7
INSERT INTO `item_latents` VALUES (20800, 27, -7, 51, 1);  -- ENMITY -7

-- 20804 Perun: Enmity-3~7
INSERT INTO `item_latents` VALUES (20804, 27, -7, 51, 1);  -- ENMITY -7

-- 20805 Perun +1: Enmity-3~7
INSERT INTO `item_latents` VALUES (20805, 27, -7, 51, 1);  -- ENMITY -7

-- 20806 Buramgh: CHR+1~10
INSERT INTO `item_latents` VALUES (20806, 14, 10, 51, 1);  -- CHR +10

-- 20807 Buramgh +1: CHR+1~10
INSERT INTO `item_latents` VALUES (20807, 14, 10, 51, 1);  -- CHR +10

-- 20851 Aizkora: "Double Attack"+1~5%
INSERT INTO `item_latents` VALUES (20851, 288, 5, 51, 1);  -- DOUBLE_ATTACK +5

-- 20852 Aizkora +1: "Double Attack"+1~5%
INSERT INTO `item_latents` VALUES (20852, 288, 5, 51, 1);  -- DOUBLE_ATTACK +5

-- 20853 Beheader: HP+70~120
INSERT INTO `item_latents` VALUES (20853, 2, 120, 51, 1);  -- HP +120

-- 20854 Beheader +1: HP+70~120
INSERT INTO `item_latents` VALUES (20854, 2, 120, 51, 1);  -- HP +120

-- 20898 Triska Scythe: "Double Attack"+1~3%
INSERT INTO `item_latents` VALUES (20898, 288, 3, 51, 1);  -- DOUBLE_ATTACK +3

-- 20899 Triska Scythe +1: "Double Attack"+1~3%
INSERT INTO `item_latents` VALUES (20899, 288, 3, 51, 1);  -- DOUBLE_ATTACK +3

-- 20942 Gae Derg: Critical hit rate +1~5%
INSERT INTO `item_latents` VALUES (20942, 165, 5, 51, 1);  -- CRITHITRATE +5

-- 20943 Gae Derg +1: Critical hit rate +1~5%
INSERT INTO `item_latents` VALUES (20943, 165, 5, 51, 1);  -- CRITHITRATE +5

-- 20980 Raicho: "Double Attack"+1~3%
INSERT INTO `item_latents` VALUES (20980, 288, 3, 51, 1);  -- DOUBLE_ATTACK +3

-- 20981 Raicho +1: "Double Attack"+1~3%
INSERT INTO `item_latents` VALUES (20981, 288, 3, 51, 1);  -- DOUBLE_ATTACK +3

-- 20987 Tancho: "Subtle Blow"+1~6
INSERT INTO `item_latents` VALUES (20987, 289, 6, 51, 1);  -- SUBTLE_BLOW +6

-- 20988 Tancho +1: "Subtle Blow"+1~6
INSERT INTO `item_latents` VALUES (20988, 289, 6, 51, 1);  -- SUBTLE_BLOW +6

-- 21029 Norifusa: STR+1~7
INSERT INTO `item_latents` VALUES (21029, 8, 7, 51, 1);  -- STR +7

-- 21030 Norifusa +1: STR+1~7
INSERT INTO `item_latents` VALUES (21030, 8, 7, 51, 1);  -- STR +7

-- 21034 Kunimune: STR+10~20
INSERT INTO `item_latents` VALUES (21034, 8, 20, 51, 1);  -- STR +20

-- 21035 Kunimune +1: STR+10~20
INSERT INTO `item_latents` VALUES (21035, 8, 20, 51, 1);  -- STR +20

-- 21075 Septoptic: "Conserve MP"+7~11
INSERT INTO `item_latents` VALUES (21075, 296, 11, 51, 1);  -- CONSERVE_MP +11

-- 21076 Septoptic +1: "Conserve MP"+7~11
INSERT INTO `item_latents` VALUES (21076, 296, 11, 51, 1);  -- CONSERVE_MP +11

-- 21090 Loxotic Mace: DEX+5~10
INSERT INTO `item_latents` VALUES (21090, 9, 10, 51, 1);  -- DEX +10

-- 21091 Loxotic Mace +1: DEX+5~10
INSERT INTO `item_latents` VALUES (21091, 9, 10, 51, 1);  -- DEX +10

-- 21099 Magesmasher: Attack+5~15
INSERT INTO `item_latents` VALUES (21099, 23, 15, 51, 1);  -- ATT +15

-- 21100 Magesmasher +1: Attack+5~15
INSERT INTO `item_latents` VALUES (21100, 23, 15, 51, 1);  -- ATT +15

-- 21159 Marin Staff: INT+10~15
INSERT INTO `item_latents` VALUES (21159, 12, 15, 51, 1);  -- INT +15

-- 21160 Marin Staff +1: INT+10~15
INSERT INTO `item_latents` VALUES (21160, 12, 15, 51, 1);  -- INT +15

-- 21162 Pouwhenua: Accuracy+10~20
INSERT INTO `item_latents` VALUES (21162, 25, 20, 51, 1);  -- ACC +20

-- 21163 Pouwhenua +1: Accuracy+10~20
INSERT INTO `item_latents` VALUES (21163, 25, 20, 51, 1);  -- ACC +20

-- 21164 Ababinili: "Cure" potency +6~10%
INSERT INTO `item_latents` VALUES (21164, 374, 10, 51, 1);  -- CURE_POTENCY +10

-- 21165 Ababinili +1: "Cure" potency +6~10%
INSERT INTO `item_latents` VALUES (21165, 374, 10, 51, 1);  -- CURE_POTENCY +10

-- 21219 Paloma Bow: Ranged Accuracy+10~20
INSERT INTO `item_latents` VALUES (21219, 26, 20, 51, 1);  -- RACC +20

-- 21220 Paloma Bow +1: Ranged Accuracy+10~20
INSERT INTO `item_latents` VALUES (21220, 26, 20, 51, 1);  -- RACC +20

-- 21222 Mengado: Ranged Accuracy+10~20
INSERT INTO `item_latents` VALUES (21222, 26, 20, 51, 1);  -- RACC +20

-- 21223 Mengado +1: Ranged Accuracy+10~20
INSERT INTO `item_latents` VALUES (21223, 26, 20, 51, 1);  -- RACC +20

-- 21343 Ghastly Tathlum: INT+2~6
INSERT INTO `item_latents` VALUES (21343, 12, 6, 51, 1);  -- INT +6

-- 21344 Ghastly Tathlum +1: INT+2~6
INSERT INTO `item_latents` VALUES (21344, 12, 6, 51, 1);  -- INT +6

-- 21349 Wingcutter: DEX+1~5
INSERT INTO `item_latents` VALUES (21349, 9, 5, 51, 1);  -- DEX +5

-- 21350 Wingcutter +1: DEX+1~5
INSERT INTO `item_latents` VALUES (21350, 9, 5, 51, 1);  -- DEX +5

-- 21418 Rigorous Grip: Attack+10~15
INSERT INTO `item_latents` VALUES (21418, 23, 15, 51, 1);  -- ATT +15

-- 21419 Rigorous Grip +1: Attack+10~15
INSERT INTO `item_latents` VALUES (21419, 23, 15, 51, 1);  -- ATT +15

-- 21483 Malison: Ranged Attack+15~25
INSERT INTO `item_latents` VALUES (21483, 24, 25, 51, 1);  -- RATT +25

-- 21484 Malison +1: Ranged Attack+15~25
INSERT INTO `item_latents` VALUES (21484, 24, 25, 51, 1);  -- RATT +25

-- 21688 Montante: "Triple Attack"+3~5%
INSERT INTO `item_latents` VALUES (21688, 302, 5, 51, 1);  -- TRIPLE_ATTACK +5

-- 21689 Montante +1: "Triple Attack"+3~5%
INSERT INTO `item_latents` VALUES (21689, 302, 5, 51, 1);  -- TRIPLE_ATTACK +5

-- 21690 Ushenzi: "Cure" potency +6~10%
INSERT INTO `item_latents` VALUES (21690, 374, 10, 51, 1);  -- CURE_POTENCY +10

-- 21691 Ushenzi +1: "Cure" potency +6~10%
INSERT INTO `item_latents` VALUES (21691, 374, 10, 51, 1);  -- CURE_POTENCY +10

-- 21695 Nullis: STR+10~20
INSERT INTO `item_latents` VALUES (21695, 8, 20, 51, 1);  -- STR +20

-- 21696 Nullis +1: STR+10~20
INSERT INTO `item_latents` VALUES (21696, 8, 20, 51, 1);  -- STR +20

-- 21702 Kladenets: INT+10~20
INSERT INTO `item_latents` VALUES (21702, 12, 20, 51, 1);  -- INT +20

-- 21703 Kladenets +1: INT+10~20
INSERT INTO `item_latents` VALUES (21703, 12, 20, 51, 1);  -- INT +20

-- 21748 Habilitator: Accuracy+20~30
INSERT INTO `item_latents` VALUES (21748, 25, 30, 51, 1);  -- ACC +30

-- 21749 Habilitator +1: Accuracy+20~30
INSERT INTO `item_latents` VALUES (21749, 25, 30, 51, 1);  -- ACC +30

-- 21805 Pixquizpan: "Magic Atk. Bonus"+15~25
INSERT INTO `item_latents` VALUES (21805, 28, 25, 51, 1);  -- MATT +25

-- 21806 Pixquizpan +1: "Magic Atk. Bonus"+15~25
INSERT INTO `item_latents` VALUES (21806, 28, 25, 51, 1);  -- MATT +25

-- 22057 Contemplator: "Refresh"+1
INSERT INTO `item_latents` VALUES (22057, 369, 1, 51, 1);  -- REFRESH +1

-- 22058 Contemplator +1: "Refresh"+1~2
INSERT INTO `item_latents` VALUES (22058, 369, 2, 51, 1);  -- REFRESH +2

-- 22120 Imati: Ranged Attack+20~30
INSERT INTO `item_latents` VALUES (22120, 24, 30, 51, 1);  -- RATT +30

-- 22121 Imati +1: Ranged Attack+20~30
INSERT INTO `item_latents` VALUES (22121, 24, 30, 51, 1);  -- RATT +30

-- 22254 Seeth. Bomblet: STR+1~5
INSERT INTO `item_latents` VALUES (22254, 8, 5, 51, 1);  -- STR +5

-- 22255 Seeth. Bomblet +1: STR+1~5
INSERT INTO `item_latents` VALUES (22255, 8, 5, 51, 1);  -- STR +5

-- 22266 Antitail: "Double Attack"+1~3%
INSERT INTO `item_latents` VALUES (22266, 288, 3, 51, 1);  -- DOUBLE_ATTACK +3

-- 22267 Antitail +1: "Double Attack"+1~3%
INSERT INTO `item_latents` VALUES (22267, 288, 3, 51, 1);  -- DOUBLE_ATTACK +3

-- 25601 Blistering Sallet: HP+30~80
INSERT INTO `item_latents` VALUES (25601, 2, 80, 51, 1);  -- HP +80

-- 25602 Blistering Sallet +1: HP+30~80
INSERT INTO `item_latents` VALUES (25602, 2, 80, 51, 1);  -- HP +80

-- 25635 Loess Barbuta: Enmity+9~14
INSERT INTO `item_latents` VALUES (25635, 27, 14, 51, 1);  -- ENMITY +14

-- 25636 Loess Barbuta +1: Enmity+9~14
INSERT INTO `item_latents` VALUES (25636, 27, 14, 51, 1);  -- ENMITY +14

-- 25680 Cohort Cloak: Magic Accuracy+10~20
INSERT INTO `item_latents` VALUES (25680, 30, 20, 51, 1);  -- MACC +20

-- 25681 Cohort Cloak +1: Magic Accuracy+10~20
INSERT INTO `item_latents` VALUES (25681, 30, 20, 51, 1);  -- MACC +20

-- 25709 Obviat. Cuirass: Enmity+1~8
INSERT INTO `item_latents` VALUES (25709, 27, 8, 51, 1);  -- ENMITY +8

-- 25710 Obviat. Cuirass +1: Enmity+1~8
INSERT INTO `item_latents` VALUES (25710, 27, 8, 51, 1);  -- ENMITY +8

-- 25732 Tatena. Harama.: "Store TP"+5~9
INSERT INTO `item_latents` VALUES (25732, 73, 9, 51, 1);  -- STORETP +9

-- 25733 Tatena. Harama. +1: "Store TP"+5~9
INSERT INTO `item_latents` VALUES (25733, 73, 9, 51, 1);  -- STORETP +9

-- 25855 Tatena. Haidate: "Store TP"+4~8
INSERT INTO `item_latents` VALUES (25855, 73, 8, 51, 1);  -- STORETP +8

-- 25856 Tatena. Haidate +1: "Store TP"+4~8
INSERT INTO `item_latents` VALUES (25856, 73, 8, 51, 1);  -- STORETP +8

-- 25923 Tatena. Sune.: "Store TP"+4~8
INSERT INTO `item_latents` VALUES (25923, 73, 8, 51, 1);  -- STORETP +8

-- 25924 Tatena. Sune. +1: "Store TP"+4~8
INSERT INTO `item_latents` VALUES (25924, 73, 8, 51, 1);  -- STORETP +8

-- 26001 Loricate Torque: DEF:+10~15
INSERT INTO `item_latents` VALUES (26001, 1, 15, 51, 1);  -- DEF +15

-- 26002 Loricate Torque +1: DEF:+10~15
INSERT INTO `item_latents` VALUES (26002, 1, 15, 51, 1);  -- DEF +15

-- 26021 Vim Torque: "Refresh"+1~2
INSERT INTO `item_latents` VALUES (26021, 369, 2, 51, 1);  -- REFRESH +2

-- 26022 Vim Torque +1: "Refresh"+1~3
INSERT INTO `item_latents` VALUES (26022, 369, 3, 51, 1);  -- REFRESH +3

-- 26401 Forfend: Accuracy+10~20
INSERT INTO `item_latents` VALUES (26401, 25, 20, 51, 1);  -- ACC +20

-- 26402 Forfend +1: Accuracy+10~20
INSERT INTO `item_latents` VALUES (26402, 25, 20, 51, 1);  -- ACC +20

-- 26709 Imp. Wing Hair.: DEX+1~7
INSERT INTO `item_latents` VALUES (26709, 9, 7, 51, 1);  -- DEX +7
-- 26709 Imp. Wing Hair.: AGI+1~7
INSERT INTO `item_latents` VALUES (26709, 11, 7, 51, 1);  -- AGI +7

-- 26710 Imp. Wing Hair. +1: DEX+1~7
INSERT INTO `item_latents` VALUES (26710, 9, 7, 51, 1);  -- DEX +7
-- 26710 Imp. Wing Hair. +1: AGI+1~7
INSERT INTO `item_latents` VALUES (26710, 11, 7, 51, 1);  -- AGI +7

-- 26714 Adorned Helm: Attack+5~15
INSERT INTO `item_latents` VALUES (26714, 23, 15, 51, 1);  -- ATT +15

-- 26715 Adorned Helm +1: Attack+5~15
INSERT INTO `item_latents` VALUES (26715, 23, 15, 51, 1);  -- ATT +15

-- 26731 Stinger Helm: STR+3~8
INSERT INTO `item_latents` VALUES (26731, 8, 8, 51, 1);  -- STR +8

-- 26732 Stinger Helm +1: STR+3~8
INSERT INTO `item_latents` VALUES (26732, 8, 8, 51, 1);  -- STR +8

-- 26784 Hike Khat: MP+10~50
INSERT INTO `item_latents` VALUES (26784, 5, 50, 51, 1);  -- MP +50

-- 26785 Hike Khat +1: MP+10~50
INSERT INTO `item_latents` VALUES (26785, 5, 50, 51, 1);  -- MP +50

-- 26786 Alhazen Hat: HP+30~80
INSERT INTO `item_latents` VALUES (26786, 2, 80, 51, 1);  -- HP +80

-- 26787 Alhazen Hat +1: HP+30~80
INSERT INTO `item_latents` VALUES (26787, 2, 80, 51, 1);  -- HP +80

-- 26868 Ros. Jaseran: "Fast Cast"+3~6%
INSERT INTO `item_latents` VALUES (26868, 170, 6, 51, 1);  -- FASTCAST +6

-- 26869 Ros. Jaseran +1: "Fast Cast"+3~6%
INSERT INTO `item_latents` VALUES (26869, 170, 6, 51, 1);  -- FASTCAST +6

-- 26870 Emet Harness: Accuracy+10~20
INSERT INTO `item_latents` VALUES (26870, 25, 20, 51, 1);  -- ACC +20

-- 26871 Emet Harness +1: Accuracy+10~20
INSERT INTO `item_latents` VALUES (26871, 25, 20, 51, 1);  -- ACC +20

-- 26872 Hime Domaru: "Store TP"+1~5
INSERT INTO `item_latents` VALUES (26872, 73, 5, 51, 1);  -- STORETP +5

-- 26873 Hime Domaru +1: "Store TP"+1~5
INSERT INTO `item_latents` VALUES (26873, 73, 5, 51, 1);  -- STORETP +5

-- 26887 Shomonjijoe: Avatar: "Magic Atk. Bonus"+25~30
INSERT INTO `item_latents` VALUES (26887, 992, 30, 51, 1);  -- PET_MAB_MDB +30

-- 26888 Shomonjijoe +1: Avatar: "Magic Atk. Bonus"+25~30
INSERT INTO `item_latents` VALUES (26888, 992, 30, 51, 1);  -- PET_MAB_MDB +30

-- 26896 Lugra Cloak: "Fast Cast"+3~6%
INSERT INTO `item_latents` VALUES (26896, 170, 6, 51, 1);  -- FASTCAST +6

-- 26897 Lugra Cloak +1: "Fast Cast"+3~6%
INSERT INTO `item_latents` VALUES (26897, 170, 6, 51, 1);  -- FASTCAST +6

-- 26942 Agony Jerkin: Accuracy+10~15
INSERT INTO `item_latents` VALUES (26942, 25, 15, 51, 1);  -- ACC +15

-- 26943 Agony Jerkin +1: Accuracy+10~15
INSERT INTO `item_latents` VALUES (26943, 25, 15, 51, 1);  -- ACC +15

-- 27106 Asteria Mitts: "Refresh"+1
INSERT INTO `item_latents` VALUES (27106, 369, 1, 51, 1);  -- REFRESH +1

-- 27107 Asteria Mitts +1: "Refresh"+1~2
INSERT INTO `item_latents` VALUES (27107, 369, 2, 51, 1);  -- REFRESH +2

-- 27108 Lamassu Mitts: MP+10~50
INSERT INTO `item_latents` VALUES (27108, 5, 50, 51, 1);  -- MP +50

-- 27109 Lamassu Mitts +1: MP+10~50
INSERT INTO `item_latents` VALUES (27109, 5, 50, 51, 1);  -- MP +50

-- 27148 Tatena. Gote: "Store TP"+4~8
INSERT INTO `item_latents` VALUES (27148, 73, 8, 51, 1);  -- STORETP +8

-- 27149 Tatena. Gote +1: "Store TP"+4~8
INSERT INTO `item_latents` VALUES (27149, 73, 8, 51, 1);  -- STORETP +8

-- 27150 Gazu Bracelets: Accuracy+10~15
INSERT INTO `item_latents` VALUES (27150, 25, 15, 51, 1);  -- ACC +15

-- 27151 Gazu Bracelets +1: Accuracy+10~15
INSERT INTO `item_latents` VALUES (27151, 25, 15, 51, 1);  -- ACC +15

-- 27230 Zoar Subligar: "Double Attack"+1~5%
INSERT INTO `item_latents` VALUES (27230, 288, 5, 51, 1);  -- DOUBLE_ATTACK +5

-- 27231 Zoar Subligar +1: "Double Attack"+1~5%
INSERT INTO `item_latents` VALUES (27231, 288, 5, 51, 1);  -- DOUBLE_ATTACK +5

-- 27407 Hygieia Clogs: Enmity-3~7
INSERT INTO `item_latents` VALUES (27407, 27, -7, 51, 1);  -- ENMITY -7

-- 27408 Hygieia Clogs +1: Enmity-3~7
INSERT INTO `item_latents` VALUES (27408, 27, -7, 51, 1);  -- ENMITY -7

-- 27409 Hippo. Socks: Evasion+15~20
INSERT INTO `item_latents` VALUES (27409, 68, 20, 51, 1);  -- EVA +20

-- 27410 Hippo. Socks +1: Evasion+15~20
INSERT INTO `item_latents` VALUES (27410, 68, 20, 51, 1);  -- EVA +20

-- 27508 Unmoving Collar: Accuracy+1~5
INSERT INTO `item_latents` VALUES (27508, 25, 5, 51, 1);  -- ACC +5

-- 27509 Unmoving Collar +1: Accuracy+1~5
INSERT INTO `item_latents` VALUES (27509, 25, 5, 51, 1);  -- ACC +5

-- 27517 Bathy Choker: Evasion+5~15
INSERT INTO `item_latents` VALUES (27517, 68, 15, 51, 1);  -- EVA +15

-- 27518 Bathy Choker +1: Evasion+5~15
INSERT INTO `item_latents` VALUES (27518, 68, 15, 51, 1);  -- EVA +15

-- 27532 Zwazo Earring: STR+1~5
INSERT INTO `item_latents` VALUES (27532, 8, 5, 51, 1);  -- STR +5

-- 27533 Zwazo Earring +1: STR+1~5
INSERT INTO `item_latents` VALUES (27533, 8, 5, 51, 1);  -- STR +5

-- 27542 Domin. Earring: Accuracy+1~5
INSERT INTO `item_latents` VALUES (27542, 25, 5, 51, 1);  -- ACC +5

-- 27543 Domin. Earring +1: Accuracy+1~5
INSERT INTO `item_latents` VALUES (27543, 25, 5, 51, 1);  -- ACC +5

-- 27548 Odnowa Earring: Accuracy+5~10
INSERT INTO `item_latents` VALUES (27548, 25, 10, 51, 1);  -- ACC +10

-- 27549 Odnowa Earring +1: Accuracy+5~10
INSERT INTO `item_latents` VALUES (27549, 25, 10, 51, 1);  -- ACC +10

-- 27560 Apeile Ring: Enmity+5~9
INSERT INTO `item_latents` VALUES (27560, 27, 9, 51, 1);  -- ENMITY +9

-- 27561 Apeile Ring +1: Enmity+5~9
INSERT INTO `item_latents` VALUES (27561, 27, 9, 51, 1);  -- ENMITY +9

-- 27562 Metamor. Ring: Magic Accuracy+1~5
INSERT INTO `item_latents` VALUES (27562, 30, 5, 51, 1);  -- MACC +5

-- 27563 Metamor. Ring +1: Magic Accuracy+1~5
INSERT INTO `item_latents` VALUES (27563, 30, 5, 51, 1);  -- MACC +5

-- 27601 Ground. Mantle: DEX+1~7
INSERT INTO `item_latents` VALUES (27601, 9, 7, 51, 1);  -- DEX +7

-- 27602 Ground. Mantle +1: DEX+1~7
INSERT INTO `item_latents` VALUES (27602, 9, 7, 51, 1);  -- DEX +7

-- 27609 Fi Follet Cape: MND+1~5
INSERT INTO `item_latents` VALUES (27609, 13, 5, 51, 1);  -- MND +5

-- 27610 Fi Follet Cape +1: MND+1~5
INSERT INTO `item_latents` VALUES (27610, 13, 5, 51, 1);  -- MND +5

-- 27636 Evalach: MP+10~50
INSERT INTO `item_latents` VALUES (27636, 5, 50, 51, 1);  -- MP +50

-- 27637 Evalach +1: MP+10~50
INSERT INTO `item_latents` VALUES (27637, 5, 50, 51, 1);  -- MP +50

-- 27638 Ajax: HP+70~120
INSERT INTO `item_latents` VALUES (27638, 2, 120, 51, 1);  -- HP +120

-- 27639 Ajax +1: HP+70~120
INSERT INTO `item_latents` VALUES (27639, 2, 120, 51, 1);  -- HP +120

-- 27640 Deliverance: Accuracy+10~15
INSERT INTO `item_latents` VALUES (27640, 25, 15, 51, 1);  -- ACC +15

-- 27641 Deliverance +1: Accuracy+10~15
INSERT INTO `item_latents` VALUES (27641, 25, 15, 51, 1);  -- ACC +15

-- 27993 Macabre Gaunt.: HP+20~60
INSERT INTO `item_latents` VALUES (27993, 2, 60, 51, 1);  -- HP +60

-- 27994 Macabre Gaunt. +1: HP+20~60
INSERT INTO `item_latents` VALUES (27994, 2, 60, 51, 1);  -- HP +60

-- 27995 Shigure Tekko: "Subtle Blow"+1~7
INSERT INTO `item_latents` VALUES (27995, 289, 7, 51, 1);  -- SUBTLE_BLOW +7

-- 27996 Shigure Tekko +1: "Subtle Blow"+1~7
INSERT INTO `item_latents` VALUES (27996, 289, 7, 51, 1);  -- SUBTLE_BLOW +7

-- 28134 Assid. Pants: "Refresh"+1
INSERT INTO `item_latents` VALUES (28134, 369, 1, 51, 1);  -- REFRESH +1

-- 28135 Assid. Pants +1: "Refresh"+1~2
INSERT INTO `item_latents` VALUES (28135, 369, 2, 51, 1);  -- REFRESH +2

-- 28136 Augury Cuisses: "Double Attack"+1~3%
INSERT INTO `item_latents` VALUES (28136, 288, 3, 51, 1);  -- DOUBLE_ATTACK +3

-- 28137 Augury Cuisses +1: "Double Attack"+1~3%
INSERT INTO `item_latents` VALUES (28137, 288, 3, 51, 1);  -- DOUBLE_ATTACK +3

-- 28273 Regal Pumps: "Fast Cast"+1~3%
INSERT INTO `item_latents` VALUES (28273, 170, 3, 51, 1);  -- FASTCAST +3

-- 28274 Regal Pumps +1: "Fast Cast"+1~3%
INSERT INTO `item_latents` VALUES (28274, 170, 3, 51, 1);  -- FASTCAST +3

-- 28275 Jute Boots: Evasion+1~10
INSERT INTO `item_latents` VALUES (28275, 68, 10, 51, 1);  -- EVA +10

-- 28276 Jute Boots +1: Evasion+1~10
INSERT INTO `item_latents` VALUES (28276, 68, 10, 51, 1);  -- EVA +10

-- 28352 Canto Necklace: CHR+5~12
INSERT INTO `item_latents` VALUES (28352, 14, 12, 51, 1);  -- CHR +12

-- 28353 Canto Necklace +1: CHR+5~12
INSERT INTO `item_latents` VALUES (28353, 14, 12, 51, 1);  -- CHR +12

-- 28412 Kentarch Belt: "Store TP"+1~5
INSERT INTO `item_latents` VALUES (28412, 73, 5, 51, 1);  -- STORETP +5

-- 28413 Kentarch Belt +1: "Store TP"+1~5
INSERT INTO `item_latents` VALUES (28413, 73, 5, 51, 1);  -- STORETP +5

-- 28423 Shinjutsu-no-Obi: MP recovered while healing +5~7
INSERT INTO `item_latents` VALUES (28423, 71, 7, 51, 1);  -- MPHEAL +7

-- 28424 Shinjutsu-no-Obi +1: MP recovered while healing +5~7
INSERT INTO `item_latents` VALUES (28424, 71, 7, 51, 1);  -- MPHEAL +7

-- 28427 Sailfi Belt: Attack+10~15
INSERT INTO `item_latents` VALUES (28427, 23, 15, 51, 1);  -- ATT +15

-- 28428 Sailfi Belt +1: Attack+10~15
INSERT INTO `item_latents` VALUES (28428, 23, 15, 51, 1);  -- ATT +15

-- 28429 Acuity Belt: INT+3~7
INSERT INTO `item_latents` VALUES (28429, 12, 7, 51, 1);  -- INT +7

-- 28430 Acuity Belt +1: INT+3~7
INSERT INTO `item_latents` VALUES (28430, 12, 7, 51, 1);  -- INT +7

-- 28481 Lugra Earring: "Double Attack"+1~3%
INSERT INTO `item_latents` VALUES (28481, 288, 3, 51, 1);  -- DOUBLE_ATTACK +3

-- 28482 Lugra Earring +1: "Double Attack"+1~3%
INSERT INTO `item_latents` VALUES (28482, 288, 3, 51, 1);  -- DOUBLE_ATTACK +3

-- 28486 Arete del Luna: Light+15~25
INSERT INTO `item_latents` VALUES (28486, 21, 25, 51, 1);  -- LIGHT_MEVA +25

-- 28487 Arete del Luna +1: Light+15~25
INSERT INTO `item_latents` VALUES (28487, 21, 25, 51, 1);  -- LIGHT_MEVA +25
