-- ============================================================================
-- zz_barrage_recast.sql
--
-- Set the RNG "Barrage" job-ability recast to 6:00 (was the retail 5:00 / 300s).
--
--   abilityId 60 = Barrage (recastId 125). `recastTime` is in SECONDS.
--
-- Abilities are loaded into memory at map boot, so this takes effect on the
-- next MAP RESTART (not a hot-reload).
--
-- Idempotent config override (a fixed SET, not a one-time migration), safe to
-- live in zz_*.sql, which re-applies on every deploy.
-- ============================================================================
UPDATE `abilities` SET `recastTime` = 360 WHERE `abilityId` = 60;
