#!/usr/bin/env python3
"""Generate catalog.itemTypeMap for the Infamy Vendor's grouped browser.

Maps each curated vendor item id (catalog.vendorItems + catalog.vendorItemsAuto
in modules/custom/lua/infamy_vendor_catalog.lua) to a 'Category/Subtype' string,
so InfamyVendor.lua can present a Category -> Subtype -> items menu instead of one
flat ~60-item paged list.

Category/Subtype is derived from the live DB:
  * item_equipment.slot  (bitmask: main/sub/range/head/body/.../ear/ring/back)
  * item_weapon.skill    (1=H2H,2=Dagger,3=Sword,... for the weapon subtype)

A few items are mis-defined in the DB (e.g. Coiste Bodhar is flagged WEAPON_TYPE
with slot=8; Knobkierrie isn't in item_equipment at all) -> see OVERRIDES.

Splices the result directly into the
  -- INFAMY_TYPEMAP:BEGIN ... -- INFAMY_TYPEMAP:END
block in dungeon_catalog.lua (falls back to writing tools/_infamy_typemap.lua
for manual paste only if those sentinels are missing). Run AFTER
build_infamy_top_picks.py (it reads catalog.vendorItemsAuto); rebalance_all.bat
does this for you. Unmapped items fall to 'Other' in the menu.
"""
from __future__ import annotations
import os, re

REPO = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))
CATALOG = os.path.join(REPO, "modules", "custom", "lua", "infamy_vendor_catalog.lua")
ITEM_EQUIP = os.path.join(REPO, "sql", "item_equipment.sql")
ITEM_WEAPON = os.path.join(REPO, "sql", "item_weapon.sql")
OUT = os.path.join(REPO, "tools", "_infamy_typemap.lua")

# DB anomalies — force the human-expected bucket.
OVERRIDES = {
    21431: "Accessories/Ear",   # coiste_bodhar: DB has slot=8 / WEAPON_TYPE (bug)
    26072: "Accessories/Neck",  # knobkierrie: not in item_equipment at all
}

SKILL = {1: "Hand-to-Hand", 2: "Dagger", 3: "Sword", 4: "Great Sword", 5: "Axe",
         6: "Great Axe", 7: "Scythe", 8: "Polearm", 9: "Katana", 10: "Great Katana",
         11: "Club", 12: "Staff", 25: "Archery", 26: "Marksmanship", 27: "Throwing"}


def _vals(line):
    s = line[line.find("VALUES (") + 8:]
    s = s[:s.rfind(")")]
    return [p.strip().strip("'") for p in s.split(",")]


def curated_ids():
    txt = open(CATALOG, encoding="utf-8").read()

    def section(start, endpat):
        i = txt.find(start)
        if i < 0:
            return ""
        m = re.search(endpat, txt[i + len(start):])
        return txt[i: i + len(start) + (m.start() if m else len(txt))]

    blob = (section("catalog.vendorItems =", r"\ncatalog\.vendorSets")
            + section("catalog.vendorItemsAuto =", r"DOCGEN:INFAMY_AUTO:END"))
    seen, out = set(), []
    # \s* (not a literal single space): the auto block right-aligns ids, e.g.
    # `id =  20672`, so a single-space pattern would silently skip every
    # vendorItemsAuto row (the bug that dumped them all into 'Other').
    for m in re.findall(r"id\s*=\s*(\d+)", blob):
        i = int(m)
        if i not in seen:
            seen.add(i)
            out.append(i)
    return out


def load_col(path, table, idx):
    d = {}
    for line in open(path, encoding="utf-8", errors="ignore"):
        if f"`{table}`" not in line or "VALUES" not in line:
            continue
        p = _vals(line)
        try:
            d[int(p[0])] = int(p[idx])
        except (ValueError, IndexError):
            continue
    return d


def categorize(iid, slot, skill):
    if iid in OVERRIDES:
        return OVERRIDES[iid]
    s = slot.get(iid)
    if s is None:
        return "Other/Other"
    if s & 1 or s & 4:                       # main-hand or ranged = weapon
        sk = skill.get(iid)
        if sk in SKILL:
            return "Weapons/" + SKILL[sk]
        if s & 4:
            return "Weapons/Instrument"      # range slot, no melee skill (horn/harp)
        return "Weapons/Other"
    if s == 2:
        return "Weapons/Grip-Shield"
    if s & 8:                                # ammo slot: bullets / arrows / bolts
        return "Weapons/Ammo"
    for bit, name in ((16, "Head"), (32, "Body"), (64, "Hands"), (128, "Legs"), (256, "Feet")):
        if s & bit:
            return "Armor/" + name
    if s & 512:
        return "Accessories/Neck"
    if s & 1024:
        return "Accessories/Waist"
    if s & (2048 | 4096):
        return "Accessories/Ear"
    if s & (8192 | 16384):
        return "Accessories/Ring"
    if s & 32768:
        return "Accessories/Back"
    return "Other/Other"


def main():
    ids = curated_ids()
    slot = load_col(ITEM_EQUIP, "item_equipment", 8)
    skill = load_col(ITEM_WEAPON, "item_weapon", 2)

    rows = [(i, categorize(i, slot, skill)) for i in ids]

    lines = [
        "-- INFAMY_TYPEMAP:BEGIN",
        "-- AUTO-GENERATED by tools/build_infamy_typemap.py -- do NOT hand-edit.",
        "-- Maps curated Infamy Vendor item ids to 'Category/Subtype' for the",
        "-- grouped browser (derived from item_equipment.slot + item_weapon.skill).",
        "-- Re-run the tool after adding items; unmapped ids show under 'Other'.",
        "catalog.itemTypeMap =",
        "{",
    ]
    for i, cs in rows:
        lines.append(f"    [{i}] = '{cs}',")
    lines.append("}")
    lines.append("-- INFAMY_TYPEMAP:END")
    block = "\n".join(lines)

    # Splice directly into infamy_vendor_catalog.lua between the sentinels.
    cat_txt = open(CATALOG, encoding="utf-8").read()
    sent = re.compile(r"-- INFAMY_TYPEMAP:BEGIN.*?-- INFAMY_TYPEMAP:END", re.DOTALL)
    if sent.search(cat_txt):
        open(CATALOG, "w", encoding="utf-8", newline="\n").write(sent.sub(lambda _m: block, cat_txt))
        dest = f"spliced into {os.path.basename(CATALOG)}"
    else:
        open(OUT, "w", encoding="utf-8", newline="\n").write(block + "\n")
        dest = (f"INFAMY_TYPEMAP sentinels missing in {os.path.basename(CATALOG)} "
                f"-> wrote {os.path.basename(OUT)} for manual paste")

    # human review
    from collections import defaultdict
    g = defaultdict(list)
    for i, cs in rows:
        g[cs].append(i)
    print(f"mapped {len(rows)} ids ({dest})")
    for cs in sorted(g):
        print(f"  {cs}: {len(g[cs])}")


if __name__ == "__main__":
    main()
