#!/usr/bin/env python3
"""Generate item_mods gap-fill for the OBTAINABLE items still flagged by
   reconcile_gear_mods.py --obtainable  (weapons + a few reforged top-ups + ammo).

Reads the audit's own report (tools/gear_reconcile_report.json), so it stays in
sync: re-run the audit with --obtainable first, then this. Each flagged "missing"
mod already carries its final stored value (the audit applied scaling), and
weapon-intrinsic skills are already excluded by the audit's weapon filter.

Skips statless-by-design items (the Onion Sword line + the rollback allowlist).
Writes sql/zz_obtainable_gap_fills.sql.  INSERT IGNORE => only adds what's missing.
"""
from __future__ import annotations
import sys, os, json, re
REPO = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, REPO)
from tools.check_obtainable_naked import by_design_allowlist


def main():
    report = json.load(open(os.path.join(REPO, "tools", "gear_reconcile_report.json"), encoding="utf-8"))
    allow = by_design_allowlist()
    rows, skipped = [], []
    for it in report["items"]:
        iid = it["itemId"]
        if iid in allow:                      # statless on purpose
            skipped.append((iid, it["name"]))
            continue
        for label, val in it["missing"].items():
            m = re.search(r"\((\d+)\)$", label)   # "STR(8)" -> 8
            if m:
                rows.append((iid, int(m.group(1)), int(val)))

    by_item = {}
    for iid, mid, v in rows:
        by_item.setdefault(iid, []).append((mid, v))
    out = os.path.join(REPO, "sql", "zz_obtainable_gap_fills.sql")
    lines = [
        "-- ---------------------------------------------------------------------------",
        "-- zz_obtainable_gap_fills.sql  (generated by tools/gen_obtainable_gap_fills.py)",
        "--",
        "-- Final gap-fill for OBTAINABLE gear flagged by reconcile_gear_mods.py",
        "-- --obtainable: a handful of iLvl 100-119 weapons missing item_mods, a few",
        "-- reforged +3/+4 missing one late-mapped stat, and ammo. Values are the",
        "-- BG-Wiki reference values. INSERT IGNORE => only missing mods are added.",
        "-- Statless-by-design items (Onion Sword line) are intentionally excluded.",
        "-- ---------------------------------------------------------------------------",
        "",
    ]
    for iid in sorted(by_item):
        vals = ",".join(f"({iid},{m},{v})" for m, v in sorted(by_item[iid]))
        lines.append(f"INSERT IGNORE INTO `item_mods` VALUES {vals};")
    open(out, "w", encoding="utf-8").write("\n".join(lines) + "\n")

    print(f"items: {len(by_item)} | INSERT IGNORE rows: {len(rows)}")
    print(f"skipped (statless by design): {skipped}")
    print("per-item:")
    for iid in sorted(by_item):
        print(f"  {iid}: {by_item[iid]}")
    print(f"\nwrote {out}")


if __name__ == "__main__":
    main()
