#!/usr/bin/env python3
"""Reforge/upgrade carry-forward fix.

A higher upgrade tier (+1/+2/+3/+4) must never be MISSING a mod that a lower
tier already has. The tier-stat derivation only scales the *common* stats and
silently drops *signature* mods -- e.g. Peltast's Cuissots +3 lost mod 286
('Jump Soul Spirit Attack Bonus' +17) that the +2 has, and ~hundreds of other
AF/Relic/Empyrean pieces lost Enmity / resists / job bonuses on upgrade.

This reads the EFFECTIVE item_mods (every sql source merged the way the server
loads them), then for each name-family emits the missing lower-tier mods onto
the higher tiers, carrying the highest value seen on any lower tier (so an
upgrade is never a downgrade and we never invent numbers).

Output: sql/zzz_reforge_carryforward.sql  (INSERT IGNORE, sorts LAST so it only
fills genuine gaps and never overrides a tier's real value).
"""
from __future__ import annotations
import re
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SQL = ROOT / "sql"
OUT = SQL / "zzz_reforge_carryforward.sql"

# (file, override?) in dbtool load order. override True = plain INSERT / ON
# DUPLICATE KEY UPDATE (later value wins); False = INSERT IGNORE (fills only if
# the (item,mod) key is still absent).
SOURCES = [
    ("item_mods.sql", True),
    ("zz_custom_naked_item_mods.sql", True),
    ("zz_derived_tier_mods.sql", False),
    ("zz_infamy_extra_mods.sql", True),
    ("zz_naked_dungeon_fix.sql", False),
    ("zz_obtainable_gap_fills.sql", False),
    ("zz_reforge_plus12_displayed_stats.sql", False),
    ("zz_reforge_plus3_displayed_stats.sql", False),
    ("zz_reforge_plus3_outliers.sql", False),
    ("zz_reforge_plus4_displayed_stats.sql", False),
    ("zz_relic_119iii_mods.sql", False),
    ("zz_tokko_voluspa_mods.sql", False),
]
_TUPLE = re.compile(r"\((\d+),(\d+),(-?\d+)\)")


def load_effective() -> dict[int, dict[int, int]]:
    eff: dict[int, dict[int, int]] = {}
    for fn, override in SOURCES:
        p = SQL / fn
        if not p.exists():
            continue
        for ln in p.read_text(encoding="utf-8", errors="replace").splitlines():
            if "item_mods`" not in ln:
                continue
            for m in _TUPLE.finditer(ln):
                iid, mod, val = int(m.group(1)), int(m.group(2)), int(m.group(3))
                d = eff.setdefault(iid, {})
                if override or mod not in d:
                    d[mod] = val
    return eff


def short_names() -> dict[int, str]:
    names = {}
    for ln in (SQL / "item_basic.sql").read_text(encoding="utf-8", errors="replace").splitlines():
        m = re.match(r"^INSERT INTO `item_basic` VALUES \((\d+),\d+,'([^']*)'", ln)
        if m:
            names[int(m.group(1))] = m.group(2)
    return names


def mod_names() -> dict[int, str]:
    out = {}
    mp = ROOT / "scripts" / "enum" / "mod.lua"
    if mp.exists():
        for ln in mp.read_text(encoding="utf-8", errors="replace").splitlines():
            m = re.match(r"\s*([A-Z][A-Z0-9_]*)\s*=\s*(\d+)\s*,", ln)
            if m:
                out.setdefault(int(m.group(2)), m.group(1))
    return out


def main() -> int:
    eff = load_effective()
    names = short_names()
    modn = mod_names()

    fam: dict[str, dict[int, int]] = defaultdict(dict)   # base -> {tier: itemId}
    for iid, sn in names.items():
        m = re.match(r"^(.*)_\+(\d)$", sn)
        base, tier = (m.group(1), int(m.group(2))) if m else (sn, 0)
        fam[base][tier] = iid

    adds: list[tuple[int, int, int, str]] = []   # (id, mod, val, base)
    items_fixed: set[int] = set()
    for base, tiers in fam.items():
        if len(tiers) < 2:
            continue
        cum: dict[int, int] = {}                 # mod -> max value across lower tiers
        for t in sorted(tiers):
            iid = tiers[t]
            cur = eff.get(iid, {})
            for mod, val in cum.items():
                if mod not in cur:
                    adds.append((iid, mod, val, f"{base}_+{t}"))
                    items_fixed.add(iid)
            for mod, val in cur.items():
                cum[mod] = max(cum.get(mod, val), val)

    adds.sort(key=lambda a: (a[0], a[1]))
    lines = [
        "-- Auto-generated by tools/gen_reforge_carryforward.py -- DO NOT EDIT.",
        "-- Fills mods that a higher upgrade tier dropped vs a lower tier.",
        "-- INSERT IGNORE + loads last: only fills genuine gaps, never overrides.",
        "",
    ]
    for iid, mod, val, who in adds:
        nm = modn.get(mod, f"mod{mod}")
        lines.append(f"INSERT IGNORE INTO `item_mods` VALUES ({iid},{mod},{val});"
                     f"  -- {who}: +{nm}")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"families with >=2 tiers scanned; {len(adds)} carry-forward mods "
          f"across {len(items_fixed)} items")
    # spot-check: Peltast's Cuissots +3 (23634) should regain mod 286
    p3 = [a for a in adds if a[0] == 23634]
    print("Peltast's Cuissots +3 (23634) carried:",
          [(modn.get(m, m), v) for _, m, v, _ in p3])
    print("WROTE", OUT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
