#!/usr/bin/env python3
"""
gen_windower_catalog.py
Generates the Windower addon data files for BOTH augment addons:

    tools/windower/augment_browser/data/catalog.lua
    tools/windower/augment_browser/data/categories.lua
    tools/windower/augment_trade/data/catalog.lua
    tools/windower/augment_trade/data/categories.lua

Sources:
    modules/custom/lua/augment_catalog.lua           (catalyst -> augment rows)
    modules/custom/lua/augment_affinity_catalog.lua  (category labels + affinity NMs)

The two addons previously shared hand-copied data files that drifted badly
(they still carried the pre-2026-07-06 24-category scheme). This script is
now the single owner of all four files -- never edit them manually.

Run from repo root: python tools/gen_windower_catalog.py
Re-run any time augment_catalog.lua or augment_affinity_catalog.lua changes.
"""
import re
import os

CATALOG_SRC  = 'modules/custom/lua/augment_catalog.lua'
AFFINITY_SRC = 'modules/custom/lua/augment_affinity_catalog.lua'
ADDON_DIRS = [
    'tools/windower/augment_browser/data',
    'tools/windower/augment_trade/data',
]

# ---- catalog rows ------------------------------------------------------------
with open(CATALOG_SRC, encoding='utf-8') as f:
    content = f.read()

# Match each entry:  [item_id] = { ... }   (fields in any order, no nested braces)
entry_re = re.compile(r'\[(\d+)\]\s*=\s*\{([^}]+)\}', re.DOTALL)

entries = []
for m in entry_re.finditer(content):
    body = m.group(2)
    cat   = re.search(r'\bcat\s*=\s*(\d+)',     body)
    tier  = re.search(r'\btier\s*=\s*(\d+)',    body)
    label = re.search(r"label\s*=\s*'([^']+)'", body)
    if not (cat and tier and label):
        continue
    entries.append({
        'id':    int(m.group(1)),
        'cat':   int(cat.group(1)),
        'tier':  int(tier.group(1)),
        'label': label.group(1),
    })

entries.sort(key=lambda e: (e['tier'], e['cat'], e['label']))

# ---- category metadata (labels + affinity NM per cat) -------------------------
with open(AFFINITY_SRC, encoding='utf-8') as f:
    aff = f.read()

cat_rows = []
aff_re = re.compile(
    r"\{\s*cat\s*=\s*(\d+)\s*,\s*bit\s*=\s*\d+\s*,\s*label\s*=\s*'([^']*)'\s*,\s*nm\s*=\s*'([^']*)'")
for m in aff_re.finditer(aff):
    cat_rows.append({
        'cat':   int(m.group(1)),
        'label': m.group(2),
        'nm':    m.group(3).replace('_', ' '),
    })
cat_rows.sort(key=lambda r: r['cat'])

if not entries or not cat_rows:
    raise SystemExit('parse failure: no catalog entries or no categories -- aborting, files unchanged')

bad_cats = sorted({e['cat'] for e in entries} - {r['cat'] for r in cat_rows})
if bad_cats:
    raise SystemExit(f'catalog rows reference unknown categories {bad_cats} -- fix the sources first')

# ---- write both addons ---------------------------------------------------------
def lua_str(s):
    return "'" + s.replace("'", "\\'") + "'"

catalog_lines = [
    '-- Auto-generated by tools/gen_windower_catalog.py -- do not edit manually.',
    '-- Source: modules/custom/lua/augment_catalog.lua',
    'return {',
]
for e in entries:
    catalog_lines.append(
        f"    [{e['id']:5}] = {{ cat = {e['cat']:2}, tier = {e['tier']}, label = {lua_str(e['label'])} }},")
catalog_lines.append('}')
catalog_text = '\n'.join(catalog_lines) + '\n'

cat_lines = [
    '-- Auto-generated by tools/gen_windower_catalog.py -- do not edit manually.',
    '-- Source: modules/custom/lua/augment_affinity_catalog.lua',
    '-- One row per augment category: display name + the affinity NM that unlocks it.',
    'return {',
]
for r in cat_rows:
    cat_lines.append(
        f"    [{r['cat']:2}] = {{ name = {lua_str(r['label'])}, nm = {lua_str(r['nm'])} }},")
cat_lines.append('}')
cat_text = '\n'.join(cat_lines) + '\n'

for d in ADDON_DIRS:
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(d, 'catalog.lua'), 'w', encoding='utf-8', newline='\n') as f:
        f.write(catalog_text)
    with open(os.path.join(d, 'categories.lua'), 'w', encoding='utf-8', newline='\n') as f:
        f.write(cat_text)
    print(f'{d}: {len(entries)} catalog entries, {len(cat_rows)} categories')
