#!/usr/bin/env python3
"""Regenerate modules/custom/lua/augment_item_names.lua.

itemId -> item name token used in the on-screen catalyst drop messages
(augment_catalyst_drops.lua, augment_dungeon_drops.lua via
gen_augment_dungeon_drops.py). Names are the FULL item_basic `name` column
('black_tiger_hide'), NOT the abbreviated log/sort name ('tiger_hide') the
pre-2026-07-10 file carried -- the website and !augwarp render item_basic
names, and the drop message must show the SAME name the player then looks up
on the augments page.

Covers the union of the previous file's ids and every augment_catalog.lua
catalyst (the old file was missing 8 of them, so their drop messages showed
only the stat label with no item name).

Run:  python tools/gen_augment_item_names.py     (cwd = repo root)
Then: python tools/gen_augment_dungeon_drops.py  (re-embeds names in the
      dungeon data) and re-run tools/docgen.
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT  = ROOT / "modules" / "custom" / "lua" / "augment_item_names.lua"


def main() -> int:
    # Existing ids (keep coverage for non-catalyst consumers of the file).
    ids: set[int] = set()
    if OUT.exists():
        for m in re.finditer(r"\[(\d+)\]\s*=", OUT.read_text(encoding="utf-8")):
            ids.add(int(m.group(1)))

    # Every catalog catalyst must have a name (drop messages depend on it).
    cat_text = (ROOT / "modules" / "custom" / "lua" / "augment_catalog.lua").read_text(encoding="utf-8")
    for m in re.finditer(r"^\s*\[(\d+)\]\s*=", cat_text, re.M):
        ids.add(int(m.group(1)))

    names: dict[int, str] = {}
    item_text = (ROOT / "sql" / "item_basic.sql").read_text(encoding="utf-8", errors="replace")
    for m in re.finditer(r"VALUES \((\d+),\d+,'([^']+)'", item_text):
        iid = int(m.group(1))
        if iid in ids and iid not in names:
            names[iid] = m.group(2)

    missing = sorted(ids - set(names))
    lines = [
        "-----------------------------------",
        "-- augment_item_names.lua",
        "-- AUTO-GENERATED by tools/gen_augment_item_names.py -- do not hand-edit.",
        "-- itemId -> full item_basic name token, shown in catalyst drop messages.",
        "-- Same names the website / !augwarp render, so every surface matches.",
        "-----------------------------------",
        "return {",
    ]
    for iid in sorted(names):
        lines.append(f"    [{iid}] = '{names[iid]}',")
    lines.append("}")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[item_names] wrote {len(names)} names ({len(missing)} ids not in item_basic: {missing[:10]})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
