"""
gen_restore_geo.py -- generate modules/custom/sql/restore_geo_retail.sql

Builds the full inverse of the 5 bouncer_*.sql files (the custom "Bouncer"
tank job that repurposed the GEO/job-21 slot), restoring retail Geomancer
from the repo's canonical sql/ dumps:

  1. abilities    REPLACE canonical rows for the 9 repurposed ability ids
  2. traits       DELETE job=21, re-INSERT canonical job=21 rows
  3. skill_ranks  restore the geo column for the 5 touched skillids
  4. spell_list   restore byte 21 (the GEO learn-level byte) of the jobs
                  blob for every spell that is GEO-castable in retail --
                  byte-21-only so other custom blob edits (e.g.
                  silencega_scroll.sql) are preserved
  5. item_equipment  strip bit 20 (1<<20, job 21) everywhere, then re-OR
                  it onto the canonical retail GEO-equippable items --
                  bit-level so any other custom mask bits are preserved

Companion C++ reverts (compiled, not data): src/map/grades.cpp GEO grade
row and src/map/job_points.cpp JOB_GEO JP spell grants.

Usage:  python tools/gen_restore_geo.py   (run from repo root or tools/)
Output is idempotent -- safe to apply more than once.
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "modules" / "custom" / "sql" / "restore_geo_retail.sql"

ABILITY_IDS = {343, 345, 347, 348, 349, 350, 351, 352, 377}
SKILL_IDS = {8, 29, 31, 44, 45}   # polearm, evasion, parrying, geomancy, handbell
GEO_BIT = 1 << 20                 # job 21 -> bit 20

def rows(path, table):
    pat = re.compile(r"^INSERT INTO `%s` VALUES \((.*)\);" % table)
    for line in (ROOT / "sql" / path).read_text(encoding="utf-8", errors="replace").splitlines():
        m = pat.match(line.strip())
        if m:
            yield m.group(1)

def split_fields(tup, n):
    """Split the first n comma-separated fields of a VALUES tuple,
    respecting single-quoted strings. Returns list of raw field strings."""
    out, cur, depth, inq, i = [], [], 0, False, 0
    while i < len(tup) and len(out) < n:
        c = tup[i]
        if inq:
            cur.append(c)
            if c == "'":
                inq = False
        else:
            if c == "'":
                inq = True
                cur.append(c)
            elif c == "," and depth == 0:
                out.append("".join(cur))
                cur = []
            elif c in "(":
                depth += 1
                cur.append(c)
            elif c == ")":
                depth -= 1
                cur.append(c)
            else:
                cur.append(c)
        i += 1
    if cur and len(out) < n:
        out.append("".join(cur))
    return out

lines = []
emit = lines.append

emit("-- ============================================================================")
emit("-- restore_geo_retail.sql   (GENERATED by tools/gen_restore_geo.py -- do not")
emit("-- hand-edit; regenerate instead)")
emit("--")
emit("-- Removes the custom 'Bouncer' tank job by restoring retail GEOMANCER on")
emit("-- job slot 21. Inverse of the five (now-deleted) bouncer_*.sql phases,")
emit("-- sourced from the repo's canonical sql/ dumps. Idempotent.")
emit("--")
emit("-- REQUIRES the companion C++ reverts to be compiled in (grades.cpp GEO row")
emit("-- restores the MP pool; job_points.cpp restores GEO JP spell grants) --")
emit("-- until then a job-21 character has 0 MP from grades.")
emit("-- ============================================================================")
emit("")

# --- 1) abilities -----------------------------------------------------------
emit("-- 1) Restore the 9 repurposed GEO ability rows.")
count = 0
for tup in rows("abilities.sql", "abilities"):
    aid = int(tup.split(",", 1)[0])
    if aid in ABILITY_IDS:
        emit("REPLACE INTO `abilities` VALUES (%s);" % tup)
        count += 1
assert count == len(ABILITY_IDS), f"abilities: expected {len(ABILITY_IDS)}, got {count}"
emit("")

# --- 2) traits --------------------------------------------------------------
emit("-- 2) Retail GEO traits (drops every custom job-21 trait, restores stock).")
emit("DELETE FROM `traits` WHERE `job` = 21;")
count = 0
for tup in rows("traits.sql", "traits"):
    f = split_fields(tup, 3)
    if len(f) == 3 and f[2].strip() == "21":
        emit("INSERT INTO `traits` VALUES (%s);" % tup)
        count += 1
assert count > 0, "traits: no job-21 rows found"
emit("")

# --- 3) skill_ranks ---------------------------------------------------------
emit("-- 3) Retail GEO skill grades (polearm/evasion/parrying off, geomancy/handbell on).")
count = 0
for tup in rows("skill_ranks.sql", "skill_ranks"):
    f = tup.split(",")
    sid = int(f[0])
    if sid in SKILL_IDS:
        # CREATE TABLE order: skillid, name, war..., geo is the job-21 column ->
        # field index = 1 (skillid) + 1 (name) + 21 - 1 = 22
        geo_val = f[22].strip()
        emit("UPDATE `skill_ranks` SET `geo` = %s WHERE `skillid` = %d;" % (geo_val, sid))
        count += 1
assert count == len(SKILL_IDS), f"skill_ranks: expected {len(SKILL_IDS)}, got {count}"
emit("")

# --- 4) spell_list ----------------------------------------------------------
emit("-- 4) Restore the GEO learn-level byte (byte 21 of the jobs blob) for every")
emit("--    retail GEO-castable spell. Byte-21-only: other custom blob edits survive.")
count = 0
for tup in rows("spell_list.sql", "spell_list"):
    f = split_fields(tup, 3)
    spellid = int(f[0])
    blob = f[2].strip()
    if not blob.startswith("0x"):
        continue
    geo_byte = blob[2:][40:42]
    if geo_byte and geo_byte != "00":
        emit("UPDATE `spell_list` SET `jobs` = INSERT(`jobs`, 21, 1, 0x%s) WHERE `spellid` = %d;" % (geo_byte.upper(), spellid))
        count += 1
assert count > 100, f"spell_list: suspiciously few GEO spells ({count})"
emit(f"-- ({count} spells restored)")
emit("")

# --- 5) item_equipment ------------------------------------------------------
emit("-- 5) Equip access: clear bit 20 everywhere (undoes chassis DRG/WAR grants,")
emit("--    itemization PLD/RUN grants and shield strip in one move), then re-OR")
emit("--    bit 20 onto the canonical retail GEO-equippable items.")
emit("UPDATE `item_equipment` SET `jobs` = `jobs` & ~1048576 WHERE (`jobs` & 1048576) <> 0;")
geo_items = []
for tup in rows("item_equipment.sql", "item_equipment"):
    f = split_fields(tup, 5)
    item_id = int(f[0])
    jobs = int(f[4])
    if jobs & GEO_BIT:
        geo_items.append(item_id)
assert len(geo_items) > 100, f"item_equipment: suspiciously few GEO items ({len(geo_items)})"
for i in range(0, len(geo_items), 250):
    chunk = ",".join(str(x) for x in geo_items[i:i + 250])
    emit("UPDATE `item_equipment` SET `jobs` = `jobs` | 1048576 WHERE `itemId` IN (%s);" % chunk)
emit(f"-- ({len(geo_items)} items restored)")
emit("")

OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote {OUT} ({len(lines)} lines)")
