# Build modules/custom/lua/hades_armor_catalog.lua from exports/gear_source_audit.csv.
# Sourced 119 armor: 499-999 by +tier and score. Invasion-only / no real source: 1499.
# Omen-only Caturae bodies: 949 (Invasion is retired; Omen is not a live farm).

$ErrorActionPreference = 'Stop'
$root   = Split-Path -Parent $PSScriptRoot
$csv    = Join-Path $root 'exports\gear_source_audit.csv'
$out    = Join-Path $root 'modules\custom\lua\hades_armor_catalog.lua'
$slots  = @('Head', 'Body', 'Hands', 'Legs', 'Feet')

function Armor-Price([string]$name, [int]$score, [bool]$sourced, [string]$relaunch, [string]$slot) {
    if (-not $sourced) { return 1499 }
    if ($slot -eq 'Body' -and $relaunch -eq 'Omen') { return 949 }
    $tier = 0
    if ($name -match '\+3$') { $tier = 3 }
    elseif ($name -match '\+2$') { $tier = 2 }
    elseif ($name -match '\+1$') { $tier = 1 }
    $base = 499 + ($tier * 125)
    $bump = [Math]::Min(100, [int]($score / 8))
    return [Math]::Min(999, $base + $bump)
}

function Esc([string]$s) {
    return ($s -replace '\\', '\\' -replace "'", "\\'")
}

$armor = @()
Import-Csv $csv | ForEach-Object {
    $ilvl = 0; [void][int]::TryParse($_.ilvl, [ref]$ilvl)
    if ($slots -notcontains $_.slot -or $ilvl -lt 119) { return }
    $score = 0; [void][int]::TryParse($_.score, [ref]$score)
    $sourced = [bool]($_.retail_source -or $_.relaunch_source)
    $armor += [pscustomobject]@{
        id      = [int]$_.item_id
        name    = $_.name
        slot    = $_.slot
        score   = $score
        sourced = $sourced
        relaunch = $_.relaunch_source
        retail   = $_.retail_source
    }
}

$unsourced = $armor | Where-Object { -not $_.sourced }
$pickU = New-Object System.Collections.Generic.List[object]
$seen  = @{}

function Add-Pick($row) {
    if (-not $row) { return }
    if ($seen.ContainsKey($row.id)) { return }
    $seen[$row.id] = $true
    $pickU.Add($row)
}

foreach ($row in ($unsourced | Where-Object { $_.name -match '^(Ikenga|Gleti|Sakpata|Mpaca|Agwu|Bunzi|Nyame|Hjarrandi|Crepuscular)' })) {
    Add-Pick $row
}
foreach ($row in ($unsourced | Where-Object { $_.name -match '\+2$' -and $_.name -match '^(Sulevia|Meghanada|Ayanmo|Flamma|Mummu|Mallquis|Hizamaru|Jhakri|Inyanga|Taliah)' })) {
    Add-Pick $row
}
foreach ($row in ($unsourced | Sort-Object score -Descending)) {
    if ($pickU.Count -ge 100) { break }
    Add-Pick $row
}

$eligible = $armor | Where-Object {
    $_.sourced -and
    $_.relaunch -notmatch 'AF/Relic/Emp' -and
    $_.relaunch -notmatch 'Dynamis \+4' -and
    $_.relaunch -notmatch 'Infamy'
}
$pickS = New-Object System.Collections.Generic.List[object]
$slotCount = @{ Head = 0; Body = 0; Hands = 0; Legs = 0; Feet = 0 }
$familyCount = @{}
function FamilyOf($name) {
    return (($name -replace ' \+[1234]$', '') -split ' ')[0]
}

foreach ($row in ($eligible | Sort-Object score -Descending)) {
    if ($pickS.Count -ge 100) { break }
    if ($seen.ContainsKey($row.id)) { continue }
    $fam = FamilyOf $row.name
    $have = if ($familyCount.ContainsKey($fam)) { $familyCount[$fam] } else { 0 }
    if ($have -ge 4) { continue }
    if ($slotCount[$row.slot] -ge 22) { continue }
    $seen[$row.id] = $true
    $familyCount[$fam] = $have + 1
    $slotCount[$row.slot] = $slotCount[$row.slot] + 1
    $pickS.Add($row)
}

$all = @($pickU + $pickS) | Sort-Object id
if ($all.Count -lt 100) { throw "armor pool too small: $($all.Count)" }

$lines = New-Object System.Collections.Generic.List[string]
[void]$lines.Add('-----------------------------------')
[void]$lines.Add('-- hades_armor_catalog.lua')
[void]$lines.Add('--')
[void]$lines.Add('-- Weekend Mail stall. One piece per UTC week, same name for')
[void]$lines.Add('-- every player. Generated by tools/gen_hades_armor_pool.ps1')
[void]$lines.Add('-- from exports/gear_source_audit.csv.')
[void]$lines.Add('--')
[void]$lines.Add('-- sourced = has a retail or curated relaunch source.')
[void]$lines.Add('-- Invasion-only pieces are unsourced and cost 1499.')
[void]$lines.Add('-- Sourced pieces cost 499-999 from +tier and score.')
[void]$lines.Add('-- Omen Caturae bodies stay sourced but cost OMEN_BODY_PRICE.')
[void]$lines.Add('-----------------------------------')
[void]$lines.Add("local CATALOG_KEY = 'modules/custom/lua/hades_armor_catalog'")
[void]$lines.Add('local C = package.loaded[CATALOG_KEY]')
[void]$lines.Add("if type(C) ~= 'table' then")
[void]$lines.Add('    C = {}')
[void]$lines.Add('end')
[void]$lines.Add('package.loaded[CATALOG_KEY] = C')
[void]$lines.Add('')
[void]$lines.Add('C.UNSOURCED_PRICE = 1499')
[void]$lines.Add('C.SOURCED_LO      = 499')
[void]$lines.Add('C.SOURCED_HI      = 999')
[void]$lines.Add('C.OMEN_BODY_PRICE = 949')
[void]$lines.Add('')
[void]$lines.Add('C.items =')
[void]$lines.Add('{')

$uCount = 0
foreach ($row in $all) {
    $price = Armor-Price $row.name $row.score $row.sourced $row.relaunch $row.slot
    $src = 'true'
    if (-not $row.sourced) {
        $src = 'false'
        $uCount++
    }
    $name = Esc $row.name
    [void]$lines.Add(("    {{ id = {0}, name = '{1}', slot = '{2}', sourced = {3}, price = {4} }}," -f $row.id, $name, $row.slot, $src, $price))
}

[void]$lines.Add('}')
[void]$lines.Add('')
[void]$lines.Add('C.byId = {}')
[void]$lines.Add('for _, row in ipairs(C.items) do')
[void]$lines.Add('    C.byId[row.id] = row')
[void]$lines.Add('end')
[void]$lines.Add('')
[void]$lines.Add('function C.weeklyPiece(weekId)')
[void]$lines.Add('    local n = #C.items')
[void]$lines.Add('    if n == 0 then')
[void]$lines.Add('        return nil')
[void]$lines.Add('    end')
[void]$lines.Add('    weekId = weekId or tonumber(os.date(''!%Y%W''))')
[void]$lines.Add('    return C.items[(((weekId or 0) * 29) % n) + 1]')
[void]$lines.Add('end')
[void]$lines.Add('')
[void]$lines.Add('return C')
[void]$lines.Add('')

[IO.File]::WriteAllText($out, ($lines -join "`n"), [Text.UTF8Encoding]::new($false))
Write-Output ("wrote {0} pieces ({1} unsourced @1499, {2} sourced 499-999) -> {3}" -f $all.Count, $uCount, ($all.Count - $uCount), $out)
