#!/usr/bin/env python3
"""
gen_windower_catalog.py
Generates tools/windower/augment_browser/data/catalog.lua
from modules/custom/lua/augment_catalog.lua.

Run from repo root: python3 tools/gen_windower_catalog.py
Re-run any time augment_catalog.lua changes.
"""
import re
import os

SRC = 'modules/custom/lua/augment_catalog.lua'
DST = 'tools/windower/augment_browser/data/catalog.lua'

with open(SRC, encoding='utf-8') as f:
    content = f.read()

# Match each entry:  [item_id] = { ... }
# Fields can appear in any order inside the braces.
entry_re = re.compile(r'\[(\d+)\]\s*=\s*\{([^}]+)\}', re.DOTALL)

entries = []
for m in entry_re.finditer(content):
    item_id = int(m.group(1))
    body    = m.group(2)

    cat   = re.search(r'\bcat\s*=\s*(\d+)',     body)
    tier  = re.search(r'\btier\s*=\s*(\d+)',    body)
    label = re.search(r"label\s*=\s*'([^']+)'", body)

    if not (cat and tier and label):
        continue

    entries.append({
        'id':    item_id,
        'cat':   int(cat.group(1)),
        'tier':  int(tier.group(1)),
        'label': label.group(1),
    })

entries.sort(key=lambda e: (e['tier'], e['cat'], e['label']))

os.makedirs(os.path.dirname(DST), exist_ok=True)
with open(DST, 'w', encoding='utf-8', newline='\n') as f:
    f.write('-- Auto-generated by tools/gen_windower_catalog.py — do not edit manually.\n')
    f.write('-- Source: modules/custom/lua/augment_catalog.lua\n')
    f.write('return {\n')
    for e in entries:
        label_lua = "'" + e['label'].replace("'", "\\'") + "'"
        f.write(f"    [{e['id']:5}] = {{ cat = {e['cat']:2}, tier = {e['tier']}, label = {label_lua} }},\n")
    f.write('}\n')

print(f'Generated {len(entries)} entries -> {DST}')
