"""Gap-fill item_mods for the +3 reforge line from FRESH BG-Wiki stats
(tools/plus3_fresh_stats.json, re-scraped complete). Reuses the +4 parser and
mod-map, plus +3-specific entries: abbreviated stat aliases ("Mag. Acc.") and
weapon-skill / misc mods. INSERT IGNORE => only missing mods are added.

Run after rescrape_plus3.py.  Writes sql/zz_reforge_plus3_displayed_stats.sql.
"""
from __future__ import annotations
import sys, json
from pathlib import Path
from collections import Counter
sys.path.insert(0, r'D:\server')
from tools.gen_plus4_displayed_mods import STAT_TO_MOD, tokenize, norm

REPO = Path(r'D:\server')

# +3-specific additions (verified vs scripts/enum/mod.lua). All stored as-is.
EXTRA = {
    # abbreviated stat aliases used on some +3 BG-Wiki pages
    'Acc.': (25, 1), 'Atk.': (23, 1), 'Rng. Acc.': (26, 1), 'Rng. Atk.': (24, 1),
    'Mag. Acc.': (30, 1), 'Mag. Atk. B.': (28, 1), 'Mag. Def. B.': (29, 1),
    'M. Def. B.': (29, 1), 'Mag. Eva.': (31, 1), 'Eva.': (68, 1),
    # weapon / combat skills (X skill +N)
    'Hand-to-Hand skill': (80, 1), 'Dagger skill': (81, 1), 'Sword skill': (82, 1),
    'Great Sword skill': (83, 1), 'Axe skill': (84, 1), 'Great Axe skill': (85, 1),
    'Scythe skill': (86, 1), 'Polearm skill': (87, 1), 'Katana skill': (88, 1),
    'Great Katana skill': (89, 1), 'Club skill': (90, 1), 'Staff skill': (91, 1),
    'Archery skill': (104, 1), 'Marksmanship skill': (105, 1),
    'Wind instrument skill': (121, 1), 'String instrument skill': (120, 1),
    # specials with a clean engine mod
    'TP Bonus': (345, 1), 'Counter': (291, 1), 'Martial Arts': (173, 1),
    'Kick Attacks': (292, 1), 'Treasure Hunter': (303, 1), 'Despoil': (896, 1),
    'Magic burst damage II': (274, 1), 'Enhancing magic duration': (890, 1),
    # casing variants + a few more clean mods seen on +1/+2 pages (verified ids)
    'Magic Burst damage': (487, 1), 'Magic Burst damage II': (274, 1),
    'Tactical Parry': (486, 1), 'Retaliation': (414, 1),
    'Regain': (368, 1), 'Inquartata': (963, 1),
}
MAP = {**STAT_TO_MOD, **EXTRA}


def main():
    fresh = json.loads((REPO / 'tools' / 'plus3_fresh_stats.json').read_text(encoding='utf-8'))
    rows, skipped, mapped, pelt = [], Counter(), Counter(), []
    for iid, d in fresh.items():
        seen = set()
        for name, val in tokenize(d['stats']):
            if not name:
                continue
            hit = MAP.get(norm(name))
            if not hit:
                skipped[norm(name)] += 1
                continue
            mid, scale = hit
            if mid in seen:
                continue
            seen.add(mid)
            v = val * scale
            if v == 0:
                continue
            rows.append((int(iid), mid, v))
            mapped[norm(name)] += 1
            if iid == '23433':
                pelt.append((mid, v, name))

    by_item = {}
    for iid, mid, v in rows:
        by_item.setdefault(iid, []).append((mid, v))
    out = REPO / 'sql' / 'zz_reforge_plus3_displayed_stats.sql'
    lines = [
        '-- ---------------------------------------------------------------------------',
        '-- zz_reforge_plus3_displayed_stats.sql  (generated by',
        '-- tools/gen_plus3_displayed_mods.py from FRESH BG-Wiki stats)',
        '--',
        '-- Same fix as the +4 line, for +3: the original data dropped fancy stat',
        '-- formats (Weapon skill damage, abbreviated names, etc.). Re-scraped each +3',
        "-- item's complete stats and gap-fills the engine mods. INSERT IGNORE => only",
        '-- missing mods are added; existing values are kept. Skipped: pet/wyvern/avatar',
        '-- stats (need item_mods_pet) and stats with no clean engine mod.',
        '-- ---------------------------------------------------------------------------',
        '',
    ]
    for iid in sorted(by_item):
        vals = ','.join(f'({iid},{m},{v})' for m, v in sorted(by_item[iid]))
        lines.append(f'INSERT IGNORE INTO `item_mods` VALUES {vals};')
    out.write_text('\n'.join(lines) + '\n', encoding='utf-8')

    print(f"items: {len(by_item)} | INSERT IGNORE rows: {len(rows)} | distinct stats mapped: {len(mapped)}")
    print(f"\nPeltast's mezail +3 (23433) generated rows:")
    for m, v, n in sorted(pelt):
        print(f"   mod {m:>4} = {v:<5} ({n})")
    print(f"\ntop SKIPPED ({len(skipped)} distinct, {sum(skipped.values())} instances):")
    for n, c in skipped.most_common(25):
        print(f"   {c:3}  {n}")
    print(f"\nwrote {out}")


if __name__ == '__main__':
    main()
