"""Gap-fill item_mods for the +1/+2 reforge tiers from FRESH BG-Wiki stats
(tools/plus12_fresh_stats.json). Reuses the +3 stat->mod map (STAT_TO_MOD +
EXTRA). INSERT IGNORE => only missing mods are added.

Run after rescrape_tier.py produced plus12_fresh_stats.json.
Writes sql/zz_reforge_plus12_displayed_stats.sql.
"""
from __future__ import annotations
import sys, json
from pathlib import Path
from collections import Counter
sys.path.insert(0, r'D:\server')
from tools.gen_plus4_displayed_mods import tokenize, norm
from tools.gen_plus3_displayed_mods import MAP   # STAT_TO_MOD + EXTRA (+3 aliases/skills)

REPO = Path(r'D:\server')


def main():
    fresh = json.loads((REPO / 'tools' / 'plus12_fresh_stats.json').read_text(encoding='utf-8'))
    rows, skipped, mapped = [], Counter(), Counter()
    for iid, d in fresh.items():
        seen = set()
        for name, val in tokenize(d['stats']):
            if not name:
                continue
            hit = MAP.get(norm(name))
            if not hit:
                skipped[norm(name)] += 1
                continue
            mid, scale = hit
            if mid in seen:
                continue
            seen.add(mid)
            v = val * scale
            if v == 0:
                continue
            rows.append((int(iid), mid, v))
            mapped[norm(name)] += 1

    by_item = {}
    for iid, mid, v in rows:
        by_item.setdefault(iid, []).append((mid, v))
    out = REPO / 'sql' / 'zz_reforge_plus12_displayed_stats.sql'
    lines = [
        '-- ---------------------------------------------------------------------------',
        '-- zz_reforge_plus12_displayed_stats.sql  (generated by',
        '-- tools/gen_plus12_displayed_mods.py from FRESH BG-Wiki stats)',
        '--',
        '-- Same fix as the +3/+4 lines, for the +1/+2 reforged tiers. Gap-fills the',
        '-- mods the client tooltip shows but the server was missing. INSERT IGNORE =>',
        '-- only missing mods are added; existing values kept. Pet/wyvern + no-mod stats',
        '-- are skipped.',
        '-- ---------------------------------------------------------------------------',
        '',
    ]
    for iid in sorted(by_item):
        vals = ','.join(f'({iid},{m},{v})' for m, v in sorted(by_item[iid]))
        lines.append(f'INSERT IGNORE INTO `item_mods` VALUES {vals};')
    out.write_text('\n'.join(lines) + '\n', encoding='utf-8')

    print(f"items: {len(by_item)} | INSERT IGNORE rows: {len(rows)} | distinct stats mapped: {len(mapped)}")
    print(f"\ntop SKIPPED ({len(skipped)} distinct, {sum(skipped.values())} instances):")
    for n, c in skipped.most_common(25):
        print(f"   {c:3}  {n}")
    print(f"\nwrote {out}")


if __name__ == '__main__':
    main()
