-----------------------------------
-- !augwarp <stat>
-- Warp to a zone where a catalyst for the named augment drops.
--   !augwarp haste     -- one match  -> warps straight there
--   !augwarp attack    -- many matches -> pops a menu to PICK the destination
--   !augwarp           -- usage help
-- Matches the typed text against augment stat labels first, then catalyst item
-- names, then each row's retired label spelling (`alias`), so wording a player
-- learned before a catalog rename still finds the right catalyst. A single
-- match warps immediately; multiple matches open a customMenu (up to 8,
-- most-accessible first) so you choose where to go.
--
-- desc: Warp to a zone that drops a catalyst for a given augment stat. Usage: !augwarp <stat or catalyst name> (e.g. !augwarp Haste).
--
-- Drop locations come from modules/custom/lua/catalyst_warp_table.lua
-- (generated by tools/gen_catalyst_warp_table.py from the mob droplist +
-- spawn points). Stat NAMES are re-read from augment_catalog.lua at match
-- time: that catalog is what the Moogle and the website print, while the warp
-- table is only a build artifact, so a table left unregenerated across a rename
-- can never make !augwarp advertise a stat name that no longer exists.
-- Permission 0 (all players), like !affinitynm.
-----------------------------------
---@type TCommand
local commandObj = {}

commandObj.cmdprops =
{
    permission = 0,
    parameters = 's',
}

commandObj.onTrigger = function(player, arg)
    local SYS = xi.msg.channel.SYSTEM_3
    local catalog  = require('modules/custom/lua/catalyst_warp_table')
    local augments = require('modules/custom/lua/augment_catalog')

    if not arg or arg == '' then
        player:printToPlayer('!augwarp <stat> -- warp to a zone that drops a catalyst for that augment.', SYS)
        player:printToPlayer('  e.g.  !augwarp Haste   |   !augwarp Attack   |   !augwarp Store', SYS)
        return
    end

    local needle  = string.lower(arg)
    local matches = {}
    for itemId, e in pairs(catalog) do
        -- Live label wins over the generated one (see header).
        local def = augments[itemId]
        if def and def.label then
            e.label = def.label
        end

        if string.find(string.lower(e.label), needle, 1, true)
            or string.find(string.lower(e.item), needle, 1, true)
            or (e.alias ~= nil and string.find(string.lower(e.alias), needle, 1, true)) then
            table.insert(matches, e)
        end
    end

    if #matches == 0 then
        player:printToPlayer(string.format(
            'No augment catalyst matches "%s". Try a stat (Haste, Attack, STR) or a catalyst item name.', arg), SYS)
        return
    end

    -- Most accessible first: exact stat match, then lowest tier, then lowest mob level.
    local function isExact(e)
        return string.lower(e.label) == needle
            or (e.alias ~= nil and string.lower(e.alias) == needle)
    end

    table.sort(matches, function(a, b)
        local ax = isExact(a)
        local bx = isExact(b)
        if ax ~= bx then return ax end
        if a.tier ~= b.tier then return a.tier < b.tier end
        return (a.lvl or 999) < (b.lvl or 999)
    end)

    -- Warp (or, for spawn-less drops, tell the player where to hunt).
    local function goTo(q, e)
        if e.noWarp then
            q:printToPlayer(string.format(
                '%s (%s augment, %.1f%%) drops from %s in %s -- no fixed spawn point, so no warp. Hunt it there.',
                e.item, e.label, (e.rate or 0) / 10, e.mob, e.zoneName), SYS)
            return
        end
        q:printToPlayer(string.format(
            'Warping to %s -- %s drops %s (%s augment, Tier %d, %.1f%% drop rate).',
            e.zoneName, e.mob, e.item, e.label, e.tier, (e.rate or 0) / 10), SYS)
        q:setPos(e.x, e.y, e.z, 0, e.zone)
    end

    -- Single match: just go.
    if #matches == 1 then
        goTo(player, matches[1])
        return
    end

    -- Multiple: pop a picker menu (client renders up to 8 options).
    local shown   = math.min(#matches, 8)
    local options = {}
    for i = 1, shown do
        local e = matches[i]
        -- Keep each label well under the 128-byte per-option cap; no double quotes.
        local label = string.format('%s | %s T%d', e.label, e.item, e.tier)
        options[i] = { label, function(q) goTo(q, e) end }
    end
    options[shown + 1] = { 'Close', function() end }

    local title = 'Augwarp: ' .. tostring(arg):gsub('"', '')
    player:timer(30, function(pl)
        pl:customMenu({ title = title, options = options })
    end)

    if #matches > shown then
        player:printToPlayer(string.format(
            '  (+%d more -- refine with a catalyst item name, e.g. !augwarp %s)',
            #matches - shown, matches[1].item), SYS)
    end
end

return commandObj
