-----------------------------------
-- !augwarp <stat>
-- Warp to a zone where a catalyst for the named augment drops.
--   !augwarp haste     -- warps to a mob that drops a Haste-augment catalyst
--   !augwarp store     -- partial match -> 'Store TP' catalysts
--   !augwarp           -- usage help
-- Matches the typed text against augment stat labels first, then catalyst item
-- names. If several catalysts match, it warps to the most accessible one and
-- lists the rest so you can refine by item name.
--
-- desc: Warp to a zone that drops a catalyst for a given augment stat. Usage: !augwarp <stat or catalyst name> (e.g. !augwarp Haste).
--
-- Drop locations come from modules/custom/lua/catalyst_warp_table.lua
-- (generated by tools/gen_catalyst_warp_table.py from the mob droplist +
-- spawn points). Permission 0 (all players), like !affinitynm.
-----------------------------------
---@type TCommand
local commandObj = {}

commandObj.cmdprops =
{
    permission = 0,
    parameters = 's',
}

commandObj.onTrigger = function(player, arg)
    local SYS = xi.msg.channel.SYSTEM_3
    local catalog = require('modules/custom/lua/catalyst_warp_table')

    if not arg or arg == '' then
        player:printToPlayer('!augwarp <stat> -- warp to a zone that drops a catalyst for that augment.', SYS)
        player:printToPlayer('  e.g.  !augwarp Haste   |   !augwarp Crit   |   !augwarp Store', SYS)
        return
    end

    local needle  = string.lower(arg)
    local matches = {}
    for _, e in pairs(catalog) do
        if string.find(string.lower(e.label), needle, 1, true)
            or string.find(string.lower(e.item), needle, 1, true) then
            table.insert(matches, e)
        end
    end

    if #matches == 0 then
        player:printToPlayer(string.format(
            'No augment catalyst matches "%s". Try a stat (Haste, Attack, STR) or a catalyst item name.', arg), SYS)
        return
    end

    -- Most accessible first: exact stat match, then lowest tier, then lowest mob level.
    table.sort(matches, function(a, b)
        local ax = (string.lower(a.label) == needle)
        local bx = (string.lower(b.label) == needle)
        if ax ~= bx then return ax end
        if a.tier ~= b.tier then return a.tier < b.tier end
        return (a.lvl or 999) < (b.lvl or 999)
    end)

    local best = matches[1]

    if #matches > 1 then
        player:printToPlayer(string.format(
            '%d catalysts match "%s" -- warping to the most accessible. Refine with  !augwarp <item name>:',
            #matches, arg), SYS)
        for i = 1, math.min(#matches, 8) do
            local e = matches[i]
            player:printToPlayer(string.format('  %-22s [%s, T%d] @ %s', e.item, e.label, e.tier, e.zoneName), SYS)
        end
        if #matches > 8 then
            player:printToPlayer(string.format('  ...and %d more.', #matches - 8), SYS)
        end
    end

    if best.noWarp then
        player:printToPlayer(string.format(
            '%s (%s augment) drops from %s in %s -- a notorious monster with no fixed spawn, so no warp. Hunt it there.',
            best.item, best.label, best.mob, best.zoneName), SYS)
        return
    end

    player:printToPlayer(string.format(
        'Warping to %s -- %s drops %s (%s augment, Tier %d).',
        best.zoneName, best.mob, best.item, best.label, best.tier), SYS)
    player:setPos(best.x, best.y, best.z, 0, best.zone)
end

return commandObj
