-- =============================================================================
-- zz_grant_judge_gear_jbae.sql  --  NEUTRALIZED 2026-06-21 (was duplicating items)
--
-- !!! DO NOT PUT A ONE-TIME ITEM GRANT IN A zz_*.sql FILE !!!
--
-- ORIGINAL PURPOSE (one-time): grant player Jbae a full 13-piece Judge gear set,
-- each piece augmented with Exp. Point +33% in all 5 slots.
--
-- THE BUG IT CAUSED: this file lives in sql/zz_*.sql, which on the Azure box
-- tools/_apply_changed_sql.sh applies UNCONDITIONALLY on EVERY deploy/restart
-- (the zz_* set has no change-ledger -- it is for IDEMPOTENT full-table
-- replacements, NOT one-time grants). The INSERT used base_slot = MAX(slot)+1,
-- so every deploy APPENDED ANOTHER full Judge set to Jbae's inventory --
-- duplicating 13 items per restart and bloating the inventory toward its cap.
-- Same root-cause class as zz_repair_job_merits.sql (neutralized same day).
--
-- FIX: emptied to a NO-OP so deploys stop duplicating the set. Jbae keeps the
-- copies already granted (this does NOT remove them -- any duplicate-cleanup is
-- a separate manual step). The original INSERT is in git history if ever needed;
-- to grant a set again, run it BY HAND once -- never as a zz_*.sql.
-- =============================================================================

-- Intentionally a no-op. Do not add item grants here.
DO 1;
