-- ---------------------------------------------------------------------------
-- zz_obtainable_gap_fills.sql  (generated by tools/gen_obtainable_gap_fills.py)
--
-- Final gap-fill for OBTAINABLE gear flagged by reconcile_gear_mods.py
-- --obtainable: a handful of iLvl 100-119 weapons missing item_mods, a few
-- reforged +3/+4 missing one late-mapped stat, and ammo. Values are the
-- BG-Wiki reference values. INSERT IGNORE => only missing mods are added.
-- Statless-by-design items (Onion Sword line) are intentionally excluded.
-- ---------------------------------------------------------------------------

INSERT IGNORE INTO `item_mods` VALUES (20639,9,6),(20639,25,13);
INSERT IGNORE INTO `item_mods` VALUES (20723,23,23),(20723,25,5);
INSERT IGNORE INTO `item_mods` VALUES (20744,2,60),(20744,23,10),(20744,25,10),(20744,161,-100),(20744,384,100);
INSERT IGNORE INTO `item_mods` VALUES (20779,2,40),(20779,8,7);
INSERT IGNORE INTO `item_mods` VALUES (20789,2,60),(20789,8,5),(20789,23,10),(20789,25,10),(20789,288,1);
INSERT IGNORE INTO `item_mods` VALUES (20878,2,60),(20878,23,10),(20878,25,10),(20878,288,1);
INSERT IGNORE INTO `item_mods` VALUES (21009,9,6),(21009,25,13);
INSERT IGNORE INTO `item_mods` VALUES (21134,2,60),(21134,12,2),(21134,13,2),(21134,23,10),(21134,25,10),(21134,311,6),(21134,384,100);
INSERT IGNORE INTO `item_mods` VALUES (21206,8,6),(21206,23,10),(21206,73,5),(21206,165,5);
INSERT IGNORE INTO `item_mods` VALUES (21323,26,3);
INSERT IGNORE INTO `item_mods` VALUES (21351,23,12),(21351,26,3);
INSERT IGNORE INTO `item_mods` VALUES (21556,9,7),(21556,11,7),(21556,25,47),(21556,68,27);
INSERT IGNORE INTO `item_mods` VALUES (21610,8,3),(21610,13,3),(21610,25,17),(21610,28,14),(21610,311,108);
INSERT IGNORE INTO `item_mods` VALUES (21708,8,10),(21708,25,27);
INSERT IGNORE INTO `item_mods` VALUES (23642,963,4);
INSERT IGNORE INTO `item_mods` VALUES (23688,414,31);
INSERT IGNORE INTO `item_mods` VALUES (23937,274,4);
INSERT IGNORE INTO `item_mods` VALUES (24056,274,3);
